
project:
  type: website
  output-dir: ../_site/pt

website:
  page-navigation: true # não funciona
  back-to-top-navigation: true
  image: unifal-logo.png # não funciona
  reader-mode: true # funciona
  google-analytics: "G-S1L73VGCG5"
  title: "" # omite-se o título pra não duplicar nome na aba
  favicon: avatar.png # ícone da aba da página
  
  sidebar:
    contents:
      - section: "**bioQuanti**"
        contents:
          - text: "O site"
            href: index.qmd
          - text: "ERЯƎ - Ensino Reprodutível"
            href: erre.qmd
          # - text: "Bioquímica de gente, de bicho, e de planta"
          #   href: nivel/superior/biqTxT/index_txt.qmd

      - section: "**Jmol & R no Ensino Básico**"
        contents:
          - text: "Moléculas & Jmol"
            href: nivel/basico/Curso/jmol_curso.qmd
          - text: "Gráficos e mapas interativos & R"
            href: nivel/basico/Curso/r_curso.qmd

  navbar:
    search: true
    logo: logo-bioquanti.png # logo ao lado esquerdo da Home

    left:
      - text: "Estrutura e Jmol"
        id: sup-menu  # identifica para cor parcial no navbar
        menu: 
          - text: "Introdução"
            href: nivel/superior/jmol/index_jmol.html
          - text: "Características do Jmol"
            href: nivel/superior/jmol/carac.html
          - text: "Comandos"
            href: nivel/superior/jmol/comandos.html
          - text: "Água"
            href: nivel/superior/jmol/agua.html
          - text: "Aminoácidos"
            href: nivel/superior/jmol/aminoacidos.html
          - text: "Proteínas"
            href: nivel/superior/jmol/proteina.html
          - text: "Enzimas"
            href: nivel/superior/jmol/enzima.html
          - text: "Carboidratos"
            href: nivel/superior/jmol/carboidrato.html
          - text: "Lipídios"
            href: nivel/superior/jmol/lipidio.html 
          - text: "Ácidos Nucleicos"
            href: nivel/superior/jmol/acnucleico.html
        
            
      - text: "Função & R"
        id: sup-menu   # identifica para cor parcial no navbar
        menu: 
          - text: "I. INTRODUÇÃO"
      #      href: ...
          - text: "R & RStudio"
            href: nivel/superior/r/index_r.html
          - text: "1. Biomoléculas"
            href: nivel/superior/r/biomoleculas.html
          - text: "2. Sistemas tampão"
            href: nivel/superior/r/tampoes.html
          - text: "II. ESTRUTURA E FUNÇÃO"
       #     href: ...
          - text: "3. Aminoácidos"
            href: nivel/superior/r/aminoacid.html
          - text: "4. Proteínas"
            href: nivel/superior/r/proteinas.html
          - text: "5. Enzimas"
            href: nivel/superior/r/enzimas.html
          - text: "6. Inibição Enzimática"
            href: nivel/superior/r/enzInib.html
          - text: "7. Interação Molecular"
            href: nivel/superior/r/binding.html
          - text: "8. Ácidos Nucleicos"
            href: nivel/superior/r/acnucleic.html
          - text: "9. Biomembranas"
            href: nivel/superior/r/membranas.qmd
          - text: "III. METABOLISMO"
     #       href: ...
          - text: "10. Biotermodinâmica"
            href: nivel/superior/r/biotermodin.html
          - text: "11. Metabolismo"
            href: nivel/superior/r/metabolismo.html 
          - text: "12. Redes Metabólicas"
            href: nivel/superior/r/redes.html
          - text: "IV. OUTROS"
     #       href: ...
          - text: "13. Planejamento Experimental"
            href: nivel/superior/r/planejExper.html
          - text: "Referências"
            href: nivel/superior/r/referências.html   
            
      - text: "Dinâmica & Sisma"
        id: sup-menu   # identifica para cor parcial no navbar
        menu: 
          - text: "Sisma"
            href: nivel/superior/sisma/index_sisma.qmd
          - text: "Exemplos"
            href: nivel/superior/sisma/sisma_ex.qmd
            
      - text: "JSPlotly em Bioquímica"
        id: sup-menu
        menu:
          - text: "Introdução"
            
      - text: "Jmol no Ensino Básico"
        id: bas-menu
        menu:
          - text: "Introdução"
            href: nivel/basico/Jardim/index_Jardim.qmd
          - text: "Orgânicas"
            href: nivel/basico/Jardim/organica.qmd
          - text: "Inorgânicas"
            href: nivel/basico/Jardim/inorganica.qmd
          - text: "Biomoléculas"
            href: nivel/basico/Jardim/biomol.qmd
          - text: "Farmacológicas"
            href: nivel/basico/Jardim/farmac.qmd
          - text: "Medicinais"
            href: nivel/basico/Jardim/medicin.qmd
          - text: "Toxicológicas"
            href: nivel/basico/Jardim/toxicol.qmd
          - text: "Nutricionais"
            href: nivel/basico/Jardim/nutri.qmd
          - text: "Sabores"
            href: nivel/basico/Jardim/sabores.qmd
          - text: "Ambientais"
            href: nivel/basico/Jardim/ambiental.qmd
          - text: "Peçonhas"
            href: nivel/basico/Jardim/peconhentos.qmd
          - text: "Aromas"
            href: nivel/basico/Jardim/aromas.qmd
          - text: "Industriais"
            href: nivel/basico/Jardim/industrial.qmd
          - text: "Plantas Tóxicas"
            href: nivel/basico/Jardim/plantasToxicas.qmd
          - text: "Supramoleculares"
            href: nivel/basico/Jardim/supramol.qmd

      - text: "R no Ensino Básico"
        id: bas-menu  # identifica para cor parcial no navbar
        menu:
          - text: "Introdução"
            href: nivel/basico/R/index_OIER.qmd
          - text: "Matemática"
            href: nivel/basico/R/matematica.qmd
          #   target: "_blank"
          - text: "Física"
            href: nivel/basico/R/fisica.qmd
          #   target: "_blank"
          - text: "Química"
            href: nivel/basico/R/quimica.qmd
          #   target: "_blank"
          - text: "Biologia"
            href: nivel/basico/R/biologia.qmd
          #   target: "_blank"
          - text: "Humanas"
            href: nivel/basico/R/humanas.qmd
          - text: "História"
            href: nivel/basico/R/historia.qmd
          - text: "Geografia"
            href: nivel/basico/R/geografia.qmd
          #   target: "_blank"
          - text: "Linguagens"
            href: nivel/basico/R/linguagens.qmd
          #   target: "_blank"
          
      - text: "JSPlotly no Ensino Básico"
        id: bas-menu
        menu:
          - text: "Introdução"
      #     
      # - text: "ScriptRplot"
      #   menu:
      #     - text: "Introdução"
      #     
          
      # - text: "JSPlotly"
      #   menu:
      #     - text: "Introdução"
            
# 
      - text: "Publicações"
        href: producao.qmd
          
      - text: "Contato"
        href: contato.qmd
        


    right:
      - text: "EN"
        href: ../en/index.html
        
format:
  html:
    theme: 
      light: flatly
#      dark: darkly
    css: styles.css
    #toc: false
    code-overflow: wrap

execute:
  cache: true
  message: false
  warning: false
