
project:
  type: website
  output-dir: ../_site/en

website:
  page-navigation: true # não funciona
  back-to-top-navigation: true
  image: unifal-logo.png # não funciona
  reader-mode: true # funciona
  google-analytics: "G-S1L73VGCG5"
  title: "" # omite-se o título pra não duplicar nome na aba
  favicon: avatar.png # ícone da aba da página
  
  sidebar:
    contents:
      - section: "**bioQuanti**"
        contents:
          - text: "The website"
            href: index.qmd
          - text: "ERЯƎ - Reproducible Teaching"
            href: erre_en.qmd
          # - text: "Bioquímica de gente, de bicho, e de planta"
          #   href: nivel/superior/biqTxT/index_en_txt.qmd

      - section: "**Tutorials for High School**"
        contents:
          - text: "Molecules & Jmol"
            href: nivel/basico/Curso/jmol_curso_en.qmd
          - text: "Interactive Graphs and Maps with R"
            href: nivel/basico/Curso/r_curso_en.qmd
          - text: "Interactivity with Plotly graphs"
            href: nivel/basico/Curso/jsplt_curso_en.qmd
            
  navbar:
    search: true
    logo: logo-bioquanti.png # logo ao lado esquerdo da Home
 
 
    left:
      - text: "Structure and Jmol"
        id: sup-menu  # identifica para cor parcial no navbar
        menu: 
          - text: "Introduction"
            href: nivel/superior/jmol/index_jmol_en.qmd
          - text: "Jmol Features"
            href: nivel/superior/jmol/carac_en.qmd
          - text: "Commands"
            href: nivel/superior/jmol/comandos_en.qmd
          - text: "Water"
            href: nivel/superior/jmol/agua_en.qmd
          - text: "Amino Acids"
            href: nivel/superior/jmol/aminoacidos_en.qmd
          - text: "Proteins"
            href: nivel/superior/jmol/proteina_en.qmd
          - text: "Enzymes"
            href: nivel/superior/jmol/enzima_en.qmd
          - text: "Carbohydrates"
            href: nivel/superior/jmol/carboidrato_en.qmd
          - text: "Lipids"
            href: nivel/superior/jmol/lipidio_en.qmd 
          - text: "Nucleic Acids"
            href: nivel/superior/jmol/acnucleico_en.qmd
        
            
      - text: "Function & R"
        id: sup-menu   # identifica para cor parcial no navbar
        menu: 
          - text: "I. INTRODUCTION"
      #      href: ...
          - text: "R & RStudio"
            href: nivel/superior/r/index_r_en.qmd
          - text: "1. Biomolecules"
            href: nivel/superior/r/biomoleculas_en.qmd
          - text: "2. Buffer Systems"
            href: nivel/superior/r/tampoes_en.qmd
          - text: "II. STRUCTURE AND FUNCTION"
       #     href: ...
          - text: "3. Amino Acids"
            href: nivel/superior/r/aminoacid_en.qmd
          - text: "4. Proteins"
            href: nivel/superior/r/proteinas_en.qmd
          - text: "5. Enzymes"
            href: nivel/superior/r/enzimas_en.qmd
          - text: "6. Enzyme Inhibition"
            href: nivel/superior/r/enzInib_en.qmd
          - text: "7. Molecular Binding"
            href: nivel/superior/r/binding_en.qmd
          - text: "8. Nucleic Acids"
            href: nivel/superior/r/acnucleic_en.qmd
          - text: "9. Biomembranes"
            href: nivel/superior/r/membranas_en.qmd
          - text: "III. METABOLISM"
     #       href: ...
          - text: "10. Biothermodynamics"
            href: nivel/superior/r/biotermodin_en.qmd
          - text: "11. Metabolismo"
            href: nivel/superior/r/metabolismo_en.qmd 
          - text: "12. Metabolic Networks"
            href: nivel/superior/r/redes_en.qmd
          - text: "IV. OTHER TOPICS"
     #       href: ...
          - text: "13. Experimental Design"
            href: nivel/superior/r/planejExper_en.qmd
          - text: "Referências"
            href: nivel/superior/r/referencias_en.qmd   
            
      - text: "Dynamics & Sisma"
        id: sup-menu   # identifica para cor parcial no navbar
        menu: 
          - text: "Sisma"
            href: nivel/superior/sisma/index_sisma_en.qmd
          - text: "Examples"
            href: nivel/superior/sisma/sisma_ex_en.qmd
            
      - text: "Visualization & JSPlotly"
        id: sup-menu
        menu:
          - text: "Introduction"
            
      - text: "Jmol in High School"
        id: bas-menu
        menu:
          - text: "Introduction"
            href: nivel/basico/Jardim/index_Jardim_en.qmd
          - text: "Organic"
            href: nivel/basico/Jardim/organica_en.qmd
          - text: "Inorganic"
            href: nivel/basico/Jardim/inorganica_en.qmd
          - text: "Biomolecules"
            href: nivel/basico/Jardim/biomol_en.qmd
          - text: "Pharmacological"
            href: nivel/basico/Jardim/farmac_en.qmd
          - text: "Medicinal"
            href: nivel/basico/Jardim/medicin_en.qmd
          - text: "Toxicological"
            href: nivel/basico/Jardim/toxicol_en.qmd
          - text: "Nutritional"
            href: nivel/basico/Jardim/nutri_en.qmd
          - text: Flavors"
            href: nivel/basico/Jardim/sabores_en.qmd
          - text: "Environmental"
            href: nivel/basico/Jardim/ambiental_en.qmd
          - text: "Venoms"
            href: nivel/basico/Jardim/peconhentos_en.qmd
          - text: "Aromas"
            href: nivel/basico/Jardim/aromas_en.qmd
          - text: "Industrial"
            href: nivel/basico/Jardim/industrial_en.qmd
          - text: "Toxic Plants"
            href: nivel/basico/Jardim/plantasToxicas_en.qmd
          - text:  "Supramolecular"
            href: nivel/basico/Jardim/supramol_en.qmd

      - text: "R in High School"
        id: bas-menu  # identifica para cor parcial no navbar
        menu:
          - text: "Introduction"
            href: nivel/basico/R/index_OIER_en.qmd
          - text: "Mathematics"
            href: nivel/basico/R/matematica_en.qmd
          #   target: "_blank"
          - text: "Physics"
            href: nivel/basico/R/fisica_en.qmd
          #   target: "_blank"
          - text: "Chemistry"
            href: nivel/basico/R/quimica_en.qmd
          #   target: "_blank"
          - text: "Biology"
            href: nivel/basico/R/biologia_en.qmd
          #   target: "_blank"
          - text: "Humanities"
            href: nivel/basico/R/humanas_en.qmd
          - text: "History"
            href: nivel/basico/R/historia_en.qmd
          - text: "Geography"
            href: nivel/basico/R/geografia_en.qmd
          #   target: "_blank"
          - text: "Languages"
            href: nivel/basico/R/linguagens_en.qmd
          #   target: "_blank"
      #     
      # - text: "ScriptRplot"
      #   menu:
      #     - text: "Introdução"
      #     
          
      # - text: "JSPlotly"
      #   menu:
      #     - text: "Introdução"
            

      - text: "Publications"
        href: producao_en.qmd
          
      - text: "Contact"
        href: contato_en.qmd

    right:
      - text: "PT"
        href: ../pt/index.html

format:
  html:
    theme: 
      light: flatly
#      dark: darkly
    css: styles.css
    #toc: false
    code-overflow: wrap
    
execute:
  cache: true
  message: false
  warning: false

