{
  "hash": "0574d81def7afceb741d7544ba710d69",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Experimental design\"\n---\n\n## Matrix system\n\n| Recalling a simple *matrix system*, as seen in the *Biothermodynamics* chapter:\n\n$$\na_{11}*x_1 + a_{12} * x_2 = b_1\n\\\\\na_{21}*x_1 + a_{22} * x_2 = b_2\n$$ {#eq-eqMatrix}\n\n| That is,\n\n$$\nA = \\begin{bmatrix}\na_{11} & a_{12}\\\\\na_{21} & a_{22}\n\\end{bmatrix} ,\n$$\n\n$$\nx = \\begin{bmatrix}\nb_1\\\\\nb_2\n\\end{bmatrix} ,\n$$\n\n$$\nb = \\begin{bmatrix}\nx_1\\\\\nx_2\n\\end{bmatrix}\n$$\n\n| Now solve for the values ​​of *x* (or $\\Delta$'s) linearly:\n\n$$\nA * x = b\n$$ {#eq-eqAxb}\n\n| Using *matrix algebra*, the @eq-eqAxb is solved for the values ​​of *x*:\n\n$$\nx = A^{-1} * b\n$$ {#eq-eqAm1xb}\n\n| Thus, the matrix solution, widely used in multivariate situations, such as *response surface methodology* and *factorial experiment*, can be obtained by the following @eq-linMatr:\n\n$$\n\\beta = (X^T \\; X)^{-1} \\; X^T*y\n$$ {#eq-linMatr}\n\n| Other examples are illustrated in @eq-eqsLineares:\n\n$$\ny = b_0+b_1*x, \\, linear\\ fit\n\\\\\ny = b_0+b_1*x_1+b_2*x_2+...+b_n*x_n, \\, multilinear\\ fit\n\\\\\ny = b_0+b_1*x_1+b_2*x_2+...+b_n*x_n, \\, linear\\ response\\ surface\\ methodology\n\\\\\ny = b_0+b_1*x_1+b_2*x_2+b_{12}*x_1*x_2, \\, factorial\\ design\\, 2^2\n\\\\\ny = b_0+b_1*x_1+b_2*x_2+b_3*x_3+b_{12}*x_1*x_2+,b_{13}*x_1*x_3+b_{23}*x_2*x_3+b_{123}*x_1*x_2*x3 \\, experiment \\, factorial \\, 2^3\n\\\\\ny = b_0+b_1*x_1+b_2*x_2+b_{11}*x_1^2+b_{22}*x_2^2+b_{12}*x_1*x_2, \\, quadratic \\, response \\, surface \\, methodology\n\\\\\n$$ {#eq-eqsLineares}\n\n| As a rule, all applications listed in @eq-eqsLineares can be solved with the help of matrix relations of the equations @eq-linMatr (linear, multilinear and linear response surface adjustments) or @eq-eqAxb (factorial designs). Two situations of this nature are exemplified below.\n## Reaction Yield & Factorial Design 2$^{2}$\n\n| The simplest *factorial experiment* is the one that evaluates the *response* of an experiment (yield, for example) in which two *factors* (temperature and type of catalyst, for example) are varied at two *levels* each (low and high). The table prepared in the excerpt below from the data provided by Neto et al [@neto2010fazer] exemplifies this situation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Factorial design\n\n# Experiment data\ntemp <- c(40, 60, 40, 60)\ncatalis <- c(\"A\", \"A\", \"B\", \"B\")\nrendim <- c(59, 90, 54, 68)\n\n# Factorial design table\n\ntab.fat <- data.frame(temp, catalis, rendim)\nknitr::kable(tab.fat, caption = \"Factorial experiment data (Neto et al., 2010).\", \"pipe\") # table\n```\n\n::: {.cell-output-display}\n\n\nTable: Factorial experiment data (Neto et al., 2010).\n\n| temp|catalis | rendim|\n|----:|:-------|------:|\n|   40|A       |     59|\n|   60|A       |     90|\n|   40|B       |     54|\n|   60|B       |     68|\n\n\n:::\n:::\n\n\n| To conduct matrix analysis of the data, it is necessary to convert the table of independent variables (predictors) into a *coded design matrix*, in which high values ​​(*upper level*) are represented by *+1* and low values ​​(*lower level*) by *-1*. In addition, it is also necessary to assign *+1* to the 1st. column, and produce a 4th column containing the product of the encoded predictors. For example, for temperature at 40 (-1) and catalyst B (+1), the row will contain the product -1. This final 4x4 matrix is ​​called the *contrast coefficient matrix*:\n\n$$\nX = \\begin{bmatrix}\n1 & -1 & -1 & 1 \\\\\n-1 & -1 & 1 & 1 \\\\\n-1 & 1 & -1 & 1 \\\\\n1 & 1 & 1 & 1 \\\\\n\\end{bmatrix}\n$$\n\n| In addition, it is necessary to divide the result of the matrix operation by a specific scalar vector. In short: the coded matrix X of the predictors is created, the matrix Y of the response is applied to @eq-eqAxb, and the result is divided by a characteristic vector of the factorial design 2$^{2}$ (*c(4,2,2,2)*). The code snippet below solves the problem raised:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creation of the coded planning matrix\nX <- matrix(c(1, -1, -1, 1, 1, 1, -1, -1, 1, -1, 1, -1, 1, 1, 1),\nnrow = 4, byrow = TRUE)\n# Creation of the yield matrix\nY <- as.matrix(rendim)\n# Determination of the beta coefficients:\nbeta <- t(X) %*% Y / c(4, 2, 2, 2)\nbeta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       [,1]\n[1,]  67.75\n[2,]  22.50\n[3,] -13.50\n[4,]  -8.50\n```\n\n\n:::\n:::\n\n\n| Thus, the result is interpreted as:\n\n$$\n\\begin{pmatrix}\nM \\\\\nT \\\\\nC \\\\\nTC \\\\\n\\end{pmatrix} =\n\\begin{pmatrix}\n67.75 \\\\\n22.50 \\\\\n-13.50 \\\\\n-8.50 \\\\\n\\end{pmatrix}\n$$ {#eq-factor22}\n\nWhere *M* represents the *overall mean* of the response, *T* and *C* the *main effects* (temperature and catalyst), and *TC* the *interaction effect*. In summary, the results suggest that 1) the temperature favored the yield, especially for catalyst A, 2) there is a reduction in yield when replacing catalyst A with B, and c) the highest yields are obtained with catalyst A at the highest temperature. Expressing these results in the multiple linear function:\n\n$$\ny=67.75+22.5*T-13.5*C-8.5*T*C\n$$ {#eq-eqFator}\n\n| Interestingly, we arrive at the same results if, instead of applying @eq-eqAxb, we use @eq-linMatr, followed by multiplication (and not division) by another vector (*c(1,2,2,2)*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeta <- (solve(t(X) %*% X) %*% t(X) %*% Y) * c(1, 2, 2, 2)\nbeta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       [,1]\n[1,]  67.75\n[2,]  22.50\n[3,] -13.50\n[4,]  -8.50\n```\n\n\n:::\n:::\n\n\n## Response Surface Methodology (RSM)\n\n| This multivariate statistical technique is also commonly used in modeling responses influenced by more than one factor, sometimes associated with factorial design, and with a view to optimizing a response without the need to evaluate all possible combinations. This can be particularly useful when one wants to optimize a test whose response depends, for example, on scalar predictors, such as the concentration range of a given reagent and the pH conditions.\n| For example, for a *linear response surface* [@neto2010fazer], in a test in which one wishes to verify the best yield (*rend, %*) of a reaction by varying 3 levels of reagent concentration (*conc, %*) and three magnetic stirring speeds (*agit, rpm*), one can, as before, prepare the *contrast matrix* from the information in the following table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data for response surface methodology\n\nconc <- c(45, 55, 45, 55, 50, 50, 50)\nagit <- c(90, 90, 110, 110, 100, 100, 100)\nx1 <- c(-1, 1, -1, 1, 0, 0, 0)\nx2 <- c(-1, -1, 1, 1, 0, 0, 0)\nyield <- c(69, 59, 78, 67, 68, 66, 69)\n\ntab.msr <- data.frame(conc, agit, x1, x2, yield)\nknitr::kable(tab.msr, caption = \"Experiment data of linear response surface methodology\n(Neto et al, 2010).\", \"pipe\") # table\n```\n\n::: {.cell-output-display}\n\n\nTable: Experiment data of linear response surface methodology\n(Neto et al, 2010).\n\n| conc| agit| x1| x2| yield|\n|----:|----:|--:|--:|-----:|\n|   45|   90| -1| -1|    69|\n|   55|   90|  1| -1|    59|\n|   45|  110| -1|  1|    78|\n|   55|  110|  1|  1|    67|\n|   50|  100|  0|  0|    68|\n|   50|  100|  0|  0|    66|\n|   50|  100|  0|  0|    69|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Criação da matriz de coeficientes de contraste\nX <- matrix(c(1, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, 0, 0, 0, -1, -1, 1, \n              1, 0, 0, 0), nrow = 7, byrow = FALSE)\n\n# Criação da matriz de rendimento\nY <- as.matrix(rendim)\n\n# Determinação dos coeficientes beta:\nbeta <- solve(t(X) %*% X) %*% t(X) %*% Y\nbeta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      [,1]\n[1,] 68.00\n[2,] -5.25\n[3,]  4.25\n```\n\n\n:::\n:::\n\n\n| Thus, the linear function that expresses the response surface will be:\n\n$$\ny=68.00-5.25*conc+4.25*agit\n$$ {#eq-eqMsr}\n\n### Quadratic Response Surface\n\n| Sometimes the linear model may not fit the experimental design, which can be verified by an *Analysis of Variance (ANAVA)* of the experiment. In these cases, a *quadratic surface methodology* can be applied, which can be expressed as seen in @eq-eqsLineares. In these cases, a construction called *star planning* is common, which adds an identical one rotated by 45$^{o}$ to the initial planning, and whose new points are $\\sqrt{2}$ coded units away from the central point. The example below aims to illustrate this methodology.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dados para superfície quadrática de resposta\n\nconc <- c(30, 40, 30, 40, 35, 35, 35, 28, 35, 42, 35)\nagit <- c(115, 115, 135, 135, 125, 125, 125, 125, 139, 125, 119)\nx1 <- c(-1, 1, -1, 1, 0, 0, 0, -sqrt(2), 0, sqrt(2), 0)\nx2 <- c(-1, -1, 1, 1, 0, 0, 0, 0, sqrt(2), 0, -sqrt(2))\nrendim <- c(86, 85, 78, 84, 90, 88, 89, 81, 80, 86, 87)\n\ntab.msr2 <- data.frame(conc, agit, x1, x2, rendim)\nknitr::kable(tab.msr2, caption = \"Dados de experimento de metodologia de \n             superfície quadrática de resposta (Neto e cols, 2010).\", \"pipe\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Dados de experimento de metodologia de \n             superfície quadrática de resposta (Neto e cols, 2010).\n\n| conc| agit|        x1|        x2| rendim|\n|----:|----:|---------:|---------:|------:|\n|   30|  115| -1.000000| -1.000000|     86|\n|   40|  115|  1.000000| -1.000000|     85|\n|   30|  135| -1.000000|  1.000000|     78|\n|   40|  135|  1.000000|  1.000000|     84|\n|   35|  125|  0.000000|  0.000000|     90|\n|   35|  125|  0.000000|  0.000000|     88|\n|   35|  125|  0.000000|  0.000000|     89|\n|   28|  125| -1.414214|  0.000000|     81|\n|   35|  139|  0.000000|  1.414214|     80|\n|   42|  125|  1.414214|  0.000000|     86|\n|   35|  119|  0.000000| -1.414214|     87|\n\n\n:::\n\n```{.r .cell-code}\n# tabela\n```\n:::\n\n\n| This time the *contrast coefficient matrix* expands to six columns as a function of the terms *x$_{1}^{2}$*, *x$_{2}^{2}$*, and *x$_{1}$x$_{2}$*, becoming:\n\n$$\n\\begin{pmatrix}\n1 & -1 & -1 & 1 & 1 & 1 \\\\\n1 & 1 & -1 & 1 & 1 & -1 \\\\\n1 & -1 & 1 & 1 & 1 & -1 \\\\\n1 & 1 & 1 & 1 & 1 \\\\\n1 & 0 & 0 & 0 & 0 & 0 \\\\\n1 & 0 & 0 & 0 & 0 & 0 \\\\\n1 & -\\sqrt(2) & 0 & 2 & 0 & 0 \\\\\n 1 & 0 & \\sqrt(2) & 0 & 2 & 0 \\\\\n 1 & \\sqrt(2) & 0 & 2 & 0 & 0 \\\\\n 1 & 0 & -\\sqrt(2) & 0 & 2 & 0 \\\\\n\\end{pmatrix}\n$${#eq-msr2)\n\n\n| The procedure for the quadratic surface repeats the matrix operation performed with the linear one:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating the matrix of contrast coefficients for the quadratic surface\nX <- matrix(c(rep(1, 11), -1, 1, -1, 1, 0, 0, 0, -sqrt(2),\n0, sqrt(2), 0, -1, -1, 1, 1, 0, 0, 0, 0, sqrt(2),\n0, -sqrt(2), 1, 1, 1, 0, 0, 0, 2, 0, 2, 0, 1, 1,\n1, 1, 0, 0, 0, 0, 2, 0, 1, 1,\n1, 1, 0, 0, 0, 0, 2, 0, 2, 1, -1, -1, 1, 0, 0, 0, 0,\n0, 0, 0), nrow = 11, byrow = FALSE)\n\n# Creating the yield matrix\nY <- as.matrix(rendim)\n# Determining the beta coefficients:\nbeta <- solve(t(X) %*% X) %*% t(X) %*% Y\nbeta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]\n[1,] 89.505503\n[2,] -1.936109\n[3,] -4.129153\n[4,] -3.253803\n[5,] -5.832328\n[6,]  1.992845\n[7,]  2.169559\n```\n\n\n:::\n:::\n\n\n| The result expresses the quadratic function of the surface found, as follows:\n\n$$\ny=89.00+1.51*x_1-2.36*x_2-2.81*x_1^2-2.81*x_2^2+1.75*x_1*x_2\n$$ {#eq-eqMsr2}\n\n| From the result above it is possible to predict the optimized conditions for the test. In this sense, `R` allows, for example, the construction of a three-dimensional graph that represents the function obtained, and without the need for an additional package: as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Quadratic response surface (MSR)\n\nx <- seq(-1, 1, 0.1) # predictor x\ny <- seq(-1, 1, 0.1) # predictor y\nmrs <- function(x, y) {\n89.00 + 1.51 * x - 2.36 * y - 2.81 * x^2 - 2.81 * y^2 + 1.75 * x * y\n} # function applied to predictors\nz <- outer(x, y, mrs) # 3D plot output (response)\nres <- persp(x, y, z, xlab = \"x1\", ylab = \"x2\", zlab = \"z\",\nshade = 0.4, theta = 30, phi = 15, ticktype = \"detailed\")\n# surface plot of function z(x,y)\npoints <- trans3d(x1, x2, rendim, pmat = res) # command for adding experimental points\npoints(points, pch = 19, col = 1) # adding points\n```\n\n::: {.cell-output-display}\n![Quadratic surface described by the MSR equation with superposition of experimental values.](planejExper_en_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n| However, there are some packages for `R` for three-dimensional representation of data and functions (`rgl`, `plot3D`, `scatterplot3d`), as well as for factorial design analysis (`agricolae`, `afex`, `FMC`), and response surface methodology (`rsm`). ",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}