---
title: "Bioquímica de Couro e de Peles"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       A pele é uma estrutura de barreira e proteção térmica, sendo constituída por uma grande massa vascularizada epitelial, e um teor significativo de gorduras, especialmente as saturadas. As gorduras acumuladas no couro permitem proteção mecânica e térmica para o animal. A pele é anatomicamente dividida em epiderme e córion, esse último característico dos curtumos produzidos. Possui baixa atividade metabólica e um teor menos pronunciado de proteínas e enzimas que outros sistemas tissulares animais.


## Detalhes

|       Carnaz é nome dado ao lado interno da pele e couros, contendo restos de tecido adiposo, muscular e sangue. É composto pela epiderme e pelo córion. A epiderme é formada por pelos, glândulas, fibras de colágeno, tecido elástico, vasos sanguíneos e nervos. O córion ou derme é composto por fibras de colágeno, fibroblastos, vasos sanguíneos e tecido nervoso sem fibras elásticas. O córion também é conhecido por definir a característica dos curtumes obtidos. 


|       A pele é composta por proteínas e enzimas (43 %), lipídios (2 %), glicídios, vitaminas e sais. Os lipídios do sebo são formados pelas glândulas sebáceas da pele, e armazenados em células adiposas, não sendo transportados pelo sangue para a composição do couro. A composição lipídica da pele é determinada por cera (35 %), fosfolipídios (20 %), e ácidos graxos (10 %). 


|       A composição de carboidratos da pele é dada por glicogênio, para a síntese de ceratinas, glicosaminas, galactosaminas, glicoproteínas, e mucopolissacarídios. Diferentemente dos lipídios, os glícides são transportados do sangue para a pele. As fontes minerais das peles envolvem o ferro da hemoglobina, o fósforo dos fosfolipídios, o cobre dos pigmentos , e o arsênico excretado da pele.

|       O metabolismo da pele é pouco significativo, frente a um baixo teor de conteúdo enzimáticos. De um modo geral, as fibras de colágeno encontram-se entremeadas com fibras elásticas, o conjunto todo embebido em mucopolissacarídios e proteínas.

