---
title: "Metabolismo & Dietas"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|   Uma simples observação do mapa metabólico nos infere sobre sua
plasticidade, adaptação e riscos, no que tange aos vários tipos de dietas
consumidas com objetivos para nutrir o corpo, facilitar a digestão e absorção
dos nutrientes, fazer a manutenção da saúde ou melhorar o desempenho
físico e mental ou mesmo, para tratar de doenças metabólicas. Este texto
poderá lhe informar que quase tudo o que pensamos sobre dietas "saudáveis"
está errado. 

|   Superalimentos, suplementos e dietas à base de plantas como
grãos integrais e leguminosas, são estratégias que não apenas falham com
frequência, mas algumas podem até mesmo trabalhar contra nós. A verdade
sobre a comida para nutrir e prosperar a saúde é que as dietas veganas não
são mais saudáveis, a carne vermelha não é perigosa, os suplementos são
necessários a depender da individualidade e contexto e os antioxidantes não
são a resposta. Segundo o [Guia Alimentar Para a População Brasileira](https://bvsms.saude.gov.br/bvs/publicacoes/guia_alimentar_populacao_brasileira_2ed.pdf) disponibilizado pelo Ministério da Saúde, a
alimentação adequada e saudável é a prática alimentar apropriada aos
aspectos biológicos e socioculturais dos indivíduos, bem como ao uso
sustentável do meio ambiente:

- Deve estar em acordo com as necessidades de cada fase da vida e com
as necessidades alimentares especiais;
- Referenciada pela cultura alimentar;
- Acessível do ponto de vista físico e financeiro;
-  Harmônica em quantidade e qualidade;
- Baseada em práticas produtivas adequadas e sustentáveis;
- Quantidades mínimas de contaminantes físicos, químicos e biológicos.

|   Assim, as recomendações feitas para a população em geral devem levar em
conta o cenário da evolução da alimentação e das condições de saúde da
população.


|   Nesse cenário alimentar caótico em que vivemos, com alto consumo de
produtos alimentícios ricos em açúcares, frutose, xaropes, farinhas brancas,
gorduras vegetais, produtos químicos, edulcorantes, estabilizantes,
aromatizantes, corantes etc., buscar alimentos de verdade e minimamente
processados já trará luz aos processos fisiológicos, permitindo suas funções
mais eficientes e prevenindo doenças metabólicas que são hoje a maior
causa de morbidade e mortalidade no mundo: inflamação, diabetes, doenças
cardiovasculares,câncer, Alzheimer, entre outras.

|   Vamos explorar brevemente as principais dietas e entender seu papel no
metabolismo humano.


## Dieta vegetariana

|   Segundo a [Sociedade Vegetariana Brasileira](https://svb.org.br/), "é considerado vegetariano todo aquele que exclui de sua alimentação todos os tipos de carne, aves e peixes e seus derivados, podendo ou não utilizar laticínios ou ovos. O vegetarianismo inclui o veganismo, que é a prática de não utilizar produtos oriundos do reino animal para nenhum fim (alimentar, higiênico, de vestuário etc.).

|   O indivíduo que segue uma dieta vegetariana pode ser classificado de acordo com o consumo de subprodutos animais (ovos e laticínios):

-Ovolactovegetariano é o vegetariano que utiliza ovos, leite e laticínios na
alimentação.
- Lactovegetariano é o vegetariano que não utiliza ovos, mas faz uso de leite
e laticínios.
- Ovovegetariano é o vegetariano que não utiliza laticínios mas consome
ovos.
- Vegetariano estrito é o vegetariano que não utiliza nenhum derivado animal
na sua alimentação.
- Vegano é o indivíduo vegetariano estrito que recusa o uso de componentes
animais não alimentícios, como vestimentas de couro, lã e seda, assim como
produtos que foram testados em animais.

|   O grande problema é o de se obter calorias e proteínas suficientes para
preencher a ingestão diária recomendada (DRI) . Isso se dá pelo baixo teor
proteico de produtos vegetais, pelo baixo valor biológico de proteínas
vegetais, e pela má digestibilidade de algumas proteínas vegetais. A dieta
vegetariana estrita é potencialmente arriscada em condições em que não se é
possível a redução da DRI, como no lactente, na gestação, e na lactação, o que pode resultar em desnutrição proteico-calórica.


|   A dieta vegetariana deve ser complementada com leite e ovos (dieta
lacto-ovo), incluir fontes calóricas altas de vegetais (nozes, grãos, frutas
secas), e permitir combinações proteicas que elevem o valor biológico das
proteínas ingeridas. As dietas veganas/vegetarianas, não fornecem ou não adequadamente fontes nutricionais de vitamina B12, ferro, zinco, ômega-3, cálcio, devendo ser obtidos de alimentos industrializados que são enriquecidos com esses
nutrientes ou deve-se suplementá-los.


|   Há um problema significativo quanto a biodisponibilidade dos nutrientes a
partir de alimentos vegetais pois são ricos em antinutrientes que interferem
tanto na fisiologia digestiva por meio da redução da atividade enzimática
quanto na capacidade de absorção de nutrientes essenciais.Por isso,
recomendam-se associar alimentos ricos em vitamina C, ácidos orgânicos
para melhorar a absorção do ferro e do zinco, por exemplo.


|   Para além da preocupação com os antinutrientes, deve-se ocupar do extenso
processamento necessário para tornar aquele alimento possível de ser
digerido e absorvido pelo organismo humano. E, ainda, deve-se manter um
microbioma intestinal equilibrado a fim de evitar fermentação intestinal
elevada.


|   As dietas ricas em carboidratos pontuam a existência de polissacarídeos e de
fibras. Neste caso, as fibras, não possuem papel central no metabolismo,
uma vez que são fermentadas na porção final do intestino contribuindo
vagamente com aporte de ácidos graxos de cadeia curta e favorecendo a
formação do bolo fecal. São utilizadas para trazer saciedade, plenitude
gástrica, quando há o objetivo de emagrecimento. Entretanto, essa dieta é
perigosa e pode levar à resistência insulínica uma vez que gerará muitos
picos de glicose ao longo do dia. Carboidratos complexos podem fornecer
calorias, além de sua hidrólise parcial resultar na liberação de prebióticos,
substâncias que auxiliam o microbioma intestinal. 

|   O uso excessivo de carboidratos, entretanto, pode resultar em formação e acúmulo de ácidos graxos através da síntese de glicerol e de acetil CoA, a partir da
disponibilidade de derivados monossacarídeos, elevando os triglicérides e o colesterol no sangue e promovendo oxidações e inflamações vasculares. Não obstante, dietas ricas em carboidratos exigem maior consumo de água para sua digestibilidade e
absorção. Além dos riscos iminentes da ingesta insuficiente de água, a perda
aparente de peso corporal observada pode ser consequência do sequestro de
água exigido no metabolismo de fibras e carboidratos complexos. 

|   É importante observar que as dietas ricas em carboidratos podem levar a uma
redução da ingestão proteica e gerar perdas musculares e teciduais
dificultando a longevidade com saúde. Ainda, pela incapacidade de ingerir a
quantidade fisiológica de proteínas, pode iniciar um estímulo central para
ingestão alimentar, gerando quadros de compulsão e obesidade. A dieta rica
em carboidratos é empregada no trabalho atlético de esforços aeróbicos,
como corridas de longa distância, natação e futebol. 

|   Já é conhecido que uma dieta rica em carboidratos complexos aumenta a secreção insulínica, facilita a glicogênese hepática, aumenta os estoques de glicogênio e, por consequência, a resistência física do atleta. Entretanto, são estoques de
rápida absorção o que necessita de ingestões constantes, diferente dos
ácidos graxos como fonte de energia.

## Dieta cetogênica

|   Originalmente, é a “dieta” natural do ser humano. Historicamente desde o
Pleistoceno, ocorrido há cerca de 2,5 milhões a 11.700 anos atrás, onde
havia uma abundância de animais e escassez de fontes vegetais como
iniciou-se no período agrícola, permitindo que os seres humanos vivessem a
partir da caça. Nesse período, as vísceras, tutano, carnes com gorduras e,
por último, carnes magras, eram a base da alimentação. 

|   Esporadicamente, com sorte, como uma surpresa a ser comemorada, os humanos conseguiam alguma fruta ou um pouco de mel. Assim, viviam em constante estado de
cetose, onde o corpo degrada por meio da beta oxidação a gordura armazenada como fonte de energia. Não havia regras de horários para
alimentar-se e sim períodos intercalados de jejum e estado alimentado. Essa
capacidade de gerar corpos cetônicos a partir dos períodos, principalmente,
de jejum e também do estado alimentado rico em gorduras é capaz de manter
o cérebro mais focado, ágil e inteligente para eventuais necessidades.
Como evidência fisiológica de nossa capacidade alimentar original, podemos
constatar o pH estomacal, o qual é de cerca de 1,5 a 2,5. Ou seja, ácido
suficiente para melhor digestão de proteínas, sugerindo que a alimentação de
origem animal seja a mais adequada para seres humanos.


|   A dieta cetogênica foi estudada e validada para o tratamento de epilepsia no
início dos anos 1920, por reduzir a excitabilidade neuronal a partir da
formação dos corpos cetônicos especialmente o beta hidroxibutirato,
resultando em melhor controle das crises.
Por ser uma alimentação de baixíssimo carboidrato, pacientes diabéticos e
que apresentam resistência insulínica e síndrome metabólica se beneficiam
grandemente com remissão da doença ou seu controle. As dietas ricas em
gordura possuem a vantagem de gerar alta saciedade, consumindo menor
volume de alimentos quando comparado a outras dietas, uma vez que o
aporte calórico de ácidos graxos é duas vezes maior que o de proteínas e
carboidratos.


|   Nosso corpo pode ser comparado a um equivalente fisiológico de um
automóvel híbrido, o qual utiliza mais de uma fonte de combustível: energia
de carboidratos e energia dos estoques de gordura.
Neste sentido, compreende-se que a ingestão de carboidratos não é
essencial, embora esse fato seja ignorado, e nosso corpo pode se sustentar
até melhor à base de cetonas (beta hidroxibutirato, acetona e acetoacetato).
A quantidade de glicose necessária para suprir alguns tecidos corporais como
o cristalino do olho e os glóbulos vermelhos do sangue pode ser produzida
pelo fígado a partir de aminoácidos glicogênicos que a partir do piruvato,
fumarato, alfa cetoglutarato, succinil CoA e oxaloacetato no ciclo de krebs
irão formar glicose para suprir as demandas fisiológicas do organismo.


|   As consequências ao repúdio às gorduras saturadas foram o aumento da
utilização de óleos vegetais e o desenvolvimento de gorduras trans e
interesterificadas. Essas gorduras como óleos vegetais, margarinas e
gorduras hidrogenadas são altamente oxidativas e inflamatórias e favorecem
ao desenvolvimento de doenças cardiovasculares, síndrome metabólica e
câncer. Um adendo deve ser feito às gorduras oriundas do azeite de oliva, do
abacate, das nozes e castanhas e do coco.
As primeiras, inseridas no contexto da dieta mediterrânea, predominantes em
gorduras monoinsaturadas, têm impacto metabólico nos processos de
desinflamação, contribuindo com a saúde antioxidante e proteção
cardiovascular. O óleo de coco tem os ácidos graxos de cadeia média (TCM)
que são de rápida absorção e consumo energético, o que beneficia o aporte
de ácidos graxos para formação de corpos cetônicos mais rapidamente.
O óleo de coco é rico em ácido láurico, cerca de 47% dos ácidos graxos,
apresenta inúmeras ações terapêuticas. Em contato com pH ácido do
estômago, transforma-se em monolaurina, um poderoso antivirótico,
antibacteriano, antiparasitário e antifúngico, sem efeitos colaterais.


|   Ao se tratar de dietas ricas em gorduras, como a cetogênica, deve-se ter em
mente a utilização de gorduras de origem animal, especialmente animais
ruminantes que alimentam-se de pasto, como é predominante no Brasil. As
gorduras saturadas constituem a base da formação dos tecidos, como o leite
materno que é rico em gorduras saturadas essenciais para formação,
especialmente cerebral, dos bebês. A utilização de gorduras como
combustível energético garante melhor atividade mitocondrial onde menos
espécies reativas de oxigênio são formadas, reduzindo a inflamação crônica
de baixo grau que acompanha o indivíduo ao longo da vida.
Paralelamente as gorduras saturadas, a utilização de gorduras poli
insaturados (PUFAs), ácidos graxos essenciais, como DHA e EPA são
necessárias para proteção cerebral e cardiovascular, respectivamente o que
inclui alguns óleos de peixes, principalmente de água fria, que se alimentam
de algas, o que está muito distante dos peixes de cativeiro que sse alimentam
de ração. Neste sentido, consumir boas fontes de gordura de ruminantes ou
ingerir cápsulas de ômega 3 contendo quantidades significativas de DHA e
EPA garantem o suprimento dessas gorduras essenciais.

## Dieta de proteínas.

|   A dieta rica em proteínas tem respaldo bioquímico no fato de que apenas 2
aminoácidos,Lys e Leu, são estritamente cetogênicos. Sendo assim, uma
dieta proteica combinada, onde haja escassez destes aminoácidos, poderá
reduzir a lipogênese. Além disso, aminoácidos são convertidos a glicose,
reduzindo a necessidade de consumo daqueles para a manutenção dos
níveis glicêmicos. Alguns aminoácidos como Gln e Ala são essenciais no ciclo
de reaproveitamento do lactato sanguíneo (ciclo de Cori), vindo da
fermentação eritrocitária ou muscular. 

|   Glutamina, em especial, possui papel
preponderante, já que representa 50% dos aminoácidos circulantes,
transporta amônia tóxica, e auxilia no balanço ácido-básico, além de nutri os
enterócitos e favorecer o tratamento de doenças intestinais e autoimunes. A
dieta proteica, entretanto, encontra barreiras no uso por indivíduos com algum
tipo de disfunção renal, já que o controle da produção de ureia e eliminação
da amônia envolve o metabolismo nitrogenado. Insuficiência renal crônica,
por exemplo, caracteriza-se pelo acúmulo de produtos finais do catabolismo
de proteínas, principalmente ureia. Algum grau de restrição proteica na dieta
é geralmente necessário porque esses produtos finais tóxicos são
responsáveis por muitos dos sintomas associados à doença.


|   Progressos recentes em nutrição levam em conta a possibilidade de oferecer
bem-estar alimentar à população, evitando contudo o desenvolvimento da
obesidade. Neste sentido, as recomendações traduzem-se em uma dieta low
carb, ou seja, reduzida em carboidratos (10 a 30%) ou cetogênica, baixíssima
em carboidratos (0 a 10%) baseada principalmente em proteínas suficiente
para suprir as necessidades de aminoácidos essenciais, uma vez que há a
regulação central para o consumo de proteínas, especialmente de origem
animal. Tal fato auxilia no controle de peso e em quadros de compulsão
alimentar. Juntamente à ingestão de proteínas, deve-se levar em conta a
utilização de gorduras saudáveis, como as citadas acima, para serem
utilizadas como fonte energética, entre 30 a 70% do consumo calórico total.
Para além da “dieta” , termo este muito recente na história da alimentação,
deve-se atentar para a fisiologia e os alimentos mais biodisponíveis e
utilizados ao longo da nossa evolução, os alimentos de origem animal.


