---
title: "Metabolismo do Músculo e do Exercício Físico – Os estados"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       Uma vez estabelecidos os arcabouços energéticos, as rotas metabólicas e as interações hormonais atuantes no esforço físico, passaremos a expor sua dinâmica nos diversos tipos de trabalho que executa.

## Detalhes

### Operação da vias durante o exercício. 

|       fibra muscular é uma estrutura eminentemente oxidativa (glicólise, $\beta$-oxidação, ciclo de Krebs, cetólise e cadeia respiratória). O centro gerador de energia para o trabalho é o ciclo de Krebs, cujo combustível é a acetil CoA. Sua desintegração leva a uma perda de energia representada por  8 elétrons, entregues ao oxigênio molecular durante a síntese de ATP. Neste sentido, o trabalho contrátil estabelece um equilíbrio dinâmico entre a acetil CoA energizada resultante do metabolismo, e o O2 que receberá os elétrons já relativamente desenergizados. O trabalho muscular pode ser anaeróbico ou aeróbico. O primeiro ocorre sob baixa demanda de O2, fazendo com que a fibra busque ATP fora da mitocôndria (absoluto). Pode também ser realizado com demanda significativa do oxigênio, mas com produção excessiva de acetil CoA, o que satura o ciclo de Krebs e a cadeia respiratória, desviando a rota também para fora da mitocôndria (relativo). Como produto final surge o lactato, 2 moles cada mol de glicose oxidada, e 2 ATPs. O rendimento energético é baixo, mas importante numa situação emergencial, juntamente com os estoques instáveis de fosfocreatina. 

|       Durante o trabalho físico, muito H+ é gerado, proveniente do ciclo de Krebs, da desidrogenação do piruvato, da hidrólise de ATP, do ciclo da uréia, da cetogênese, neoglicogênese e $\beta$-oxidação. Essa produção de H+ ocorre, portanto, tanto no metabolismo anabólico como no catabólico (são produzidos diariamente H+correspondente a 1 litro de HCl concentrado, e 40Kg de ATP). No trabalho contrátil anaeróbico (absoluto ou relativo), contudo, estes prótons são produzidos a partir da formação do piruvato, sendo esta a principal causa de redução do pH na fibra, e não a presença crescente de ácido lático, como se supunha. 

|       Além disso, pela equação de equilíbrio de Handerssen-Hasselbach (vide texto sobre tampões), a razão de lactato/ácido lático no pH fisiológico é de 5 mil pra 1, corroborando com a hipótese acima. Os H+produzidos no corpo são utilizados nos sistemas tampões do bicarbonato (pra se livrar do CO2 metabólico e respiratório), de proteínas (His) e fosfato (grande importância na fibra), e também na ativação metabólica do centro respiratório e de quimioreceptores carotídicos e aórticos (aumento da frequência cardíaca e respiratória).

###  Músculo em repouso. 

|       Ocorre por ocasião da pletora alimentar (fase pós-prandial e absortiva). Neste estado, a alta relação ATP/ADP (10-20/1) proporciona a fomação de estoques de fosfocreatina (20g, 9Kcal/mol, contra  7Kcal/mol do ATP). O ATP livre no organismo suporte apenas 10 contrações 2s), enquanto que a reserva de fosfocreatina utilizável por um velocista, 100 contrações (30s). É curioso o metabolismo do repouso concomitante ao estado de jejum. 

|       No repouso com jejum o músculo consome mais ácido graxo do que glicose, devido a um estado de hipoinsulinemia, aumento de ácidos graxos circulantes pela ação dos hormônios contra-regulatórios, baixo teor de GLUT-4 (baixa insulinemia), e facilidade do uso de FADH2 da $\beta$-oxidação em relação ao NADH da glicólise, já que para a formação do primeiro é necessário 1 ADP a menos que para o segundo. Na prática, o músculo em repouso obtém o ATP de que precisa 80% vindos da oxidação de ácidos graxos, e 20% da de corpos cetônicos, glicose e aminoácidos. 

|       Esses corpos cetônicos, cujo teor não é sujeito à ação humoral  ($\beta$-oxidação não possui enzimas regulatórias), mas apenas estequiométrica, ficam disponíveis em excesso para o cérebro. O repouso no estado absortivo muda de figura. O sistema gastrointestinal está repondo as reservas energéticas, com o tecido hepático e adiposo em intensa atividade. O excesso de acetil CoA satura o ciclo de Krebs, sendo desviado para lipogênese. 

|       A $\beta$-oxidação cai de ritmo, pois há inibição da carnitina acil-transferase por excesso de malonil CoA. O fígado torna-se mais eficiente em repor seu glicogênio do que fazer glicólise, devido ao baixo teor de frutose 2,6-diP. Quando a situação absortiva é acompanhada de estresse, entretanto, a predominância das catecolaminas mascara os efeitos dos demais hormônios, e o organismo experimenta o desconforto de uma absorção forçada às custas de um desequilíbrio hormonal.

### O músculo em trabalho. 

|       A fase inicial do esforço físico demanda uma situação anaeróbica mediada pela quebra de fosfocreatina (controle apenas estequiométrico, consumo em segundos) e pela glicólise, menos ativa no início, pois o ADP que ativaria a PFK-1 foi utilizado na construção da fosfocreatina. Em seguida, a relação ADP/ATP aumenta, induzindo a atividade da PFK-1 em até mil vezes, e dando início a um maciço trabalho glicolítico. De início, este trabalho mobiliza o piruvato sarcoplasmático, uma vez que o mitocondrial está sendo convertido em acetil CoA. NAD+ citósólico é obtido, pois a lançadeira do glicerol-fosfato tem FAD na mitocôndria para entregar-lhe os elétrons, o que não acontecia no repouso. Este mecanismo limita a utilização do FAD e garante um consumo maior de glicose pela fibra. Paralelamente vão surgindo as catecolaminas, e o metabolismo muscular passa a ser complementado pelos efeitos lipolíticos adrenérgicos. 

|       Aparecem o hGH e as somatomedinas, aumentando a glicólise e a captação de glicose musculares. Com os efeitos catecolamínicos de taquicardia, vasodilatação periférica, lipólise, e taquipnéia, o músculo ganha o que precisa para sua atividade, ou seja, muito oxigênio, glicose e ácidos graxos, e uma boa perfusão sanguínea. A manutenção da glicemia é mantida pela atividade contra-regulatória hormonal, sendo privilegiadas a glicogenólise, glicólise, lipólise, e gliconeogênese, com nehuma atenção à síntese de proteínas. 

|       As somatomedinas agem em sentido contrário, o que justifica o aumento da massa muscular em médio prazo de treinamento. Em situações especiais, a glicose pode ser suprida exogenamente, como na administração de dextrina para atletas, o que pode evitar uma situação de hipoglicemia. Na continuação do exercício físico, quando ficam ultrapassados o uso de fosfocreatina e glicogênio, aprofundam-se as modulações endócrinas, com ácidos graxos, corpos cetônicos e aminoácidos (essencialmente Val, Leu e Ile) sendo utilizados para o suprimento energético muscular. Aminoácidos ramificados também podem ser oferecidos no treinamento atlético. 

|       Como Ala, Phe, Tyr, Met e outros aminoácidos glicogênicos não são utilizados pelo músculo, o exercício intenso tende a aumentá-los a partir da degradação protéica. Ala pode chegar a mais de 90% de seu valor inicial. Esse aminoácidos livres podem agora ser utilizados pelo SNC. A detoxificação da amônia livre resultante pode ser feita pelo ciclo da uréia hepático, ciclo da Ala e ciclo da Gln (texto anterior sobre músculos). O corpo pode, então, entrar em falência quando o consumo da massa protéica atinge aproximadamente a metade da corporal. Neste sentido, são os ácidos graxos o verdadeiro combustível da continuação do esforço físico, já que corpos cetônicos, piruvato e alguns aminoácidos, embora melhor absorvíveis, encontram-se em teor reduzido, comparativamente. 

|       A recuperação após o esforço extenuado se dá com a diminuição da adrenalina, e H+ , principais fatores responsáveis pela redução das frequências cardíaca e respiratória. A glicólise diminui em razão da redução de ADP, o que determina o acúmulo de glicose-6-P para glicogenogênese hepática, restabelecendo os reservatórios. O tecido adiposo reduz a lipólise, e o fígado, a cetogênese e gliconeogênese. O resultado final é o retorno às condições de repouso. 

### Exaustão muscular. 

|       Quando o esforço físico se torna supramáximo, a produção de ATP não acompanho seu consumo, e o músculo entra em falência, pela depleção da fosfocreatina muscular, diminuição local do pH, depleção do glicogênio muscular, hipoglicemia e aumento no teor relativo de triptofano. O ATP produzido se torna insuficiente, a força contrátil diminui, a lançadeira do glicerol-fosfato reduz, e a glicólise aumenta os teores locais de lactato, piruvato e intermediários do ciclo de Krebs, aumentando a osmolaridade local e retendo água. Instala-se a hipoglicemia, com efeitos transitórios e posteriormente neuroglicopênicos, resultando progressivamente em perda da consciência, coma e morte. 

|       No músculo extenuado, o ATP vai sendo degradado a xantina e urato, aparecendo ainda radicais livres o que, em conjunto, pode levar a uma lesão irreversível do músculo.

### O limite máximo do esforço. 

|       Parece consenso que o limite máximo do esforço físico aeróbico depende da demanda de O2 que chega à fibra. Ela é limitada e inversamente proporcional à intensidade do exercício, de maneira que melhorias na capacidade respiratória conduzem à maior resistência física. Os limites anaeróbicos não dependem de O2, sendo potencialmente uma função das reservas de fosfocreatina, da capacidade glicolítica (teor enzimático), e das reservas de glicogênio. A glicose sanguínea tem 30 vezes menor disponibilidade de oferta energética do que a glicogenólise, já que a hexoquinase tem bem menor atividade do que a fosforilase-a.

### Adaptações ao exercício físico.

|       O treinamento físico possibilita adaptações respiratórias, cardiovasculares, musculares, oxidativas, e energéticas. As adaptações respiratórias incluem um aumento da capacidade pulmonar (no sentido de extrair mais O2 atmosférico e expulsar mais CO2 do corpo), e no teor de hemácias (aumento da taxa de renovação celular). As adaptações cardiovasculares incluem um aumento de massa e volume sistólico (cardiomegalia, e não aumento da frequência cardíaca), e um aumento na diferença arteriovenosa de consumo de O2 (gás que aporta à fibra). As adaptações musculares locais incidem no aumento da densidade capilar e fluxo sanguíneo locais, bem como hipertrofia e hiperplasia musculares. O potencial oxidativo, medido pela atividade da glicerolfosfato desidrogenase (lançadeira do glicerol-fosfato), succinato desidrogenase (ciclo de Krebs), e citocromo oxidase (cadeia respiratória), também aumenta, constituindo a mais importante das adaptações em tempo e intensidade. 

|       Enzimas da $\beta$-oxidação e da cetólise não são aferidas, uma vez que estão apenas sujeitas a controle estequiométrico, hierarquicamente dependente daquelas. Adaptações de enzimas glicolíticas e glicogenolíticas são inconclusivas, sabendo-se aumentar teores de lactato desidrogenase (LDH, protege contra a formação de lactato), e de glicogênio sintetase. As adaptações energéticas são variadas, já que a contratilidade é sustentada pela gliconeogênese, glicogenólise e lipólise. 

|       O catabolismo do glicogênio, colocado no animal para esforços bruscos e cotidianos de curta duração, leva geralmente à exaustão experimentada numa corrida de longa distância. De fato, a utilização do glicogênio costuma ser superestimada, uma vez que numa corrida de 1600m são consumidos apenas 22g de carboidratos e 11g de gorduras. Não obstante, o treinado coloca menos lactato no sangue do que o sedentário, porque o glicogênio passa a ser poupado. A glicólise desacelera, em decorrência da inibição alostérica de ácidos graxos, dependendo, o atleta ou trabalhador preparado, de seu condicionamento no consumo e transporte de ácidos graxos para o músculo. Na captação da glicose, também melhoram os teores de AST (Ala aminotransferase) muscular e hepática, como matérias-primas para a gliconeogênese. 

|       Há aumento lisossômico para degradação protéica, o que justifica a ingesta maior de proteínas por atletas adaptados ao exercício. A eficiência de absorção da glicose cresce de 15 vezes, nos primeiros minutos, a 35 vezes, em 60 minutos. A adaptação endócrina também ocorre, com aumento no teor de receptores de insulina na fibra, o que justifica a recomendação de exercício físico ao diabético. O consumo de ácidos graxos e seu transporte aos músculos também se aprimoram no exercício (músculo tem 50 vezes menos ácidos graxos que tecido adiposo), e sobrepoem o de glicose a longo prazo. 

|       A liberação de gorduras se dá pelo aumento de cAMP decorrente de uma descarga simpática. O consumo de aminoácidos aumenta, podendo suprir até 10% da energia muscular requerida no exercício, o qual promove diminuição de síntese protéica em curto prazo e aumentada, em longo prazo, aumento na oxidação de aminoácidos, e redução da meia-vida de proteínas. Isto torna razoável a recomendação dietética para atletas de 2g de proteína/Kg de peso, o dobro da de sedentários.  Por fim, a amônia resultante do exercício físico pode vir da oxidação de aminoácidos (o NH3 liberado forma uréia, excretada pelo suor e urina) ou de purinas. Com relação aos primeiros, dietas ricas em carboidratos tendem a aumentar a captação muscular de aminoácidos ramificados, podendo levar à hiperamonia do tecido.  Com relação ao catabolismo das purinas, o problema é a produção de radicais livres. 


