---
title: "Metabolismo na Hipoglicemia, Obesidade, Gestação e Lactação"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       Assim como no jejum, estresse e trauma, o metabolismo na hipoglicemia, gestação e lactação é catabólico. Assim como no metabolismo absortivo, a obesidade envolve um processo anabólico. Vamos por partes. Na obesidade, as rotas anabólicas de síntese de proteínas, lipogênese (síntese de ácidos graxos), glicogenogênese (síntese de glicogênio), e cetogênese (produção de corpos cetônicos) estão aumentadas. Acontece que a síntese de proteínas e de glicogênio é limitada, ao passo que de gordura não. Nesse sentido, a obesidade se dá por uma exarcebação do metabolismo absortivo, onde os excessos de nutrientes são convertidos em gorduras. Além disso, como há excesso de gorduras no corpo, as gorduras ingeridas pela dieta tendem a ser acumuladas ainda mais, conferindo ao seu autor a silhueta esférica de que todos tememos. É claro que esta situação difere de pessoa para pessoa mas, como regra geral, a obesidade advém de uma ingesta calórica superior às necessidades corporais. 

|       Já a hipoglicemia, a gestação e a lactação são metabolicamente opostas, isto é, ao invés de um excesso de nutrimentos, tem-se uma carência dos mesmos. A regra geral nestes 3 quadros é a de que falta glicose no sangue e, por consequência, ATP para as células. Na hipoglicemia, que pode ocorrer no jejum ou no alcoolismo, isto é bastante evidente, levando o indivíduo a sintomas de sudorese, queda de pressão arterial, confusão mental e tremor. Em casos mais severos, a hipoglicemia pode resultar em convulsões, coma e óbito (sintomas neuroglicopênicos). 

|       Na gestação e lactação o que ocorre é uma sinalização ao organismo materno de que é preciso construir um algo mais. No caso da gestação, esse algo mais é o feto, o qual pode ser considerado como um tecido esfomeado em formação. Neste sentido, a glicose, os ácidos graxos, os corpos cetônicos, os ácidos nucléicos e as proteínas, têm o seu metabolismo voltado para a quebra e fornecimento de energia para o desenvolvimento do feto. Na lactação, o que muda é o alvo. Ao invés do metabolismo materno estar voltado para um feto em formação, ele o está para o desenvolvimento de glândulas e ductos mamários, e para a formação do leite. Como este último é essencialmente formado por proteínas (caseína, lactalbumina, imunoglobulinas), gordura e lactose (dissacarídio de glicose+galactose), as rotas metabólicas maternas estarão desviadas para a produção desses metabólitos, para a elaboração do leite e de seu tecido produtor. Nos dois últimos quadros fisiológicos, gestação e lactação, como o metabolismo não está privilegiando a mãe como um todo, mas tecidos específicos, a mesma pode ser acometida de sub-nutrição e hipoglicemia, razão pela qual a dieta materna em ambos os casos torna-se especial.

## Detalhes

### Metabolismo na hipoglicemia. 

|       A sintomatologia da hipoglicemia é consequência direta ou indireta da diminuição do teor de glicose no sistema nervoso. Como os nervos não armazenam glicogênio, há a necessidade de obtenção da glicose através da alimentação, pela glicogenólise hepática, ou pela gliconeogênese. A hipoglicemia afeta mais as áreas cerebrais de alta atividade metabólica e os centros vegetativos respiratórios. Os sintomas precoces, que surgem em níveis glicêmicos em torno de 50mg/dl, envolvem mal estar, apatia, confusão, enjôo, cefaléia, nervosismo, sudorese, irritabilidade. 

|       Os sintomas avançados envolvem convulsões, desmaios, coma e morte (neuroglicopênicos). A hipoglicemia pode ser de jejum ou pós-prandial. Os ataques hipoglicêmicos do jejum ocorrem geralmente pela manhã, quando foram esgotadas as reservas de glicose.A hipoglicemia de jejum pode ser devida a um aumento na utilização da glicose ou diminuição de sua produção. O aumento da utilização glicêmica pode ser devido a insulinoma (tumor pancreático das células $\beta$, com secreção descontrolada de insulina), tumores extra-pancreáticos (principalmente do abdomen, como carcinoma gastrointestinal), megadosagem de insulina exógena, ou síndrome auto-imune (anticorpos contra sítios de ligação da insulina). 

|       A produção diminuida de glicose, por sua vez, pode ser devida a doenças endócrinas (doença de Addison – hipofunção da córtex adrenal, com síntese reduzida de cortisol), doença hepática grave (destruição de 80% do parênquima hepático), ou alcoolismo. Associada a mal nutrição, essa última ocorre em pessoas jovens, após a primeira exposição ao álcool ou no alcoolismo crônico. A hipoglicemia alcoólica é decorrente de inibição da gliconeogênese (baixa oxidação de piruvato, lactato e alanina), resposta diminuida de hormônios reguladores da glicemia, ou potencialização do efeito hipoglicêmico da insulina e das sulfoniluréias. 

|       Paralelamente à hipoglicemia de jejum, há a hipoglicemia pós-prandial, cujos ataques ocorrem de 2 a 5 h após uma refeição. O diagnóstico é realizado através do teste de tolerância à glicose (injesta única de 50g/200ml de glicose, seguida de monitoramento periódico dos níveis glicêmicos por  3h). Este tipo de glicemia é classificado em três grupos. Assim, a hipoglicemia pós-prandial pode ser alimentar (observada em pacientes de cirurgia gástrica, ocorre de 1 a 3 h após a injestão de glicose), secundária ao diabetes (resposta tardia do pâncreas ao estímulo de carboidratos, entre 3 a 5 h após injesta glicêmica), e funcional (causa idiopática, liberação excessiva de insulina à presença de carboidratos). Esta última desenvolve-se em pacientes tensos e de personalidade compulsiva, geralmente em estado de stress e psiconeurose.


### Metabolismo na obesidade. 

|       Problema nutricional mais comum entre os norte-americanos, pode levar ao diabetes, hipertensão, e doenças cardiovasculares. Possui origem simples: injesta calórica além das necessidades corporais. Paralelamente, já se conhece genes relacionados à obesidade, como o gene ob, que codifica a proteína leptina, associada à redução de apetite e perda de peso (aumento no gasto de energia). O tipo mais comum de obesidade envolve uma hiperplasia de adipócitos (não aumentam em número). 

|       Na obesidade infantil, pode ocorre hiperplasia e hipertrofia (aumento no número) dos adipócitos. O único tratamento efetivo para a obesidade é a redução na ingestão ou o aumento no gasto de calorias. Existe uma  base bioquímica para o queixume geral de que é mais fácil ganhar do que perder peso. A baixa injestão de calorias é compensada pelo corpo pela redução do metabolismo basal e síntese reduzida de T3, triiodotironina da tireóide. Além disso, cerca de 95% das pessoas que perdem teores significativos de gordura, o readquirem dentro de 1 ano. 

|       Metabolicamente a obesidade envolve um excesso na absorção de glicose e aminoácidos pelo intestino, os quais são convertidos em gordura (juntamente com o lactato fermentativo). Ocorre então um aumento no teor de VLDL e quilomicra (gordura vinda dos vasos linfáticos a partir do intestino), os quais são transformados em gordura para acúmulo no tecido adiposo.


### Metabolismo na gestação. 

|       O feto pode ser considerado como um outro tecido que polariza nutrientes. Neste sentido, utiliza primariamente glicose, mas também aminoácidos, lactato, ácidos graxos e corpos cetônicos. O lactato produzido na placenta pela glicólise segue duas direções. Parte é direcionada ao feto, onde serve como combustível, e o restante retorna à circulação materna, para estabelecer o ciclo de Cori, com o fígado. 

|       O colesterol do LDL materno é um precursor importante de esteróides da placenta (estradiol e progesterona). Durante a gravidez, o ciclo jejum-alimentação é alterado. A placenta secreta um hormônio polipeptídico, lactogênio placentário, e dois hormônios esteróides, estradiol e progesterona. O lactogênio placentário estimula a lipólise no tecido adiposo e os hormônios esteróides induzem um estado de resistência à insulina. Assim, no estado pós-prandial, mulheres grávidas entram no estado de jejum mais rapidamente que mulheres não grávidas. Isso resulta do aumento de consumo de glicose e aminoácidos pelo feto. Os níveis plasmáticos de glicose, aminoácidos e insulina caem rapidamente e os níveis de glicagon e lactogênio placentário aumentam e estimulam a lipólise e a cetogênese. 

|       O consumo de glicose e aminoácidos pelo feto pode ser elevado o suficiente para causar hipoglicemia materna. Por outro lado, no estado alimentado, mulheres grávidas apresentam níveis aumentados de insulina e glicose e demonstram resistência à insulina exógena. Essas alterações nos hormônios plasmáticos e nos combustíveis são ainda mais exageradas em mulheres diabéticas grávidas, tornando o controle de sua glicose sanguínea difícil.


### Metabolismo na lactação. 

|       No final da gravidez, os hormônios placentários induzem a lipoproteína lipase, nas glândulas mamárias, e promovem o desenvolvimento das células e dos ductos secretores de leite. Durante a lactação, a mama utiliza glicose para síntese de lactose e de triacilgliceróis, como principal fonte de energia. Aminoácidos são captados para síntese de proteínas, quilomicra e VLDLs são utilizados como fonte de ácidos graxos para a síntese de triacilglicerol. Se esses compostos não forem fornecidos pela dieta, proteólise, gliconeogênese e lipólise precisam fornecê-los, resultando, eventualmente, em mal nutrição materna e má qualidade do leite. A mama lactante também secreta um hormônio com alguma semelhança ao hormônio da paratireóide. Esse hormônio é, provavelmente, importante para a absorção de cálcio e fósforo do intestino e osso.




