---
title: "Membranas biológicas"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       Membranas são estruturas que separam compartimentos. Uma linguiçinha de churrasco só não se desmancha na grelha ou no espeto devido a membrana que a circunda. Membranas biológicas também separam compartimentos. Há a membrana citoplasmática, a membrana nuclear, e as membranas das organelas celulares. Com este nível de compartimentalização celular, é possível à célula realizar diferentes trabalhos em diferentes locais dentro da mesma. 

|       Mas membranas biológicas não servem apenas para separar ambientes, mas também para a comunicação entre as células, o transporte de íons e nutrimentos, a resposta elétrica dos neurônios, a percepção visual, o reconhecimento imunológico e de tipagem sanguínea, e muitas outras atividades. No entanto, todas as atividades das membranas que não estão relacionadas à separação física entre compartimentos, são desempenhados por protéinas, carboidratos e lipídios, que se encontram afixados ou boiando na superfície das membranas. Excessão à esta regra é o transporte de gases e algumas estruturas lipídicas pequenas, que trespassam a membrana sem auxílio daquelas biomoléculas nela inserida. 


|       Sendo assim, pode-se afirmar que a membrana é uma mistura complexa de lipídios, carboidratos e proteínas, formando um verdadeiro mosaico heterogêneo de estruturas. Nesse sentido, a superfície de uma membrana biológica  pode ser comparada com a visão panorâmica que se experimenta ao se observar, de dentro de um avião, os inúmeros arranha-céus, prédios e casas que se apresentam nos momentos que antecedem o pouso num aeroporto de cidade grande. A única diferença é que essas construções não se mexem. No mosaico que é a membrana biológica, seus constituintes estão em constante movimento, dando um aspecto fluídico à mesma, razão pela qual os cientistas afirmam ser as membranas verdadeiros mosaicos fluidos. 

## Detalhes

|       Membranas biológicas possuem uma função dual: ao mesmo tempo em que servem de delimitação externa e compartimentalização celular, propiciam o embebimento de um número infindável de proteínas, carboidratos e lipídios, próprios da mesma,  permitindo-lhe movimento amebóide, endo/exocitose, divisão celular, alteração de forma e permeabilidade seletiva (transporte). 

![Modelo tridimensional de preenchimente para membrana celular, apresentando  moléculas de água nas extremidades polares dos lipídios. Observar o caráter de dupla camada lipídica (ao nível das esferas), além do alto grau de insaturação dos ácidos graxos presentes na membrana. Essa insaturação confere à membrana celular grande flexibilidade estrutural, paralela a fornecida por moléculas de colesterol e movimentos dinâmicos de proteínas periféricas e integrais.](membrana.png){#fig-membrana}

|       A arquitetura supramolecular da membrana envolve uma bicamada lipídica de 5-8 nm de espessura, contendo um grande número de proteínas (até 90 % em bastonetes de retina), lipídios (20-55 %) e carboidratos, esses últimos aderidos à glicoproteínas e glicolipídios. Em vegetais, há que se considerar a presença de clorofilas, carotenóides, plastoquinonas (cloroplastos) e ubiquinonas (mitocôndrias), como lipídios outros que fosfo e glicolipídios comuns das membranas animais. As proteínas podem estar ligadas à membrana por forças fracas, como pontes de hidrogênio ou interação eletrostática (proteínas periféricas), ou por forças fortes, como ligações éster/amida à ácido graxo, isoprenóides ou carboidratos (proteínas integrais, ex: transmembrânicas). 


|       Tanto proteínas como lipídios possuem grande movimentação na membrana (rotação, deslocamento lateral e transversão) o que, aliado à transição de estados fluido/paracristal da mesma, fornece à membrana a sua dimensão de "mosaico fluido". Uma função vital das membranas decorre de sua capacidade para o transporte seletivo. Esse transporte pode ocorrer com ou sem um acoplamento energético (transporte ativo e passivo, respectivamente). O transporte passivo pode se dar através de uma difusão simples de compostos essencialmente apolares (O2, N2, CH4), ou por auxílio de uma proteína facilitadora desse transporte (transporte passivo facilitado, ex: permease, GLUT-transportadores de glicose). Nesse caso, a energia de ativação necessária para se remover as moléculas de água da capa de hidratação do soluto, permitir sua passagem pela membrana, e rehidratá-lo após esta, torna-se bem menor quando na presença de uma proteína facilitadora. 
O transporte de glicose para o interior da célula na presença das GLUT ocorre, por exemplo 50 mil vezes mais rápido do que em sua ausência. Assim também ocorre o transporte de Cl- e NO3- na planta. 

|       Os transportadores agem cineticamente como enzimas: catalisam o transporte até um valor de saturação, interagem por forças fracas, e possuem grande afinidade estereoquímica. Alguns transportes facilitados podem ocorrer duplamente (simporte e antiporte), quando um soluto entra/sai da célula concomitantemente à entrada/saída de outro. Exemplificando, há o simporte de H+/NO3- e o antiporte de Na+/H+, e de Ca2+/H+ pelas plantas. O transporte ativo envolve sempre um acoplamento energético na forma de quebra de ATP, reação de oxidação, absorção de luz ou fluxo concomitante de outro soluto, permitindo a viabilidade de uma reação energeticamente inviável. 


|       Assim ocorre com a bomba de Na+/K+, que oferta 3 Na+ ao meio extracelular a cada 2 K+ captados para dentro da célula, permitindo uma diferença de potencial de 50-70 mV negativos (fica mais positivo fora do que dentro), fonte de toda a atividade elétrica celular (impulsos nervosos, despolarizações/repolarizações de células de músculo liso, etc). 

## Aplicação

|       Alguns compostos são capazes de bloquear o funcionamento de bombas protéicas de Na+/K+, tais como o vanadato e a ouabaína, inviabilizando a atividade celular (25% de toda energia eucariota é consumida com as bombas de Na+/K+). Alguns antibióticos de estrutura peptídica também agem no fluxo de íons através das membranas de bactérias. Esses peptídios, tais como a valinomicina (K+) e a monensina (Na+), agem encobrindo íons de troca, neutralizando sua carga e, consequentemente, a ação efetiva de bombas e canais protéicos bacterianos. 

|       Em vegetais, a membrana tem importância singular na membrana plasmática (plamalema), em vacúolos, nos tilacóides dos cloroplastos, nos peroxissomos, nos plastídeos, e nos tonoplastos. Nestes últimos, uma diferença no bombeamento de prótons H+ (transporte primário) gera uma variação de pH que, acoplada à ATPase (transporte secundário) permite uma força motriz geradora de carga elétrica e de ATP para a planta. Diferenças na pressão osmótica também permitem a função de abertura/fechamento da membrana das células-guarda de estômatos. 








