---
title: "Bioquímica de Pastagens e Forrageiras"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       Proteína bruta (PB), extrato etéreo (EE), extrato não nitrogenado (ENN), fibra bruta (FB), matéria mineral ou cinzas (MM), e matéria seca (MT), bem como fibra de detergente neutro (FDN) e fibra de detergente ácido (FDA), constituem elementos da composição centesimal de pastagens e forragens oferecidas nutricionalmente aos mais diversos rebanhos. Ambas são constituídas por diferentes teores de proteínas, nitrogênio não protéico, lipídeos e proteínas, dependente do espécime vegetal, maturação da planta, solo, clima, insulação, e demais fatores que atuam diretamente na digestibilidade do alimento para o animal de produção.

## Detalhes

|       As pastagens constituem a base da dieta de ruminantes na grande maioria dos sistemas de produção das regiões tropicais. Na composição botânica destas pastagens, é encontrada ampla variação de espécies na sua grande maioria representadas por gramíneas e leguminosas, as quais podem ser nativas ou cultivadas, e cujas qualidades nutritivas são muito variáveis. 

|       Essa variação é uma função do culivar, da anatomia vegetal, do estágio de maturidade, da fertilidade do solo e de condições locais e sazonais. A qualidade das forragens está intimamente relacionada ao consumo de energia disponível (ED) que define o desempenho do animal. Neste sentido, a natureza química das forragens e pastagens define o seu valor nutritivo para a alimentação animal.


|       A composição química das espécies forrageiras tem sido determinada desde 1864 através da metodologia de Weende de análise aproximativa. Por esta metodologia são determinados seis grandes componentes químicos das plantas, que são: proteína bruta (PB), extrato etéreo (EE), extrato não nitrogenado (ENN), fibra bruta (FB), matéria mineral ou cinzas (MM), e matéria seca (MT). Paralelamente a esta metodologia, separa-se as diversas frações que constituem as plantas por meio de detergentes inespecíficos, método desenvolvido por Van Soest em 1965. Assim, tem-se a fibra de detergente neutro (FDN) e a fibra de detergente ácido (FDA).


|       A concentração de MS é determinada por secagem da amostra da forragem em estufa a 105 0C, e a MM por combustão em estufa a 600 0C. A PB é avaliada pelo método de Kjedahl, onde se determinam os teores de nitrogênio da amostra e se multiplica pelo fator de conversão 6,25, assumindo que a grande maioria das proteínas possuem 16,5 % de nitrogênio em sua composição elementar. O EE envolve principalmente substâncias de natureza lipídica, extraídas dos alimentos pelo uso de solventes orgânicos (éter de petróleo, por exemplo). 

|       A FB constitui a porção da matéria orgânica insolúvel em ácidos e álcalis. O ENN é obtido por diferença, subtraindo-se de 100 os níveis percentuais dos demais componentes. 
	
|       O método de Van Soest, de determinação da qualidade de forrageiras, é baseado na extração de componentes carbo-lipídicos por detergentes. Por meio de um detergente neutro é possível separar o conteúdo celular de parte da forragem solúvel, o qual se constitui basicamente de proteínas, lipídios, carboidratos solúveis, pectinas e outros componentes solúveis da parede vegetal. Esta fração é denominada FDN. A seguir, o uso de detergente ácido solubiliza o conteúdo celular e de hemicelulose, além de grande parte da proteína insolúvel, obtendo-se um resíduo insolúvel em detergente ácido, denominado FDA, e constituido principalmente por frações de hemicelulose e lignina. 

|       O tratamento do resíduo de FDA com solução de ácido sulfúrico (H2SO4 a 72 %) ou permanganato, promove a solubilização da lignina, permitindo assim a determinação desta e da celulose.


### Proteínas

|       A proteína bruta (PB) das plantas forrageiras inclui tanto a proteína verdadeira quanto o nitrogênio não protéico (NNP). Dependendo da maturidade da planta, a proteína verdadeira pode representar até 70 % da PB nas forragens verdes, 60 % da PB do feno, e um percentual muito pequeno nas silagensj. O NPP inclui glutamina, glutamato, asparagina, aspartato, GABA, ácidos nucléicos, pequenas quantidades de nitrato (presentes em forrageiras e significativamente tóxica para o gado), e NNP associado a lignina da parede celular (5-10 % do nitrogênio das forragens). O maior teor de proteínas ocorre nas folhas, com alta digestibilidade e oferta de aminoácidos (muita lisina e pouca metionina e isoleucina), e de pouca variação entre as espécies. O teor proteico de forrageiras declina com a maturidade do espécime.


### Carboidratos

|       Correspondem a 50-80 % da matéria seca (MS) das forrageiras e cereais, com características nutritivas dependentes da composição de monossacarídeos, ligações entre monômeros de sacárides, e fatores físico-químicos. Os carboidratos não estruturais incluem frutose, glicose, de reserva (amido, sacarose e frutosanas), ao passo que os carboidratos estruturais compõem-se de pectina, hemicelulose e celulose, presentes principalmente na parede celular (30-80 % da MS de forrageiras), e marcadores da digestibilidade animal.


### Lipídeos

|       Os teores de lípides em forrageiras encontram-se bem diminuídos, raramente excedendo 60 g/Kg de MS, com os galactolipídeos representando 60 % desta fração. Ácido linolênico representa 60-75 % dos ácidos graxos em forrageiras, seguindo-se o linolênico e o palmítico. Folhas são bastante ricas em lipídes mais do que os talos (galactolipídeos e triglicerídeos), enquanto que sementes dispõe de alto teor de triglicérides para sua germinação.


|       Existem diversos fatores que alteram a qualidade nutricional de forrageiras e pastagens, dentre os quais destacam-se o tipo de solo, clima, o animal, o estágio de densenvolvimento e idade de corte, e fitopatogenias que influenciam o desenvolvimento dos vegetais.