---
title: "Livros Vivos - Uma experiência imersiva com JSPlotly"
---

Esta **<span style="color:red">página em construção</span>** busca ofecer conteúdos didático-científicos para aprendizagem autônoma de textos estilizados combinados à simulações interativas com uso do JSPlotly. 

Ou seja, uma versão para **<span style="color:green">**livros vivos**</span>**, combinando texto e códigos reprodutíveis e editáveis para uso do *JSPlotly*. 


Cada ***livro vivo*** abaixo busca permitir uma *experiência interativa e imersiva única* no uso do aplicativo, na qual a sequência didática é intercalada por objetos interativos. A parte do material relativa ao *USo do JSPlotly* e *JavaScript & JSPlotly* foi estruturada para permitir a inserção direta de comandos em campos visando a reprodução dos objetos abordados, por simples cópia/cola/execução na própria página do *“livro”*, e sem necessidade do programa *JSPlotly* externo. 

Os demais *livros vivos* em construção foram estruturados para permitir uma combinação da sequência didática com objetos interativos de JSPlotly personalizados a cada tema. 

O material intititulado **JSPlotly por Estudantes** compreende alguns temas do ensino médio para Matemática e Ciências da Natureza abordados com auxílio de objetos interativos desenvolvidos por estudantes de graduação e do ensino médio.


[Uso do JSPlotly](Tutorial/_book/index.html){target="_blank" rel="noopener"}

[JavaScript & JSPlotly](JS/_book/index.html){target="_blank" rel="noopener"}
<!-- [Gráficos e Mapas com *JSPlotly*]() -->

<!-- [3. Gráficos e Mapas com *JSPlotly*](Plotly/_book/index.html){target="_blank" rel="noopener"}  -->

[Simulações Interativas com JSPlotly em Matemática](EM/Mat/_book/index.html){target="_blank" rel="noopener"}

<!-- [4. Matemática & JSPlotly](EM/Mat/_book/index.html){target="_blank" rel="noopener"} -->

[Simulações Interativas com JSPlotly em Física](EM/Fis/_book/index.html){target="_blank" rel="noopener"}

<!-- [5. Física & JSPlotly](EM/Fis/_book/index.html){target="_blank" rel="noopener"} -->

[Simulações Interativas com JSPlotly em Química](EM/Quim/_book/index.html){target="_blank" rel="noopener"}

<!-- [6. Química & JSPlotly](EM/Quim/_book/index.html){target="_blank" rel="noopener"} -->

[Simulações Interativas com JSPlotly em Biologia](EM/Bio/_book/index.html){target="_blank" rel="noopener"}

<!-- [7. Biologia & JSPlotly](EM/Bio/_book/index.html){target="_blank" rel="noopener"} -->

[Simulações Interativas com JSPlotly em Físico-química de Proteínas](ES/biofisQuim/_book/index.html){target="_blank" rel="noopener"}      

<!-- [8. Biofísico-química & JSPlotly](ES/bioFisquimProt/_book/index.html){target="_blank" rel="noopener"} -->

[JSPlotly por Estudantes](EM/Student/_book/index.html) 

[Sensores & JSPlotly]() 



