<!-- Google tag (gtag.js)-->

```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```

```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```

# Introdução {.unnumbered}

|       O *software* de programação estatística **R** e sua interface gráfica (*GUI*) **Rstudio** encerram um ambiente de desenvolvimento integrado (*IDE*) de emprego virtualmente ilimitado para diversas áreas do conhecimento. Dentre essas, as *Ciências da Natureza* e, em especial, a *Bioquímica*, *Biologia Molecular*, *Biofísica*, e áreas afins.
|       São muitas as características que possibilitam o uso do *R & RStudio* para o ensino e aprendizagem em *Bioquímica*. Parte dessas características residem na *Pesquisa Reproduzível* [@gandrud2018reproducible], o qual é resumidamente norteada pela:

1)  Disponibilização dos dados originais;
2)  Existência de um código para processar esses dados e analisá-los;
3)  Documentação dos dados e do código, possibilitando sua reprodutibilidade;
4)  Distribuição e acessibilidade do código.

|       Nesse sentido, a produção de textos, tabelas, gráficos, análise de dados e simulações, podem perfeitamente ajustar-se ao **ensino-aprendizagem** pelo uso de tais princípios e da simultaneidade de texto e códigos, tangenciando um **Ensino Reproduzível**. Tal abordagem permite ao leitor o estudo dos diversos temas tratados por leitura e interpretação, como também de sua apropriação mais convergente, pela execução, modificação, e criação de códigos pertinentes em cada tema. Na presente obra, essas concepções são aplicadas ao *conteúdo quantitativo* e às *relações matemáticas* dos temas abordados em *Bioquímica*.
|       Essas relações estão presentes nos **livros-texto de Bioquímica** e abrangem, por exemplo, **curvas de titulação de ácidos fracos e aminoácidos**, estudo de **cargas efetivas em biomoléculas**, **características físico-químicas de proteínas e ácidos nucleicos** previstas por análise de sequência, **cinética de enzimas e sua inibição**, **quantidades termodinâmicas e Bioenergética**, **interação ligante-biopolímero**, **estequiometria de reações bioquímicas**, **rotas bioquímicas e redes metabólicas**, dentre outros.
|       De modo geral, os temas acima são abordados neste material com auxílio do *R & RStudio*. Não obstante, seu conteúdo não possui a pretensão de abordar, para além da superfície, o uso do *R*, do *RStudio*, e mesmo dos temas de *Bioquímica* propostos. Para esses, recomenda-se as fontes tradicionais de tutoriais, livros-texto e internete. E tampouco se arrisca a adentrar no universo da *Bioinformática*, tradicional ou estrutural, como na *Biologia de Sistemas*, *alinhamento de sequências*, *predição estrutural*, *modelagem, dinâmica e atracamento moleculares*, ou nas várias faces dos *estudos ômicos*.
|       Em resumo, objetiva-se apenas abordar os *conteúdos quantitativos* e *relações matemáticas* presentes em parte da *Bioquímica*, tal como descrito acima, utilizando o *R & Rstudio*. Essa abordagem tangencia a **solução de problemas e simulações por sistema linear de equações, álgebra linear, ajuste linear, não linear, polinomial, linear múltiplo, otimização, minimização, equações diferenciais simples, e análise de sequências**, dentre outros.
|       Secundariamente, objetiva-se permitir que o leitor possa, a partir da repetição ou modificação de trechos simples de códigos e de *scripts*, reproduzir cálculos, gráficos e/ou tabelas pertinentes aos conteúdos elencados.
