---
title: "Algumas características do Jmol como visualizador molecular"
toc: true
lang: pt
---


1.  Programa didático e intuitivo;
2.  Programa completo de distribuição e código-fonte livres, não restrito à versões demonstrativas ou educacionais;
3.  Não requer instalação, apenas inicialização de arquivo executável em *Java*.
4.  Como não possui instalação, basta copiar o diretório do programa pra uso em mídias removíveis;
5.  Permite salvar a imagem como um PNG interativo, cujo arquivo pode ser aberto num visualizador de imagens, ou de forma integrada, diretamente no Jmol.
6.  Se imagens renderizáveis, basta clique-e-arraste da mesma à janela do *Jmol*;
7.  Permite rodar independentemente da linguagem *Java*, por *applet JSmol*, inteiramente em HTML5, o que permite seu uso por qualquer navegador de internet;
8.  Permite inserção de modelos tridimensionais em páginas da internete por *JavaScript*;
9.  É bastante empregado na produção de imagens e modelos dinâmicos em diversos *sites* e livros;
10. Possui um número elevado de tutoriais disponíveis *online.*
11. Adota linhas de comando simples;
12. Facilita a identificação de erro de digitação, mostrando destacando em vermelho a linha de comando; 1 Permite *scripts* salvos como vídeos por um conjunto sequencial de comandos;
13. Permite uso de mais de uma seção ao mesmo tempo;
14. Permite uso de *kit* de ferramentas de desenvolvimento para outros aplicativos em *Java*.
15. Permite *Menu* customizável pelo usuário;
16. Possui *user group* bastante ativo na internet;
17. Roda as imagens em HTML5, o que permite independência de dispositivo (móvel ou não) e de sistema operacional;
18. Inclui análise de simetria cristalográfica.
19. Carrega e permite a produção de diversos formatos de superfícies moleculares (van der Waals, superfície molecular, área acessível ao solvente - SAS, potencial eletrostático);
20. Permite carregamento de arquivos acima de 60 formatos, incluindo Protein Data Bank (PDB), Crystallographic Information File (CIF), MDL Molfile (mol), e Chemical Markup Language (CML), bem como sessões do Pymol (PSE);
21. Permite carregamento da molécula a partir da internete, pela introdução de código PDB, SMILES ou PubChem, além de linguagem SMART;
22. Exporta para GIF, JPG, PNG, PDF, WRL, POV-Ray, e OBJ;
23. Possui biblioteca genérica JavaScript para Swing.
24. Permite leitura de formatos espectroscópicos de JCAMP-DX, CML, AnIML por JSpecView.
25. Permite simulação de espectrogramas de 1H e 13C de NMR.
26. Produz espectros interativos em formato PDF de IR, Raman, NMR, GC/MS, e UV/VIS;
27. Suporta cálculos de energia e minimização (MMFF94/UFF).
28. Permite alinhamento de estruturas;

29. Apesar de não realizar ou possuir extensão para módulos de modelagem, simulação ou dinâmica molecular, permite um esboço de parte dessas ações (ex: otimização de estrutura secundária de proteínas, rastreamento de sítios prováveis de interação).
30. É mais limitado para atividades de alinhamento de estruturas para comparação ou mutações dirigidas, em relação a alguns concorrentes;
31. Possui pouquíssimos *plugins*, contrariamente a alguns concorrentes;
32. Renderiza imagens vetoriais com alta qualidade para publicação, embora de forma indireta (POV-ray);
33. Trata-se de programa para visualização molecular com linhas de comando e programação acessível por navegador, o que o diferencia de seus concorrentes.
