---
title: "Carboidratos"
toc: true
lang: pt
---

<!-- Google tag (gtag.js)-->

```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```

```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Monossacarídios

| 
|       Carboidratos são definidos como **polihidroxialdeídos**\index{polihidroxialdeído} ou **polihidroxiacetonas**\index{polihidroxicetona}, a partir do esqueleto carbônico mais simples de um trissacarídio, tal representado como *projeção de Fisher* para o [gliceraldeído](https://chemapps.stolaf.edu/jmol/jmol.php?model=glyceraldehyde&script=Console){target="_blank"} e para a [diidroxicetona](https://chemapps.stolaf.edu/jmol/jmol.php?model=dihydroxyacetone&script=Console){target="_blank"}. Dessa forma, os carboidratos passam a referir-se como **aldoses**\index{aldose} ou como **cetoses**\index{cetose}.

|       Carboidratos, assim como aminoácidos, apresentam um *centro quiral*\index{centro quiral} e, por consequência, uma **isomeria óptica**\index{isomeria óptica}, detectável num polarímetro. Identifique o *carbono quiral* para o [gliceraldeído](https://chemapps.stolaf.edu/jmol/jmol.php?model=glyceraldehyde&script=Console){target="_blank"}. Identifique também se o modelo refere-se a *D-gliceraldeído* ou a *L-gliceraldeído*.

|       Para isso, rotacione a molécula de modo a manter a carbonila (C=O) voltada para baixo, e com seu átomo de oxigênio à direita. Caso o grupo hidroxila (-OH) esteja à direita da ecrã do *Jmol*, trata-se de D-gliceraldeído. Do contrário, será L-gliceraldeído. Percebe-se dessa forma que o modelo acessado pelo *link* é de um D-gliceraldeído.

|       A partir dessas moléculas é possível compor diversos carboidratos variando-se o número de seus carbonos (*diose, triose, tetrose, pentose, hexose, heptose*) e/ou a função que os definem (*aldoses ou cetoses*). Assim, uma molécula de *glicopiranose* pode ser representada por uma [glicose](https://chemapps.stolaf.edu/jmol/jmol.php?model=glucose&script=Console){target="_blank"}

|       A estrutura linear representada acima é de baixíssima proporção em solução. A estrutura mais comum envolve uma *ciclização* oriunda de uma torção inicial entre *C-4* e *C-5*, o que aproxima um álcool do grupo funcional do carboidrato, Dessa forma, sucede-se uma reação entre a função álcool e um aldeído/cetona, produzindo um *hemiacetal* (aldeído + R-OH) ou um *hemicetal* (cetona + R-OH). Com a ciclização, o carboidrato ganha mais um centro quiral.

|       Vale aqui um intervalo sobre a aquisição de novos modelos para visualização pelo *Jmol*. Até o momento, e salvo raras excessões, utilizamos arquivos de atributo *PDB* referentes ao depósito de biomoléculas cristalografadas no sítio homônimo. Outras biomoléculas são facilmente acessíveis pelo próprio *Jmol*, por *File, Get Mol*, o que é espelhado para a *web* pelo pelas estruturas carregadas a partir do sítio [Chemapps-Stolaf](https://chemapps.stolaf.edu/jmol/jmol.php?pdbid=XXX&script=Console){target="_blank"}.

|       Ocorre que para outras moléculas, tais como as contidas neste capítulo, as estruturas estão dispersas pela internete, sendo necessário seu *download* e posterior carregamento no *Jmol*.

|       Relembrando uma característica do *Jmol*, para compreender melhor os conceitos reportados neste material, além de visualizar a imagem correlata a cada assunto em um programa comum de imagens, também é possível clicar e arrastar o arquivo de imagem *PNG* (*Portable Network Graphics*) baixado deste sítio para a janela principal do *Jmol.* Isso permitirá um estudo mais consolidado, uma vez que se pode observar as moléculas no espaço tridimensional como fora realizado nos capítulos anteriores, podendo-se rotacioná-las, direcionar sua observação para uma região específica, alterar cores e representações, calcular distâncias e ângulos, entre outros.

|       Ilustrando-se para o que foi dito, carregue em seu PC o modelo da [glicose sob fechamento do anel](./figuras/glc_fechando.png){target="_blank"}, e observe os detalhes da reação entre a função álcool com aldeído que culmina na produção do *hemiacetal*.

| Está difícil a visualização ? Experimente então carregar no *Jmol* o modelo de [animação da glicose sob fechamento](./figuras/glc_open_close.png){target="_blank"}

|       Com a ciclização o monossacarídio também adquireuma **isomeria conformacional**\index{isomeria conformacional}. Assim, a conformação de um *ciclohexano*\index{ciclohexano} para o anel de *pirano*\index{pirano} (ex: glicose, uma piranose) ou *furano*\index{furano} (ex: frutose, uma furanose) pode variar. Os principais confôrmeros constituem o [bote](./figuras/bote.png){target="_blank"} e a [cadeira](./figuras/cadeira.png){target="_blank"}, essa energeticamente mais favorável.

|       Reforçando, pode-se observar ambas as estruturas tridimensionalmente baixando-as no PC e arrantando-se uma das imagens com o *mouse* para o ecrã aberto do *Jmol*. E é claro, também pode-se abrir a imagem no programa por *File, Open* !

|       Também é possível visualizar pelo *Jmol* a **isomeria configuracional** de carboidratos. Para tanto, carregue no *Jmol* a [configuração alfa da glicose](./figuras/glicose-a.png){target="_blank"}. Agora posicione o oxigênio do anel ao *Norte*, de tal forma que a função *-CH*$_{2}$OH fique voltada para a esquerda. Incline a molécula para frente aos poucos e observe como o álcool do carbono anomérico em C1 (logo à direita do oxigênio do anel) está situado fora do plano do anel. Essa é a configuração $\alpha$ da glicose.

|       Repita o procedimento para a [configuração beta da frutose](./figuras/beta-fru.png){target="_blank"}, uma cetose, para visualizar que a disposição do grupo *-OH* referido não é propriamente acima do plano, como nas representações bidimensionais dos livros-texto, embora seja bem diferente dos isômeros alfa.

## Derivados de carboidratos

|       Além de \index{isomeria constitucional}*isomeria constitucional* (aldo/ceto), \index{isomeria óptica}*isomeria óptica* (L/D), \index{isomeria conformacional}*isomeria conformacional* (bote/cadeira), e \index{isomeria configuracional}*isomeria configuracional*} ($\alpha$/$\beta$), monossacarídios podem sofrer diversas reações, tais como *sulfatização* ([condroitina](./figuras/condroitina.png){target="_blank"}\index{condroitina}), *aminação* ([glicosamina](https://chemapps.stolaf.edu/jmol/jmol.php?model=glucosamine&script=Console){target="_blank"}\index{glicosamina}), *oxidação*, *redução*, *fosforilação*, *metilação*, *introdução de um álcool* (poliol, "sorbitol.png") ou a *desoxidação* (desoxiaçúcar). Essas alterações enriquecem a diversidade estrutural e funcional dos carboidratos, estando relacionadas a variações na interação com o solvente, e com outras biomoléculas, tais como as apresentadas na interação e sinalização celular, entre outros.

## Oligossacarídios

|       São definidos a partir de uma [*ligação acetal (glicosídica)*](./figuras/maltose-lig.png){target="_blank"} entre os carbonos anoméricos de dois monossacarídios. Essa ligação envolve também a liberação de uma moléculas de água. Como observado pelo modelo acima, a ligação acetal\index{ligação acetal} é formada entre os carbonos C1 e C4.

|       A ligação glicosídica também pode caracterizar-se como $\alpha$ (ex: [maltose](./figuras/maltose.png){target="_blank"}\index{maltose}) ou $\beta$ (ex: [celobiose](./figuras/celobiose.png){target="_blank"}\index{celobiose}) em função do *vetor axial ou sagital* de um grupo funcional, no caso *-OH*, a partir do carbono C1 do 1o. monômero. Para evidenciar essa diferença, proceda de modo similar ao que foi realizado com as moléculas de glicose acima no texto.

|       Carregue primeiro a [maltose](./figuras/maltose.png){target="_blank"}. Posicione a molécula de tal forma que o oxigênio do anel do 1o. resíduo, aquele que apresenta em seu carbono $\alpha$ a etiqueta C1, fique à direita. Agora incline a estrutura e evidencie como a ligação glicosídica distancia-se do plano do 1o. resíduo. Essa é a *ligação* $\alpha$, considerada no livros como abaixo do plano bidimensional. Repita esse procedimento com a [celobiose](./figuras/celobiose.png){target="_blank"}, e veja a diferença para uma ligação $\beta$-glicosídica. Observe como a *ligação* $\beta$ ocorre num dímero de [celobiose](https://chemapps.stolaf.edu/jmol/jmol.php?model=cellobiose&script=Console){target="_blank"}\index{celobiose}

|       Na nomenclatura oficial, os oligossacarídios possuem a numeração dos carbonos envolvidos na ligação glicosídica, bem como a direção da reação. Dessa forma, tem-se a [sacarose](https://chemapps.stolaf.edu/jmol/jmol.php?model=sucrose&script=Console){target="_blank"}\index{sacarose}, açúcar de cozinha, ou ou $\alpha$-D-glicopiranosil (1,2)-$\beta$-D-frutofuranose, como um dissacarídio formado pela ligação acetal entre um resíduo de glicose e um de frutose.

|       Como a *ligação glicosídica*\index{ligação glicosídica} compromete os dois *carbonos anoméricos*\index{carbono anomérico} envolvidos na formação da sacarose, essa perde a capacidade redutora do grupo carbonila. O mesmo não ocorre com a [lactose](https://chemapps.stolaf.edu/jmol/jmol.php?model=XXX&script=Console){target="_blank"}\index{lactose}, cuja ligação glicosídica ainda permite um potencial redutor\index{potencial redutor} de um anômero livre (Cu$^{+}$ para Cu$^{0}$, por ex.).

|       Clinicamente, a deficiência da enzima $\beta$-galactosidase impede a hidrólise da ligação glicosídica da lactose acumulando-a nos tecidos e induzindo uma das formas de mal absorção/intolerância à lactose.

|       Dessa forma podem juntar-se monossacarídios formando dissacarídios ([maltose](https://chemapps.stolaf.edu/jmol/jmol.php?model=maltose&script=Console){target="_blank"}\index{maltose}), trissacarídios ([maltotriose](https://chemapps.stolaf.edu/jmol/jmol.php?model=maltotriose&script=Console){target="_blank"}\index{maltotriose}), tetrassacarídios, etc.

|       Alguns oligômeros de 15-50 unidades, aproximadamente, também podem exibir propriedades benéficas a saúde, sendo considerados *oligossacarídios funcionais*. Um exemplo de oligossacarídio funcional é a [inulina](./figuras/inulina.png){target="_blank"}, um frutooligossacarídio composto de 30 resíduos de frutose e um de glicose, e relacionado à benefícios digestórios, antimicrobianos e de imunomodulação.

## Polissacarídios

|       Ainda que não haja consenso sobre seu tamanho, considera-se como polissacarídio um polímero variando entre 300 a mais de 50.000 resíduos monoméricos. Esses polímeros, ou **glicanos**\index{glicano}, podem exibir um mesmo monômero em sua constituição sendo assim denominados por *homoglicanos*\index{homoglicano}, ou por tipos distintos de monômeros, produzindo *heteroglicanos*\index{heteroglicano}.

|       O exemplo mais comum de um homoglicano é o *amido*\index{amido}. É composto de uma estrutura ramificada e outra linear. A estrutura ramificada é denominada [amilopectina](./figuras/amilopectina.png){target="_blank"} (no modelo, apresentada com 25 resíduos de glicose. Veja uma estrutura mais concisa da [amilopectina](https://chemapps.stolaf.edu/jmol/jmol.php?model=amylopectin&script=Console){target="_blank"}\index{amylopectin}.

|       A ramificação dá-se na direção 1-6 entre cada 10-12 resíduos de glicose. O [glicogênio](./figuras/glicogenio.png){target="_blank"}\index{glicogênio} animal é similar à amilopectina, exceto pelo grau maior de ramificação decorrente do espaçamento de 8-12 resíduos de glicose. Segue um modelo mais conciso para renderização do [glicogênio](https://chemapps.stolaf.edu/jmol/jmol.php?model=glycogen&script=Console){target="_blank"}\index{glycogen} Gire a estrutura (modelo conciso ou mais amplo) e perceba que há uma espiral central em sua molécula. Essa conformação helicoidal representa a [amilose](./figuras/amilose.png){target="_blank"}. A amilose possui estrutura linear e apresenta uma conformação helicoidal. Veja que tanto o glicogênio como o amido possuem essa estrutura em hélice.

|       Outro *homopolissacarídio* comum é a [celulose](./figuras/celulose.png){target="_blank"}\index{celulose}, um polímero linear de resíduos de glicose. Tanto a amilose como a celulose possuem conformações decorrentes da *configuração* de sua ligação glicosídica, $\alpha$ para a amilose e $\beta$ para a celulose.

### Outros polissacarídios

|       Diversos polissacarídios, homo ou hetero, atuam funcionalmente nas células, como o [ácido hialurônico](./figuras/acido-hialuronico.png){target="_blank"}\index{ácido hialurônico}, um heteroglicano do humor vítreo e líquido sinovial, formado por $\beta$-acetil-N-glicosamina e ácido glicurônico, ou a [pectina](./figuras/pectina.png){target="_blank"}\index{pectina}), um *homopolissacarídio hidrossolúvel - fibra solúvel*, presente na parede vegetal, e formada por ácido galacturónico (poligalacturônico), ramnose, arabinose e galactose.

|       Outros polissacarídios contribuem para a estrutura constitutiva dos organismos, como a [quitina](./figuras/quitina.png){target="_blank"}\index{quitina}, um homoglicano estrutural do exoesqueleto de insetos e crustáceos, formado por resíduos de $\beta$-acetil-N-glicosamina. Observe um modelo renderizado mais conciso para a [quitina](https://chemapps.stolaf.edu/jmol/jmol.php?model=chitin&script=Console){target="_blank"}\index{chitin}. Outros polissacarídios possuem também atividade biológica, tal como a [heparina](https://chemapps.stolaf.edu/jmol/jmol.php?model=heparin&script=Console){target="_blank"}\index{heparin}, um anticoagulante que atua quelando íons cálcio.
