---
title: "Gráficos e Mapas Interativos na Escola"
---


|       Este material pretende oferecer um conjunto de *gráficos e mapas, interativos e de animação*, para alguns tópicos encontrados em disciplinas do *ensino médio*. Esses *objetos didáticos* utilizam pacotes interativos do *R*, principalmente `plotly` e `gganimate`. 

--------------------------------------------------------------

## Objetos Interativos de Ensino Reprodutível (OIER) desenvolvidos para o ensino básico

|       A parte de *Gráficos & Mapas* do [Bioquanti](https://bioquanti.netlify.app/) possui um repositório de objetos didáticos homônimos acompanhados de seus trechos de código comentados, permitindo fácil reprodução, personalização, e criação de novos materiais para compartilhamento. O repositório aborda as áreas de *Matemática, Ciências da Natureza, Ciências Humanas e Linguagens*. Encontra-se dividido em classes, cada qual com alguns *Objetos Interativos de Ensino Reprodutível (OIER)* ilustrativos: Matemática, Física, Química, Biologia, Humanas, História, Geografia, e Linguagens. Cada OIER está referenciado ao título juntamente a alguns códigos correlatos da *BNCC.* A fim de simplificar a produção de cada OIER para gráficos e mapas relativos ao ensino básico, bem como facilitar o uso do `R` em ambiente *RStudio*, privilegiou-se o emprego da biblioteca `plotly`. 

|       Ocasionalmente foi utilizada a biblioteca `ggplot2` para gráficos mais elaborados, e subsequente conversão à interatividade de `plotly` com uso da função `ggplotly` do pacote. Por vezes também foi utilizado o pacote `gganimate`, o qual permite criar uma animação por representação sequencial de gráficos de `ggplot2`, assim como alguns pacotes específicos a determinada situação. 
\

|       Cada OIER está estruturado em 3 partes: 

```{r, eval=FALSE}
1. O OIER propriamente dito, com título e códigos da BNCC;

2. O código-fonte usado para gerar o objeto;

3. Sugestões para modificações do código-fonte para obtenção de um objeto final distinto do original.
```

## Objetos didáticos e códigos


[1. Matemática](matematica.qmd)
\

[2. Física](fisica.qmd)
\

[3. Biologia](biologia.qmd)
\

[4. Humanas](humanas.qmd)
\

[5. História](historia.qmd)
\

[6. Geografia](geografia.qmd)
\

[7. Linguagens](linguagens.qmd)
