project:
  type: website
  output-dir: ../_site/pt
  resources:
    - nivel/superior/sisma/prat/contr.pdf
    - nivel/superior/sisma/prat/carb.pdf
    - nivel/superior/sisma/prat/carb_lip.pdf
    - nivel/superior/sisma/prat/a_nucl.pdf
    # - nivel/superior/jsplotly/sbbq/vdw3D.html
    # - nivel/superior/jsplotly/sbbq/buffer_slider.html
    # - nivel/superior/jsplotly/sbbq/cargaPept_slider.html
    # - nivel/superior/jsplotly/sbbq/gibbs.html
    # - nivel/superior/jsplotly/sbbq/nyquist2.html
    # - nivel/superior/jsplotly/sbbq/3d.html

    

website:
  page-navigation: true
  back-to-top-navigation: true
  image: unifal-logo.png
  reader-mode: true
  google-analytics: "G-S1L73VGCG5"
  title: ""
  favicon: avatar.png

  sidebar:
    contents:
      - section: "JSPlotly & GSPlotly - Simulação gráfica interativa & IA"
        contents:
          - text: "JSPlotly - Simulação gráfica com JavaScript"
            href: nivel/superior/jsplotly/jsplotly_geral.qmd
          - text: "GSPlotly - gerador de códigos por IA para JSPlotly"
            href: nivel/superior/jsplotly/gsplotly.qmd
          - text: "Simulações em Biofísico-química"
            href: nivel/superior/jsplotly/jsplt_bioq.qmd
          - text: "Simulações na Escola"
            href: nivel/basico/jsplotly/jsplotly_bas.qmd
          
            
      - section: "Jmol - Moléculas em 3D"
        contents:
          - text: "Modelos atômicos em Bioquímica"
            href: nivel/superior/jmol/index_jmol.qmd
          - text: "Moléculas 3D na Escola"
            href: nivel/basico/Curso/index_jmol_bas.qmd
          - text: "Jardim de Moléculas"
            href: nivel/basico/Jardim/index_Jardim.qmd

      - section: "R - Cálculos e visualizações"
        contents:
          - text: "R em Biofísico-química"
            href: nivel/superior/r/index_r.qmd
          - text: "scriptRplot: gráficos elegantes com ggplot2"
            href: nivel/superior/ScriptRplot/scriptrplot.qmd
          - text: "R & RStudio na Escola"
            href: nivel/basico/Curso/index_r_bas.qmd
          - text: "Gráficos e mapas interativos na Escola"
            href:  nivel/basico/R/index_OIER.qmd


      - section: "Sisma - diagramas dinâmicos"
        contents:
          - text: "Fluxos dinâmicos em Bioquímica"
            href: nivel/superior/sisma/index_sisma.qmd
          - text: "Diagramas interativos na Escola"
            href: nivel/basico/sisma/index_sisma_bas.qmd

  navbar:
    search: true
    logo: logo-unifal.png

    left:
      #
      # - text: ""
      #   href: images/logo-unifal.png

      - text: "Sobre"
        id: sup-menu
        href: index.html
      - text: "Ensino Reprodutível"
        id: bas-menu
        href: erre.qmd
        
      - text: "Folhas de dicas"
        id: sup-menu
        menu: 
          - text: "Plotly"
            href: cheatsheet/plotly.pdf
          - text: "Jmol"
            href: cheatsheet/jmol_cheat.pt2.pdf
          - text: "R"
            href: cheatsheet/r_cheat.pt.pdf
          

      - text: "Trabalhos"
        href: producao.qmd

      - text: "Contato"
        href: contato.qmd
         
    right:
    
      - text: "EN"
        href: ../en/index.html


format:
  html:
    theme: 
      light: flatly
    css: styles.css
    code-overflow: wrap

execute:
  cache: true
  message: false
  warning: false
