project:
  type: website
  output-dir: ../_site/pt

website:
  page-navigation: true
  back-to-top-navigation: true
  image: unifal-logo.png
  reader-mode: true
  google-analytics: "G-S1L73VGCG5"
  title: ""
  favicon: avatar.png

  sidebar:
    contents:
      - section: "JSPlotly & GSPlotly - simulação interativa por IA"
        contents:
          - text: "JSPlotly - simulação por gráficos em JavaScript"
            href: nivel/superior/jsplotly/jsplotly_geral.qmd
          - text: "GSPlotly - gerador de códigos por IA para JSPlotly"
            href: nivel/superior/jsplotly/gsplotly.qmd
          - text: "Simulações em Bioquímico-física"
            href: nivel/superior/jsplotly/jsptl_bioq.qmd
          - text: "Simulações na Escola"
            href: nivel/basico/jsplotly/jsplotly_bas.qmd
          
            
      - section: "Jmol - Moléculas em 3D"
        contents:
          - text: "Modelos atômicos em Bioquímica"
            href: nivel/superior/jmol/index_jmol.qmd
          - text: "Moléculas 3D na Escola"
            href: nivel/basico/Curso/index_jmol_bas.qmd
          - text: "Jardim de Moléculas"
            href: nivel/basico/Jardim/index_Jardim.qmd

      - section: "R - cálculos e visualizações"
        contents:
          - text: "Cálculos e gráficos em Bioquímico-física"
            href: nivel/superior/r/index_r.qmd
          - text: "scriptRplot: gráficos elegantes com ggplot2"
            href: nivel/superior/ScriptRplot/scriptrplot.qmd
          - text: "R & RStudio na Escola"
            href: nivel/basico/Curso/index_r_bas.qmd
          - text: "Gráficos e mapas interativos na Escola"
            href:  nivel/basico/R/index_OIER.qmd


      - section: "Sisma - diagramas dinâmicos"
        contents:
          - text: "Fluxos dinâmicos em Bioquímica"
            href: nivel/superior/sisma/index_sisma.qmd
          - text: "Diagramas interativos na Escola"
            href: "#"

  navbar:
    search: true
    logo: logo-bioquanti.png

    left:
    
      - text: "Sobre"
        id: sup-menu
        href: index.html
      - text: "Ensino Reprodutível"
        id: bas-menu
        href: erre.qmd
        # menu: 
        #   - text: "ER"
        #     href: erre.qmd
        #   - text: "Características de ER"
        #     href: "#"
         
      # - text: "Ferramentas"
      #   id: sup-menu
      #   href: ferramentas.qmd
        # menu: 
        #   - text: "Possibilides"
        #     href: "#"
        #   - text: "Objetos"
        #     href: "#"
            
      # - text: "Ensino Básico"
      #   id: bas-menu
      #   # menu: 
      #   #   - text: "Possibilidades"
      #   #     href: "#"
      #   #   - text: "Exemplos"
      #   #     href: "#"

      - text: "Produção"
        href: producao.qmd

      - text: "Contato"
        href: contato.qmd
         
    right:
      - text: "EN"
        href: ../en/index.html


format:
  html:
    theme: 
      light: flatly
    css: styles.css
    code-overflow: wrap

execute:
  cache: true
  message: false
  warning: false
