project:
  type: website
  output-dir: ../_site/pt

website:
  page-navigation: true
  back-to-top-navigation: true
  image: unifal-logo.png
  reader-mode: true
  google-analytics: "G-S1L73VGCG5"
  title: ""
  favicon: avatar.png

  sidebar:
    contents:
      - section: "JSPlotly & GSPlotly - simulação interativa e IA"
        contents:
          - text: "Bioquímica"
            href: "#"
          - text: "Ensino Básico"
            href: "#"
            
      - section: "Jmol - Moléculas em 3D"
        contents:
          - text: "Bioquímica"
            href: nivel/superior/jmol/index_jmol.qmd
          - text: "Jmol na Escola"
            href: nivel/basico/Curso/index_jmol_bas.qmd
          - text: "Jardim de Moléculas"
            href: nivel/basico/Jardim/index_Jardim.qmd

      - section: "R - cálculos e visualizações"
        contents:
          - text: "Bioquímica"
            href: nivel/superior/r/index_r.qmd
          - text: "R na Escola"
            href: nivel/basico/Curso/index_r_bas.qmd
          - text: "Gráficos e mapas interativos na Escola"
            href:  nivel/basico/R/index_OIER.qmd
          - text: "scriptRplot: gráficos elegantes"
            href: "#"

      - section: "Sisma - fluxos dinâmicos"
        contents:
          - text: "Bioquímica"
            href: nivel/superior/sisma/index_sisma.qmd
          - text: "Ensino Básico"
            href: "#"

  navbar:
    search: true
    logo: logo-bioquanti.png

    left:
    
      - text: "Sobre"
        id: sup-menu
        href: index.qmd
      - text: "Ensino Reprodutível"
        id: bas-menu
        # menu: 
        #   - text: "ER"
        #     href: erre.qmd
        #   - text: "Características de ER"
        #     href: "#"
         
      - text: "Bioquímica"
        id: sup-menu
        # menu: 
        #   - text: "Possibilides"
        #     href: "#"
        #   - text: "Objetos"
        #     href: "#"
            
      - text: "Ensino Básico"
        id: bas-menu
        # menu: 
        #   - text: "Possibilidades"
        #     href: "#"
        #   - text: "Exemplos"
        #     href: "#"

      - text: "Publicações"
        href: producao.qmd

      - text: "Contato"
        href: contato.qmd

    right:
      - text: "EN"
        href: ../en/index.qmd

format:
  html:
    theme: 
      light: flatly
    css: styles.css
    code-overflow: wrap

execute:
  cache: true
  message: false
  warning: false
