---
title: ""
toc: true
number-sections: true
lang: pt
---

## Livro

- Schneedorf, J.M. [Vivificando Conteúdos Para o Ensino Básico: Moléculas, Gráficos, e Mapas Interativos](https://www.pimentacultural.com/livro/vivificando-conteudos/). Ed. Pimenta Cultural, 132p., 2025. ISBN 978-85-7221-397-4. 

- Schneedorf, J.M. Códigos Para Conteúdos: documentos dinâmicos para
pesquisa e ensino com R & RStudio. Editora UNIFAL-MG, Alfenas, 342p. (in press).

- Schneedorf, J.M., Rodrigues, K.L. [Bioquímica básica, de gente, de bicho, e de planta](http://dx.doi.org/10.13140/RG.2.2.32623.55208). 353p., 2024. ISBN: 978-65-00-90366-9.

- Schneedorf, J.M. [Bioquímica Quantitativa](http://dx.doi.org/10.13140/RG.2.2.36090.40644) & R. 152p., 2022. ISBN: 978-65-00-52125-2. .

- Schneedorf, J.M. [SISMA - Visualização Dinâmica em Catálise & Metabolismo](http://dx.doi.org/10.13140/RG.2.2.25027.92964). 95p., 2022. ISBN: 978-65-00-52124-5.

- Schneedorf, J.M. [Bioquímica Estrutural: guiada por Jmol](http://dx.doi.org/10.13140/RG.2.2.29268.10882). 140p., 2019. ISBN 978-85-63-47342-4. Unifal-MG.


## Capítulo

- Oliveira, G. A. V. ; Lemes, N. H. T. ; Sindra, L. V. ; Schneedorf, J.M. . [Binding of Molecules Followed by Electroanalytical Techniques](https://link.springer.com/chapter/10.1007/978-1-0716-4294-8_12). In: Ana Clarissa dos Santos Pires; Luis Henrique Mendes da Silva. (Org.). Methods and Protocols in Food Science - Characterization of Molecular Interactions. 1ed.New York: Springer Nature, 2025, v. 13, p. 1-12.

- Ferreira, M. P. ; Galhardo, B. R. ; Lemes, N. H. T. ; Coelho, Y. L. ; Schneedorf, J.M. ; Sindra, L. V. [Application of Quartz Crystal Microbalance to Study Intermolecular Interactions](https://link.springer.com/chapter/10.1007/978-1-0716-4294-8_14). In: Ana Clarissa dos Santos Pires; Luis Henrique Mendes da Silva. (Org.). Methods and Protocols in Food Science - Characterization of Molecular Interactions. 1ed.New York: Springer Nature, 2025, v. 13, p. 29-38.

- Andrade, R. J. ; Lemes, N. H. T. ; Sindra, L. V. ; Schneedorf, J.M. . [Difference Spectra Absorption Spectrophotometry Applied to Molecular Interactions](https://link.springer.com/chapter/10.1007/978-1-0716-4294-8_12). In: Ana Clarissa dos Santos Pires; Luis Henrique Mendes da Silva. (Org.). Methods and Protocols in Food Science - Characterization of Molecular Interactions. 1ed.New York: Springer Nature, 2025, v. 13, p. 14-28. 

- Schneedorf, J.M. Um aplicativo para gráficos interativos e dinâmicos para navegadores HTML, e GPT personalizado para seu códigos. In: Sumariva, G. Robótica, Inovação e Educação: conexões para o futuro. V & V Editora, Santo André (SP), 2025 (in press).

<!-- - Schneedorf, J.M. JSPlotly: um aplicativo aberto para gráficos interativos e dinâmicos no ensino e -->
<!-- aprendizagem de Ciências. In: Gerolin, E., Crisafulli, U. Papo de Professores: desafios, inovações e práticas no ensino de Ciências. V & V Editora, Santo André (SP), 2025 (in press). -->

- Schneedorf, J.M. [JSPlotly - um aplicativo prático e portável para simulações gráficas interativas ao ensino reprodutível](https://www.pimentacultural.com/livro/recursos-educacionais/). In: Recursos Educacionais Abertos na UNIFAL-MG. Org: Mafra, L.A.S; Silva, L.E; Schneedorf, J.M. Ed. Pimenta Cultural. 2025. DOI: 10.31560/pimentacultural/978-85-7221-396-7.4.

- Schneedorf, J.M. [Bioquanti: um website para ensino reprodutível de códigos para conteúdos](https://www.pimentacultural.com/livro/unifal-interativa/). In: Unifal Interativa: Projetos de Educação Digital da Universidade Federal de Alfenas. Org: Mafra, L.A.S; Silva, L.E; Schneedorf, J.M. Ed. Pimenta Cultural. 2025. ISBN: 978-85-7221-395-0.

- Schneedorf, J.M. [ScriptRplot - um script de R para produção de gráficos elegantes com ggplot2](https://www.pimentacultural.com/livro/recursos-educacionais/). In: Recursos Educacionais Abertos na UNIFAL-MG. Org: Mafra, L.A.S; Silva, L.E; Schneedorf, J.M. Ed. Pimenta Cultural. 2025. DOI: 10.31560/pimentacultural/978-85-7221-396-7.3.

- Schneedorf, J.M. R e RStudio: uma plataforma para implementação de ensino reprodutível. In: Aprendizagem Ativa: da Educação Básica ao Ensino Superior. Org: Sindiany Suelen Caduda dos Santos, Débora Moreira de Oliveira. V & V Editora, Santo André (SP), 2025 (no prelo).

- Schneedorf, J.M., Nogueira, M.G.F., Mafra, L.A.S., Silva, E.L. Jardim de Moléculas: um catálogo virtual para ensino reprodutível de modelos atômicos ao ensino básico. In: Aprendizagem Ativa: da Educação Básica ao Ensino Superior. Org: Sindiany Suelen Caduda dos Santos, Débora Moreira de Oliveira. V & V Editora, Santo André (SP), 2025 (no prelo).

- Schneedorf, J.M. Pacotes do R para criação de objetos de aprendizagem ativos em ensino reprodutível. In: Aprendizagem Ativa: da Educação Básica ao Ensino Superior. Org: Sindiany Suelen Caduda dos Santos, Débora Moreira de Oliveira. V & V Editora, Santo André (SP), 2025 (no prelo).

- Schneedorf, J.M., Hornink, G.G. Desenvolvimento De Competências Digitais No Ensino Superior A Partir De Aprendizagem Baseada Em Projetos Com R e Rstudio.In: Aprendizagem Ativa: da Educação Básica ao Ensino Superior. Org: Sindiany Suelen Caduda dos Santos, Débora Moreira de Oliveira. V & V Editora, Santo André (SP), 2025 (no prelo).

- Silva, L.E., Alves, L.P.O., Vespucio, N.M.B., Schneedorf, J.M. Sisma, um aplicativo para simulação de diagramas dinâmicos para o ensino-aprendizagem e sua adaptação para ambiente online (SismaWeb). In: Aprendizagem Ativa: da Educação Básica ao Ensino Superior. Org: Sindiany Suelen Caduda dos Santos, Débora Moreira de Oliveira. V & V Editora, Santo André (SP), 2025 (no prelo).

- Schneedorf, J.M. Documentos Dinâmicos em Ensino Reprodutível com R & Rstudio. In: Tecnologias Emergentes em Educação. V & V Editora, Santo André (SP), 2025 (no prelo).

- Schneedorf, J.M. Ensino reprodutível como metodologia ativa em ensino-aprendizagem. In: Tecnologias Emergentes em Educação. V & V Editora, Santo André (SP), 2025 (no prelo).

- Schneedorf, J.M., Rodrigues, B.S., Hornink, G.G. OIER - Objetos Interativos em Ensino Reprodutível: uma abordagem com R. In: Tecnologias Emergentes em Educação. V & V Editora, Santo André (SP), 2025 (no prelo).

- Schneedorf, J.M. Literacia de prompts na produção de objetos didáticos interativos em ensino reprodutível para R & RStudio. In:  Reflexões e Relatos sobre Inteligência Artificial. Org: Carolei, P., Rosalen, M. V & V Editora, Santo André (SP), 2025 (no prelo).

- Schneedorf, J.M. Avaliação de assistentes de IA na criação de códigos de R para objetos interativos em ensino reprodutível. In:  Reflexões e Relatos sobre Inteligência Artificial. Org: Carolei, P., Rosalen, M. V & V Editora, Santo André (SP), 2025 (no prelo).

- Silva, L.E., Lima, D.C., Isgrignero, I., França, J.G., Lage, R.M., Schneedorf, J.M., Mafra, L.A.S. Tales Ludos: aprimorando a experiência dos usuários 
para a elaboração de jogos educacionais online.  In: Tecnologias Emergentes em Educação. V & V Editora, Santo André (SP), 2025 (no prelo).

- [Tecnologias digitais e a coprodução do bem público: interatividade e participação na construção de Recursos Educacionais Abertos](https://www.vveditora.com/educacao/978-65-6063-082-6). Mafra, L.A.S, Gozzi, W.P., Santos, A.G.S., Silva, L.E., Schneedorf, J.M. In: Abordagens Multidisciplinares na cultura digital. Org: Costa, C.T.O.P. V & V Editora, Santo André (SP), 2025.


## Artigo

- Schneedorf, J.M. JSPlotly: um aplicativo para gráficos interativos em Bioquímica para visualizadores HTML. Revista de Ensino de Bioquímica. 2025 (no prelo).

- Schneedorf, J.M. Livros vivos: uma proposta de ensino reprodutível com R & Rstudio. Revista Eletrônica Casa de Makunaima. 2025 (no prelo).

- Schneedorf, J.M. Bioquanti, um website interativo para ensino-aprendizagem em Bioquímica." Revista de Ensino de Bioquímica 21.1 (2023): 110-124.

- Oliveira, Schneedorf. A Simple, Fast and Portable Method for Electrochemical Detection of Adenine Released by Ricin Enzymatic Activity. v. 13, p. 238. Toxins. 2021.

- Oliveira, G. A. V.; Schneedorf, J. M. An Electrochemical Approach to Follow and Evaluate the Kinetic Catalysis of Ricin on hsDNA. v. 11(5), p. 405. Life. 2021.

- Silveira, G., Neto, S.A., Schneedorf, J.M. Development, characterization and application of a low-cost single chamber microbial fuel cell based on hydraulic couplers. Energy 208 (2020): 118395.

- Andrade, R. J., Schneedorf, J.M. Interação Ligante-Proteína Monitorada por Espectrofotometria. Revista de Ensino de Bioquímica 17 (2019): 1-12.

- Oliveira, G.A.V., Schnnedorf, J.M. Monitoramento de atividade de α-amilase com multímetro digital comercial. Revista de Ensino de Bioquímica 17 (2019): 94-103.

- Silveira, G. Schneedorf, J.M. Evaluation of kefir as a new anodic biocatalyst consortium for microbial fuel cell. Applied Biochemistry and Biotechnology 185 (2018): 1118-1131.

- Silveira, G. Ikegaki, M., Schneedorf, J.M. A low-cost yeast-based biofuel cell: an educational green approach. Green Chemistry Letters and Reviews 10.1 (2017): 32-41.

- Silveira, G. Ikegaki, M., Schneedorf, J.M. Biocélula a combustível de baixo custo para investigação do metabolismo energético. Revista de Ensino de Bioquímica 15 (2017): 155-161.

## Patente

- Oliveira, G.A.V., Schneedorf, J.M. Método para detecção de ricina e caracterização de sua atividade enzimática em tempo real por eletroquímica. INPI, registro no. BR1020200206532. 2020.

- Cavalcanti, M. H. S.; Virtuoso, L. S.; Mendes, A. A.; Schneedorf, J.M. Processo para imobilização de enzima em suporte nanoparticulado magnético. INPI, registro no. BR10202002016.


## Software

- Macedo, J.A.; Matos, N.; Paula, M.M.V.; Silva, L.E.; Schneedorf, J.M. SISMA: Sistema de Mapas Autocatalíticos. Programa de Computador. Registro INPI no. 08869-3 (19/05/2008).

- Schneedorf, J.M. JSPlotly & GSPlotly: aplicativo e gerador de códigos por IA para gráficos interativos em visualizador HTML(2025). Depositado no portal eduCAPES, registro no. 972869.

## Website

- Schneedorf, J.M. Bioquanti (2022). Depositado no portal eduCAPES, registro no. 748598.

## GPT personalizado

- Schneedorf, J.M. GSPlotly: gerador de scripts interativos para JSPlotly. OpenAI GPT customizado. Disponível em: https://chat.openai.com/g/g-6819fbb8d2d08191bf7d50a3dbeadb0d-gsplotly. Acesso em: 11 maio 2025.




