---
title: "Mebolismo do Etanol"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       O álcool possui, no organismo animal, ação direta e indireta. A direta envolve sua combinação com enzimas, coenzimas, vitaminas e outros constituintes biológicos, e a indireta, sua ação danosa ao tecido hepático, centro do metabolismo de proteínas, gorduras e açúcares, e renal, centro de excreção de metabólitos indesejáveis ao organismo. A principal ação direta do álcool é sua degradação enzimática pelo organismo, que faz com que ocorra a produção de uma coenzima chamada NADH, cujo excesso sinaliza ao organismo que ele não precisa mais de energia. Quando isso ocorre, seus estoques de açúcares e de gordura, que normalmente são quebrados para formar ATP, ficam parados. 

|       Isso leva a um enfraquecimento do organismo e queda nos teores de glicose sanguínea, o que pode resultar em sintomas de hipoglicemia e de fome. O álcool é bastante calórico, quase 2 vezes mais do que os açúcares, o que faz com que o alcoólatra, enquanto esteja bebendo, não sinta fome. Isto pode levar a uma mal nutrição do indivíduo que, combinada com o álcool, acaba em quadros severos de intoxicação alcoólica. Isso acontece porque, aliado a uma dieta deficiente, o álcool destrói quase todas as vitaminas, aumenta a perda renal de K, P, e Na, e reduz a absorção de carboidratos e de aminoácidos. 

|       Existem diversos quadros patológicos severos, como a doença de *Wernicke-Korsakoff* e a síndrome alcoólica fetal, que resultam do alcoolismo crônico, isto sem falar da cirrose hepática e pancreática. A dor de cabeça e a ressaca que se experimentam após uma noitada etílica são também resultados do metabolismo de enzimas sobre o álcool, visando sua eliminação pelo organismo. Não obstante, a sensasão agradável que acomete o indivíduo após 2 ou 3 copos de bebida alcoólica, tem a ver com a liberação de uns peptídios cerebrais relacionados ao bem-estar do consumidor. 

|       O problema é que essa sensação de leveza passa a acontecer sempre com doses mais elevadas de álcool, levando o indivíduo à dependência deste. Paralelamente aos efeitos perigosos do consumo exagerado do álcool, existem alguns poucos benefícios, mas só para aqueles considerados consumidores moderados de álcool. Estes consomem até duas tulipas diárias de cerveja ou uma única dose de vinho ou uísque, não sendo considerados bebedores moderados os que se encharcam a noite toda da marvada, mesmo que duas ou três vezes por semana. Nos chamados consumidores moderados, ocorre um aumento do bom colesterol (HDL), uma proteína recheada de gordura, que tira o colesterol da corrente sanguínea para degradá-lo no fígado. Outros efeitos benéficos estão relacionados mais à composição diferencial das bebidas do que ao próprio álcool. Assim, já se sabe que o vinho ajuda a reduzir os níveis de colesterol no sangue, mas esse efeito é antes de tudo produzido por substâncias chamadas flavonóides, também encontradas num simples suco de frutas.

## Detalhes

|       A oxidação do etanol hepático altera a relação NAD+/NADH. O fígado é primariamente responsável pelas duas primeiras etapas do catabolismo do etanol: a conversão de etanol a acetaldeído, e a conversão de acetaldeído em acetato.

CH3COOH + NAD+ --> CH3CHO + NADH + H+
CH3CHO + NAD+ --> CH3COO- + NADH + H+

|       A primeira etapa, catalisada pela álcool desidrogenase no citosol, gera NADH. A álcool desidrogenase é uma enzima induzível, tendo seus níveis aumentados em resposta ao consumo do álcool. A primeira reação ocorre muito rapidamente nos alcoólatras, de forma que os efeitos da intoxicação por álcool são, na verdade, reduzidos (isto é, menos intoxicação por dose). Os alcoólatras toleram níveis de álcool no sangue que seriam letais para abstêmios. O acetaldeído resultante pode causar dores de cabeça, náuseas e ressaca. Os homens parecem ter um nível mais alto de álcool desidrogenase nas células das vilosidades intestinais, o que poderia explicar por que, mesmo depois dos ajustes pela massa corporal maior, a maioria dos homens pode beber muito mais álcool do que as mulheres, sem sentir seus efeitos. 

|       A segunda etapa, catalisada pela aldeído desidrogenase, também gera NADH, mas ocorre principalmente no espaço da matriz mitocondrial. Japoneses e chineses possuem uma forma menos ativa da adeído desidrogenase, o que produz sintomas de vasodilatação e taquicardia nesses indivíduos. O fígado utiliza NADH gerado por essas reações pela única via disponível, a cadeia de transporte de elétrons mitocondrial. Ingestão de quantidades, mesmo moderadas, de etanol gera muito NADH. Muitas enzimas, por exemplo, várias envolvidas na gliconeogênese e na oxidação de ácidos graxos, são sensíveis à inibição por NADH. Dessa forma, durante o metabolismo do álcool, essas vias estão inibidas, e hipoglicemia, devido ao jejum e ao acúmulo de triacilgliceróis hepáticos (fígado gordo) são consequências da ingestão do álcool. A droga dissulfiran, inibidora da aldeído desidrogenase, parece surtir algum efeito no tratamento do alcoolismo. 

|       Lactato pode acumular-se como consequência da inibição da lactato-gliconeogênese, e pode resultar em acidose metabólica. A abundância de NADH favorece a redução de piruvato e oxalacetato, ambos intermediários da gliconeogênese, em lactato e malato, respectivamente. Assim, o consumo do álcool em pessoas subnutridas ou após exercício extenuante pode causar hipoglicemia pela inibição da gliconeogênese (excesso de NADH), excesso de lactato, e exaustão de estoques glicogênicos. Neste sentido, crianças são muito dependentes da gliconeogênese durante o jejum, fazendo com que ingestão acidental de álcool numa criança possa causar hipoglicemia severa. A hipoglicemia resultante da injesta alcoólica pode produzir muitos dos comportamentos associados à intoxicação alcoólica, como agitação, julgamento diminuído e agressividade.


|       As mitocôndrias hepáticas têm uma capacidade limitada de oxidar acetato a CO2, porque a ativação do acetato a acetil CoA requer GTP, um produto da reação da succinil CoA sintetase. O ciclo de Krebs e, portanto, a síntese de GTP são inibidos por níveis elevados de NADH durante a oxidação do etanol. Grande parte do acetato produzido a partir de etanol escapa do fígado para o sangue. Virtualmente todas as outras células com mitocôndrias podem oxidá-lo a CO2, pela via do ciclo de Krebs. Acetaldeído, o intermediário na formação de acetato a partir de etanol, também pode escapar do fígado. Acetaldeído é um composto reativo que forma, rapidamente, ligações covalentes com grupos funcionais de compostos biológicos importantes. Tem sido demonstrada a formação de aductos de acetaldeído com proteínas nos tecidos e no sangue de animais e humanos que bebem álcool. Tais aductos podem ser marcadores do hábito de beber anterior de um indivíduo. Em doenças graves do fígado provocadas pela injesta crônica de álcool, como na cirrose hepática, ocorre uma anomalia na fluidez da membrana celular dos eritrócitos, com aumento de 25-65% do teor de colesterol da membrana, reduzindo a fluidez vital para o funcionamento destes. 

|       Alterações de fluidez de membrana em tecido nervoso, juntamente com alterações em receptores de membrana e canais iônicos, estão associadas também à intoxicação pelo álcool. Do ponto de vista nutricional, alcoólatras crônicos possuem alto risco de deficiências alimentares de ordem vitamínica, pois o alcoolismo crônico, além de reduzir a absorção de grande número delas, leva à doença hepática severa, o que aniquila o maior produtor e reservatório de vitaminas no organismo. As deficiências nutricionais do alcoolismo estão normalmente associadas à dieta deficiente, e podem afetar o metabolismo virtual de todas as vitaminas hidrossolúveis. Assim, o consumo crônico do álcool elimina tiamina e piridoxina (sintomas neurológicos). 30% dos alcoólatras hospitalizados apresentam anemia sideroblástica, característica da deficiência de piridoxina, também associada a neuropatia periférica. 40% dos alcoólatras hospitalizados possuem eritropoiese megaloblástica, causada por deficiência de folato. 

|       Em torno de 1-3% das doenças neurológicas associadas ao consumo do álcool envolvem a grave síndrome de Wernicke-Korsakoff, uma deficiência de tiamina, que leva a sintomas de distúrbios mentais, ataxia (caminhada insegura), incoordenação motora (musculatura esquelética e movimento dos olhos), e insuficiência cardíaca congestiva. Deficiência de riboflavina, que também acomete o alcoólatra, se evidencia no aparecimento de glossite e dermatite escamosa. 

|       Exaustão de estoques de vitamina A no organismo, juntamente com deficiência na ativação da vitamina D (osteoporose) estão também relacionadas à injesta de álcool. O alcoólatra experimenta ainda deficiência de minerais, tais como cálcio, zinco e magnésio, devido à injestão dietética deficiente e perda urinária aumentada. Ironicamente, também experimenta um excesso nos teores de ferro, visto que o etanol parece aumentar sua absorção, além dos níveis altos de ferro já presentes na maioria das bebidas alcoólicas. O uso prolongado desta está associado à formação de neoplasmas. Assim, a cerveja possui alto índice de câncer do reto, ao passo que as bebidas destiladas estão melhor relacionadas aos tumores de laringe e esôfago.

|       O álcool é teratogênico. A síndrome alcoólica fetal é particularmente preocupante para as mulheres. Não existe nível seguro de consumo de álcool durante a gravidez. A síndrome alcoólica fetal ocorre em cinco de cada mil nascimentos. Os sintomas incluem crescimento reduzido, disfunção do sistema nervoso central, e um aspecto facial característico. O nível de acetaldeído no sangue de uma gestante tem valor diagnóstico para se detectar a síndrome alcoólica fetal. O acetaldeído é transferido da placenta e acumula-se no fígado do feto.
Existe um interesse crescente a respeito dos efeitos do álcool sobre neurotransmissores psicoativos, como adrenalina e serotonina, e sobre a produção de endorfinas e de encefalinas. Esses últimos são pequenos peptídeos que fazem parte do sistema analgésico opióide endógeno do cérebro. 

|       A hipoglicemia mediada pelo consumo crônico do álcool resulta na mobilização das reservas corporais de gordura. Complementarmente, se por um lado o NADH em excesso inibe o catabolismo de ácidos graxos, o acetato liberado da oxidação do álcool eleva sua síntese hepática. Desta forma, o alcoolista apresenta níveis aumentados de triglicerídeos plasmáticos, colesterol total, quilomicra e VLDL (consumo superior a 20 mg/dL/semana). Esse catabolismo lipídico é ainda estimulado pelo aumento de cortisol e epinefrina que o álcool promove, induzindo à produção de catecolaminas.

### Marcadores do alcoolismo.

|       Não existe um indexador bioquímico preciso para consumo crônico do álcool. No entanto, algumas substâncias podem ser monitoradas no sangue para o acompanhamento do estado funcional dos tecidos sob a intoxicação persistente. 


|       Acetaldeído é um composto reativo que forma, rapidamente, ligações covalentes com grupos funcionais de compostos biológicos importantes. Tem sido demonstrada a formação de aductos de acetaldeído com proteínas nos tecidos e no sangue de animais e humanos que bebem álcool. Tais aductos podem ser marcadores do hábito de beber anterior de um indivíduo. 


|       Um marcador comumente utilizado no monitoramento do alcoolista constitui a serino protease gama-glutamil transpeptidase (GGT). Essa enzima se apresenta elevada no soro de pacientes com doenças hepáticas variadas. Porém, no caso em questão, seus níveis se alteram em função do consumo de álcool em poucos dias, razão pela qual o exame diagnóstico é realizado sob abstinência de 72 h. Quando a GGT se encontra de 8 a 10 vezes acima de seu valor de referência, ou permanece elevada durante 2 meses, pode-se deduzir o quadro crônico da droga. 

|       Ainda no acompanhamento do paciente, percebe-se uma redução nos teores de albumina, e elevação de CK (creatina quinase), imunoglobulina G, ácido úrico, triglicérides, transferrina deficiente em carboidrato (90 % dos casos) e hemoglobina total (hemólise aguda).

|       Em indivíduos não-alcoólatras, o etanol inibe a síntese da encefalina, uma vez que o efeito agradável do álcool substitui a necessidade das encefalinas. Parte do mal-estar de uma ressaca provém da falta de encefalinas, e permanece até que os níveis desses compostos retornem ao normal. Alguns estudos indicam que, nos alcoólatras natos, o etanol pode estimular a produção de encefalina, com um efeito sinergístico. O problema é que o organismo se acostuma com os altos níveis, e tais níveis transformam-se em um novo estado “normal”. 

|       Nesse caso, passa a ser necessário um suprimento constante de álcool para manter esses níveis de sensação agradáveis. O estabelecimento de novos níveis altos produz tolerância, um dos marcadores do vício, e esse efeito deve explicar também muitos dos sintomas de abstinência associados com o alcoolismo.


|      *Intoxicações por metanol ou pelo anticongelante etilenoglicol* podem ser tratadas com etanol. O metanol pode também ser metabolizado pela álcool desidrogenase em formaldeído e ácido fórmico, produtos altamente tóxicos. Pequenas quantidades de formaldeído podem causar cegueira e morte. A inibição competitiva pelo etanol faz com que grande parte do metanol seja excretado pela urina, antes de ser convertido a formaldeído. A álcool desidrogenase hepática também catalisa a conversão de etilenoglicol em glioxilato e oxilato, produtos de alta toxicidade. Sendo assim, o etanol pode ser utilizado em uma emergência para o tratamento destas intoxicações. O consumo moderado do álcool diminui o risco de doença arterial coronária. 

|       Existe uma correlação positiva entre o consumo de álcool e a concentração de HDL, que responde por grande parte do efeito protetor do álcool contra a doença cardíaca. Entretanto, devido aos riscos potenciais do álcool, os profissionais da saúde relutam em recomendar quantidades maiores de consumo de álcool aos abstêmios ou bebedores ocasionais.







