---
title: "Fontes Proteicas na Alimentação"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       Fontes dietéticas protéicas podem ser de origem animal, como leite e derivados, ovos e carne, ou vegetal, como grãos, cereais e leguminosas. Além dessas, fontes não convencionais de proteínas podem ser constituidas por microrganismos, folhas, sementes de oleaginosas, pescados, sangue e penas. A seguir são descritas as características principais de cada uma, seus aspectos nutricionais e fatores anti-nutricionais correlatos.


## Detalhes

### Leite e derivados

|       Propriedades bioquímicas do leite encontram-se melhor explicitadas em capítulo anterior. Existe alguma diferença na composição bioquímica do leite e de sua ejeção primeva, o colostro, esse último apresentando menor teor de lactose e maior de proteína, em relação ao primeiro, diferença essa que se normaliza em poucos dias. Entre as espécies, contudo, a variação de proteína, lactose e gordura é mais proeminente. 

|       Assim, grandes teores de lipídeos são encontrados no leite de veada e de baleia, e menores em vacas e ser humano. Lactose se encontra mais pronunciada no leite humano e de elefanta, sendo reduzida em veada, cadela e cabra. Proteínas, por sua vez, estão mais presentes em leite de baleia, coelha e veada, e menos em vaca, humano e cadela.
Das proteínas presentes no leite classificam-se as caseínas, proteínas do soro, de glóbulos de gordura e de membranas, além de várias enzimas. 

|       Das proteínas do leite de vaca (3,5 % em constituição), a caseína cumpre 2,9 % contra 0,6 % de proteínas do soro. A caseína não constitui uma proteína de peso molecular conhecido, e sim uma classe de mais de 20 proteínas capazes de formar micelas protéicas de peso e características físico-químicas variadas.  São quatro as classes principais, definidas como $\alpha$ (50 %), $\beta$ (33 %), $\kappa$ (15 %), e $\gamma$ (1 a 5%). 


|       A alfa-caseína apresenta ponto isoelétrico em 4,6, o que significa que, a este pH, ela sofre desnaturação, insolubilizando-se no leite e promovendo a formação de uma massa precipitada típica da formação dos fermentados lácteos. Além disso, é composta por 200 aminoácidos aproximadamente, possui um alto teor de prolina, 0,9 % de fósforo (fosfoproteínas), e hidrofobicidade suficiente para a formação de micelas. 

|       A beta-caseína é formada por polímeros em rosário (modelo em roseta), com características similares à alfa-caseína. A capa-caseína, por sua vez, tem a propriedade de se combinar ao cálcio (sal de fosfato), permitindo uma interação entre a alfa e a beta-caseína, e gerando as micelas de caseína (de 60 a 600 kD, unidas por duas pontes dissulfeto por mol de proteína). A capa-caseína pode se combinar alternativamente a N-acetilglicosamina e ácido neuramínico, situação que impede sua interação com fosfato e cálcio. Como alvo principal da protease renina, a capa-caseína do leite tratado com essa não coagula, uma vez que a renina permite uma estabilização estrutural das micelas. 

|       Finalmente, a gama-caseína compõe-se de uma conversão de beta para gama, possuindo 180 aminoácidos em sua estrutura. Em conjunto, a molécula / micela de caseína exibe um peso molecular aproximado de 10 milhões de quilodáltons, o equivalente a mais de quatrocentas moléculas de tripsina, principal enzima proteolítica animal, ou a uma molécula carboidratada de reserva, o polímero de glicogênio. Com relação à estrutura primária, a caseína apresenta teores decrescentes de glutamato, prolina, leucina e valina.


|       As proteínas do soro são as que restam após um tratamento ácido do leite por 30 min a temperatura superior a 60$^{o}$C, ou, melhor traduzindo, as que representam o teor protéico do leite desnatado desprovido de caseína (tratamento por renina, liberando peptídeos e aminoácidos). Mais de dois terços são constituidas por $\alpha$-lactalbuminas (importância na síntese de lactose pelas glândulas mamárias) e $\alpha$-lactoglubinas (polimérica), e o restante por soralbumina (se bovina, BSA, 17 pontes dissulfeto), imunoglobulinas (IgG, IgA, IgM), proteases e peptona, lactoferrina (interage com duas moléculas de ferro por proteína, inibindo metabolismo microbiano), transferrina (grande presença no colostro, bacteriostática) e algumas enzimas. 


|       Existem mais de 50 enzimas presentes no leite, das quais seguem alguns exemplos principais. A fosfatase alcalina é considerada um marcador da pasteurização obtida a 71,5$^{o}$C por 16 segundos, sendo distribuida em glóbulos no leite. A lipase, capaz de se combinar a caseína, figura parcialmente responsável pela atividade metabólica originária do ranço e sabor amargo. Proteinases, tais como a caseinase, podem ser empregadas como indicadores da textura do queijo e do tratamento de cura, uma vez que só se desnaturam em temperaturas acima de 80 0C. Além dessas são também encontradas peroxidases (efeito bacteriostático), oxidases de xantina (10 % da massa protéica de membrana de glóbulos de gordura, e formadora de urato), e tioxidases (característica do sabor cozido do leite, devido a ruptura de pontes dissulfeto). 


|       As proteínas do leite podem ser industrialmente aplicadas como espumantes, emulsificantes, e geleificantes, no setor alimentício. Complementarmente, também são empregadas como colas adesivas, no clareamento do papel, na produção de tintas e na indústria têxtil. 
	

### Ovos

|       Ovos possuem teores protéicos e lipídicos distintos na cutícula (86 % de proteína), casca (menos de 2 %, com 98 % de sais de cálcio), membrana (90 % de lipídeos), clara, membrana vitelina (87 % de lipídeos), e gema. A grosso modo, contudo, proteínas e lipídeos são melhor encontrados na gema, ao passo que carboidratos e água, na clara. 


|       A clara é composta por ovomucina e mais de 50 proteínas globulares coloidais, como a ovalbumina (54 %), formada por aminoácidos hidrofóbicos em sua metade, além de manose e N-acetilglicosamina. Outras proteínas constituem a ovotransferrina (12 %, 1 % de hexose, ligadora de ferro, bacteriostática), o ovomucóide (11 %, 25 % de carboidratos), ovoinibidor (2 %, considerado um fator antinutricional por se ligar a serino proteases), e ovalbumina S (marcador da qualidade do ovo, já que permanece em mais de 80 % íntegra após 6 meses de estocagem a frio). 

|       Além dessas, placalbumina (marcador da presença de *Bacillus subtilis*), lisozima (4 %, polissacaridase antimicrobiana), avidina (menos de 1 %, fator antinutricional ligador irreversível de biotina), e ovomucina (4 %). A ovomucina, responsável por 50 % do ácido siálico da clara, além de galactose e galactosamina,  merece registro especial, uma vez que sua combinação a lisozima permite a viscosidade natural da clara, a qual é perdida com o tempo, elevação de pH ou temperatura (redução dos complexos, redução de ácido siálico, de carboidratos ou de solubilidade). 


|       A gema do ovo é composta por glicoproteinas, fosfoproteínas, e lipoproteínas. Fosfolipoproteínas carregam lipídeos neutros, lipovitelinas nitrogênio, enxofre e fósforo, livetinas são partícipes da defesa animal, e fosfovitinas, responsáveis por 70 % do teor de fosfato da gema (54 % de serina, 120 P/mol).  Sob o ponto de vista nutricional, o ovo comparece com um alto valor biológico de aminoácidos essenciais. Além disso, ovos são utilizados na indústria alimentícia como emulsificantes (gema, na produção de maionese), e espumantes (clara, retenção de ar). A pasteurização da clara ocorre a 60 0C por 3 minutos, ao passo que a gema, a 57 0C por 2 minutos. 

|       Ovos podem ser consumidos frescos, congelados ou desidratados, devendo-se contudo tomar o cuidado devido para a ingesta do alimento cru, já que o mesmo possui diversos fatores antinutriconais. Dentre esses, podem ser mencionados as proteínas ovomucóide e ovoinibidor (ligadoras de serino proteases), ovotransferrina (ligadora de ferro), e avidina (ligadora de vitamina B3, biotina).


### Carne

|       A proteína da carne encontra-se, via de regra, na musculatura da carcaça, mas podem ser computadas também a epitelial, conjuntiva e nervosa. Proteínas da carne são classificadas como sarcoplasmáticas (35 % das proteínas da musculatura, de 100 a 200 tipos diferentes), tais como mioglobina (superior em baleia e boi, inferior em suíno e frango), miofibrilares (55 %), tais como actina, miosina, troponina, tropomiosina, creatina quinase, e estromáticas (15 %), como colágeno (50 %) e elastina.


### Grãos

|       Considera-se neste grupo, basicamente, milho, arroz e trigo, como cereais, e feijão  e soja, como leguminosas. O trigo é rico em proteínas (12 %) e glutamato, mas pobre em lisina. Possui proteínas solúveis, como globulina e albumina, e elementos de reserva como o glúten, o qual confere propriedades de panificação devido ao alto número de pontes dissulfeto formadas durante a batedura, e em presença de brometo de potássio. 

|       O glúten, conjunto de glico e lipoproteínas, corresponde a 80 % do conteúdo protéico do trigo, sendo subdividido em duas classes. A gliadina, um misto polipeptídico com 80 % de estrutura terciária aleatória, possui grande número de aminoácidos básicos e ácidos, o que lhe confere alto teor de interações eletrostáticas. Um segundo conjunto, a glutenina, é composto por um polímero linear com grande número de pontes dissulfeto e de baixa solubilidade, responsável pela bola de glúten, e contido em 70 % da proteína de farinha de trigo. A separação do glúten pode ser efetivada em presença de ácido acético.


|       O arroz é rico em leucina, fenilalanina e valina, sendo pobre em metionina, triptofano e lisina. Pouca diferença existe entre o teor protéico do arroz polido (7 %) e o integral (8 %), a despeito desse último possuir maior nível de lisina. A composição protéica conta com 80 % de glutelina de alta insolubilidade, 10 % de globulina (pericarpo e embrião) e 5 % de albumina. Sob o ponto de vista nutricional, o conteúdo protéico de aveia e centeio são similares. 


|       O milho possui 13 % de proteína, dois terços localizados no endosperma, e composta por albumina, globulina, prolamina e zeína, essa última responsável por metade do total protéico. Devido a suas propriedades de insolubilidade, a zeína é aproveitada como fibra nas indústrias têxtil, farmacêutica e de alimentos, sendo nessa última utilizada como spray na fortificação de grãos. Com relação ao seu teor de aminoácidos, o milho é rico em leucina e valina, e pobre em cisteína, triptofano e lisina. 

|       O feijão, por sua vez, é rico em lisina, glutamato e aspartato, e pobre em triptofano,  metionina e cisteína, dotando a leguminosa de pouco enxofre em sua constituição, e reduzindo sua digestibilidade gastrintestinal. Mais de dois terços da proteína de feijão encontra-se nas sementes, e um terço nos grãos. O feijão possui pouca glutelina, sendo também desprovido de prolamina; no entanto, é rico em albumina e globulinas, como a globulina G, que confere alta resistividade à atividade tripsínica.  O feijão possui alguns fatores antinutricionais, como lectina a 5 %, glicoproteína que induz agregação eritrocitária (hemaglutinina), além de inibidores de proteases. 


|       A soja, último grão acima listado, apresenta pouco ou nenhum amido, sendo composta de óleo a 20 % e proteína a 40 %. A soja não possui gliadina e glutenina e, portanto, não panifica através das propriedades visco-elásticas dessas proteínas. Possui alto teor de globulinas antinutricionais, contudo, representadas por inibidores de proteases (Kunitz, Bowan-Birk), lipoxigenases (causam oxidação de ácidos graxos poliinsaturados a aldeídos e cetonas, resultando em sabor desagradável característico), amilases e lectinas, essas últimas inibidoras de crescimento celular. 

|       Os produtos industriais advindos da biotecnologia da soja envolvem a farinha integral (elevação térmica inibe os fatores protéicos antinutricionais), a farinha desengordurada (tratamento com hexano) e resíduo (torta de soja), grits de soja, e concentrado protéico (produzido a partir da farinha desengordurada, e retendo mais de 95 % de proteína pobre em metionina e lisina, através de tratamento por ácido e álcool em temperatura elevada).


### Fontes não-convencionais de proteína

|       Nesta classe entram as fontes de microrganismos, folhas, sementes de oleaginosas, pescado, sangue e penas. Fontes microbianas de bactérias, fungos, leveduras e algas são de baixo custo relativo e alta produtividade, frente às taxas de multiplicação celular desses organismos. Exemplificando, a produtividade protéica de leveduras é de cem mil vezes superior a de rebanho bovino. O teor protéico relativo de B. subtilis supera o do bovino, e é duas vez maior que do milho. 

|       As vantagens nutricionais do emprego de fontes microbianas inclui o alto teor de ácidos nucléicos, proteínas e vitaminas. As desvantagens abrangem o alto nível de moléculas nitrogenadas de ácidos nucléicos, convertidos metaboicamente em uréia e urato (relacionados a cálculos e gota), a baixa digestibilidade (metade da de caseína), e a toxicidade de alguns grupos (algas consumidas em excesso – 250 g/dia podem causar diarréia e cãibras musculares). Em rações animais, o emprego de fontes microbianas pode envolver de 5 a 15 % do total de proteínas.


|       Folhas são melhor utilizadas no preparo de rações, devido a sua baixa solubilidade e sabor desagradável (capim). O tratamento térmico empregado leva ao enegrecimento do alimento, devido à conversão de clorofila em feofilina e a reações de Maillard. Como vantagens a fonte foliar apresenta alto teor de lipídeos e de pigmentos, sendo ideal para frangos e suínos, além de alto valor protéico nutricional, similar à caseína. Adicionalmente o resíduo sólido auxilia na produção do fardo de alfafa.


|       Sementes de oleaginosas (soja, milho, arroz, amendoim, algodão, etc) variam no teor protéico. Exemplificando, o amendoim possui em torno de 30 % de proteína (baixos níveis de cisteína e metionina) e 50 % de óleo, ao passo que o algodão possui 25 % de proteína e 25 % de óleo. O algodão possui ainda o fator antinutricional gossipol, capaz de induzir reações de Maillard que resultam em baixa digestibilidade. 

|       Pescados constituem fontes protéicas superiores a de grãos, com valor nutricional de aminoácidos miofibrilares superior a de cartilagem, vísceras, escamas e pele (presença de queratina nas duas útlimas reduz biodisponibilidade). No entanto, sob tempo prolongado de armazenamento ou alta temperatura pode resultar em peroxidação de aminoácidos sulfurosos, resultando em sulfóxidos ácido cistéico (recomendando o uso de antioxidantes na farinha), além de desnaturação protéica, alterando coloração e palatabilidade. 


|       Sangue possui alto valor nutricional devido a seus teores de lisina e leucina (fibrinogênio, globulinas, albumina). Outra vantagem, de caráter estratégico, reside no fato de que a fonte é facilmente disponível em matadouros (estima-se que ao final da década de 70 o Brasil teria produzido 18 mil toneladas de proteínas sanguínea por ano).  

|       Por fim, uma fonte não-convencional de proteína consiste na de penas, incluindo também cascos, unhas, pelos, cabelo, pele de anfíbios e lã, todas com potencial voltado à produção de rações, já que o alto teor de queratina, com riqueza de suas pontes dissulfeto, resulta em diminuída digestibilidade para o animal.


### Fatores antinutricionais proteicos

|       Em síntese ao que foi mencionado acima, esses fatores podem incluir inibidores de proteases (soja, feijão), avidina de ovos (combinação com vitamina biotina), tiaminases de crustáceos, peixes e plantas (hidrolizantes de vitamina B1), ovotransferrina (ligadora de ferro, polipeptídeos do glúten (em monogástricos causa a severa e aguda doença celíaca, além de se combinarem à vitamina niacina), e aminoácidos tóxicos. Dentre esses últimos destacam-se a mimosina da forrageira do gado, análogo estrutural do triptofano, o ácido djentóico do feijão sumatra, similar à cistina, cianoalanina e ácidos diaminobutírico e diaminopropiônico, os três últimos causadores do latirismo em rebanhos.
	

### Deteriorações e modificações protéicas

|       Como fonte alimentar para os rebanhos, a proteína pode sofrer diversas transformações ou modificações que convergem sua estrutura a um efeito pró ou antinutricional. Tais  modificações parecem incluir reações de Maillard (combinação de aminas protéicas com carboidratos redutores), tratamentos térmicos (inativação enzimática, de produtos de Maillard e de proteínas tóxicas), tratamentos ácidos e básicos (degradação, desnaturação e racemização), desnaturação a frio (sequestro hídrico nas estruturas protéicas levando à formação de cristais de gelo), oxidação e peroxidação (cadeias laterais de aminoácidos e ácidos graxos insaturados), fotodegradação e alterações na atividade de água (decomposição e oxidação).