---
title: "Bioquímica da Carne e dos Pescados"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       Todo bicho morre. E não é diferente com boi, porco, frango, coelho, peixe, crustáceos e moluscos. Nesse sentido, todos os processos que envolvem a biotecnologia de produção de carne e pescados faz uso dessa máxima vital que, no final das contas, se resume a um apodrecimento controlado do cadáver. A carne que comemos constitui o músculo dos animais. 

|       No músculo ocorrem diversas atividade post-mortem que conferem consistência, aroma e sabor à carne, todos saudáveis por determinado período, ou até perigosos à saúde, quando os períodos de atividade biológica sobre a carne se tornam muito extensos. Assim, fazemos uso de uma atividade biológica, essencialmente enzimática, de constituintes da carne ou de microorganismos sobre esta, para a produção de maminha ou picanha maturada, dourado, siri, lula, lombo, carne defumada, salame, carne seca, e escabeches. 


|       Estímulo de atividade enzimática (pura ou de microorganismos, tais como lactobacilos e fungos) e inibição desta constitum pontos centrais da bioquímica de carnes e pescados. Quando o animal morre, o músculo passa por uma extensa atividade contrátil que leva ao seu enrijecimento. Esta atividade é mediada por íons Ca2+, que deixam o retículo onde se encontram, e estimulam a contração muscular até um limite onde não haja mais ATP, moeda energética fundamental para a contração. Neste ponto ocorre o rigor mortis, pontuado pelo endurecimento da carne (rigidez cadavérica, 7a. hora após o abate bovino). 

|       Acontece que esse ATP não cai do céu, mas precisa ser produzido a partir da quebra de glicose e de proteínas, cujos aminoácidos possam virar glicose. 
Assim, o glicogênio, proteínas e gorduras da carcaça são quebrados para produzir ATP e, nessa quebra, ocorre por consequência a formação de ácido lático, que diminui o pH da carcaça, parando a atividade das proteínas do músculo. Essa carne agora pode ser armazenada, contra ação de microorganismos, a quente, a frio ou no sal e no vinagre. A quente, através da defumação (queima da madeira), a frio, por resfriamento, refrigeração ou congelamento, no sal, pela salmoura, e no vinagre, no preparo de escabeches. Seja qual for o procedimento, o objetivo é o de se conservar a carne por determinado período, definido para cada procedimento, onde a ação de microorganismos e a oxidação pelo ar seja a menor possível. 


|       Quando a carne fica muito tempo armazenada, principalmente em baixas temperaturas, ou na temperatura ambiente sem conservantes, perde parte de seu aroma, cor e sabor, devido à atuação de microorganismos e do ar, resultando em mal cheiro (produtos finais do metabolismo microbiano, esverdeamento (oxidação de hemeproteínas) e ranço (liberação de ácidos graxos voláteis de odor desagradável). A indústria também faz de alguns microorganismo e de enzimas para o amaciamento e para alterações controladas de aroma e sabor nas carnes. Assim, enquanto que o preparo do salame envolve uma etapa de fermentação por lactobacilos, a produção da carne maturada inclui a inoculação de enzimas que digerem proteínas na mesma, tais como catepsinas e calpaínas, amaciando o produto final.


## Detalhes

### Fase ante e post-morten

|       O processamento da carne para o consumidor final envolve um grande número de etapas que estabelecem uma alteração nas suas propriedades, antecedentes ao abate.  Inicialmente, ocorre uma fase post-morten a partir da 7a. hora do abate, quando têm lugar a rigidez cadavérica. Para compreendê-la, uma síntese do processo de contração muscular é exigida. A fibra muscular esquelética possui feixes cuja unidade funcional é a miofibrila. 

|       A miofibrila também também possui uma unidade funcional, o sarcômerio, com bandas escuras e claras, e filamentos protéicos espessos  (miosina) e finos (actina) interligados. Durante a contração muscular, mediada por ATP e Ca2+, as fibras deslizam entre si, reduzindo a extensão do sacômero (contração). O mecanismo da rigidez cadavérica envolve uma queda de ATP (hidrólise) após o abate, com pouca reposição pelo glicogênio e fosfocreatina. 

|       Após algum tempo, a glicose metabolizada em anaerobiose (ácido lático) impede a re-síntese de ATP. Com ATP muito diminuído, a elasticidade muscular reduz progressivamente. A rigidez é inversamente proporcional à temperatura (excessão: frango). As alterações na carne que ocorrem com a rigidez cadavérica envolvem um endurecimento  (ligações cruzadas de proteína actina com miosina na fibra muscular, na ausência de ATP), perda de extensibilidade, perda da capacidade de retenção de água e acidificação. 

|       Quando o pH da carne está baixo e a temperatura alta (300$^{o}$C), pode ocorrer precipitação e desnaturação protéica no retículo sarcoplasmático (fibra muscular), resultando em carne exudativa (mole, úmida e esbranquiçada). 


### Maturação

|       Após a rigidez cadavérica, passa a ocorre a fase de maturação, quando um catabolismo geral dos constituintes da carne (proteínas, tecido conjuntivo, lipídios, ácidos nucléicos) leva a um aspecto mais tenro da mesma. O colágeno tem papel fundamental na qualidade final da carne. A maturação da carne envolve, pois, um processo de degradação natural após a morte do animal, onde componentes estruturais da carne são enfraquecidos ou destruídos, tornando-a mais macia. 

|       Em animais novos ocorre uma melhor solubilização das fibras de colágeno (carne mais tenra) do que em animais mais velhos, devido à um menor teor de ligações cruzadas de hidroxiprolina e hidroxilisina naqueles. Em bovinos, o estresse pós-abate  causa o consumo de reservas de glicogênio, reduzindo a glicólise anaeróbica, o rigor mortis e o declíno do pH. Nestes casos, são observados carnes escuras e com vida-de-prateleira reduzida. 


|       Diversas são as enzimas envolvidas no processo de maturação, dentre as quais podemos citar as lisossomais (catepsinas B, D, L e H), de proteólise ácida, e liberadas durante a lise de membrana, e as citoplasmáticas (proteinases neutras e alcalinas, e tripsina), ativadas em pH maior ou igual a 6,6. A ação enzimática de proteinases visa a degradação de miosina, actina, tropomiosina, nebulina, troponina, desmina, timina e proteína C, dos tecidos musculares, dentre outras. A maturação cárnea pode também ser tecnologicamente induzida por colônias iniciadoras de lactobacilos, leveduras e mofos, como ocorre na fabricação do salame, que atuam fermentativamente no produto, influenciando diretamente em sua cor, aroma, sabor e textura.

### Maciez

|       A  maciez da carne é o principal aspecto da palatabilidade que determina sua aceitação pelo consumidor. Fatores ante-mortem e post-mortem atuam diretamente sobre a maciez e tenrez da carne. Entre os fatores ante-mortem destacam-se raça ou genótipo, alimentação, idade, sexo, aplicação de promotores de crescimento, e manejo pré-abate. Entre os fatores post mortem inerentes ao abate industrial podem ser citados o resfriamento e a consequente velocidade de queda do pH muscular. 


|       Fatores post-mortem inerentes aos procedimentos tecnológicos aplicados às carcaças incluem estimulação elétrica (3000-6000V, minimiza o encurtamento a frio, aumenta a solubilização de colágeno, provoca ruptura mecânica), resfriamento lento ou retardado (temperaturas acima de 100C), maturação em câmara fria (com ou sem vácuo), aplicação de pressão em corte cárneos (pressurização em músculo pré-rigor, Tendertainer®), estiramento (evita contração muscular de vários músculos), aplicação de ultra-som (ondas de choque em músculo pré-rigor, Hydrodine®), e aplicação de substâncias químicas.  

|       Essas últimas incluem ação de enzimas amaciantes (proteases bacterianas, fúngicas ou de origem vegetal), como catepsinas e calpaínas (mamíferos), papaína (mamão), ficina (figo), e bromelina (abacaxi), e infusão de cálcio (ativação das calpaínas musculares, dependentes de cálcio. 


|       Um fator de maciez alternativamente explorado vem sendo o inibidor natural de calpaínas, calpastatina, cuja presença e clonagem vem sendo avaliados para uso industrial. A calpastatina , de elevada atividade 24h post-mortem, é um inibidor de ação de proteases ativadas por cálcio e presentes no músculo. Animais com menores teores de calpastatina (e cistina, inibidor de cisteíno proteinases, como as catepsinas) exibem maior maciez.


### Pescados

|       Devido a teores reduzidos de carboidratos em pescados (salvo moluscos bivalves), pescados são melhor categorizados através de seu teor de gordura, combinado secundariamente ao teor de proteína (atum e bonito representam o topo da fauna marinha no nível protéico). Assim, tem-se animais gordos (mínimo de 10 % em gordura, manjuba, cavalinha, bagre e enchova), semigordos (2,5 a 10 %, bonito, sardinha e tainha), e magros (menos de 2,5 %, cação, linguado, merluza e pargo). Peixes jovens possuem, via de regra, menor teor de gordura e maior de água do que animais adultos, variação essa que também acompanha as mudanças sazonais (gordura maior no inverno). 

|       Crustáceos são considerados animais magros, e com teor de proteína inferior ao de peixes, excessão a este último quesito para o camarão, de composição protéica elevada, similar a da lula, e oposta a do polvo. O teor de proteínas tende a variar bastante entre as espécies. Animais marinhos de carne branca tem os teores de proteínas sarcoplasmáticas em torno de 20 % e miofibrilares em torno de 75 %. A sardinha e o krill apresentam teores acima de 30 % de proteínas sarcoplasmáticas, teores normais de estroma (5 %) e baixos de proteínas miofibrilares. 


|       Quando se compara características protéicas como miosina, proteína da maquinaria contrátil, entre peixes e animais terrestres, observa-se que os primeiros a tem mais termolábil e sensível a digestão de proteases, com menor ativação conjunta da ATPase. O colágeno de peixes também possui a característica única da presença de triptofano realizando o papel de ligações cruzadas entre cadeias polipeptídicas, normalmente realizado por resíduos de hidroxiprolina e hidroxilisina, em animais terrestres.


|       Com relação aos minerais, os peixes brasileiros possuem alto teor de sódio e cálcio, sendo o potássio elemento mais abundante no músculo de peixes marinhos. Peixes brasileiros, contudo, possuem baixo teor de ferro. Crustáceos e moluscos, por sua  vez, tem teores de sódio, magnésio e cálcio elevados, mas níveis de potássio reduzidos. Os sabores e aromas que peixes, moluscos e crustáceos apresentam após o tratamento térmico estão sintonizados com a produção de aminoácidos típicos e nitrogênio não protéico.


### Emas e avestruzes

|       A estruticultura encontra-se em fase de consolidação de plantel no país, com criadores profissionais incentivando o desenvolvimento pecuário de avestruz e de seu conterrâneo nativo, a ema, animal silvestre da América do Sul. Emas são capazes de produzir carne saborosa com baixos níveis de colesterol e alto de proteína, a baixo custo e curto período (12 a 18 meses). Esses animais apresentam ainda um rendimente de carcaça superior a de outras espécies de interesse zootécnico, em torno de 68 % contra uma média de 50 %, perdendo apenas para suínos (73 %). Os cortes da carne de ema, de modo geral, apresentam composição centesimal semelhante à carne das demais espécies de açougue. 

|       A gordura de cortes de ema situa-se em torno de 2 % (carnes gordas o são ao atingir cifras de 10 %), e o teor de proteínas, superior a 22 %, o que indica um alto valor nutritivo, perfeitamente aproveitado em dietas que exijam baixa quantidade de gordura. Seu potencial para a transformação em derivados cárneos pode ser considerado bom, pela relação água:proteína (1:3,3), mas é escasso em gordura, o que requer adição da mesma para a produção de linguiça e hamburguer.


### Armazenamento de carne

|       A carne uma vez obtida pode ser armazenada a frio, por congelamento, defumação ou salmoura. Carnes resfriadas o são em temperaturas superiores a 10$^{o}$C, refrigeradas entre 0 e 10$^{o}$C, e congeladas, abaixo de -1,50$^{o}$C. Durante o pré-resfriamento da carne pode ocorrer o fenômeno de "encurtamento a frio". Este fenômeno se dá quando em temperaturas inferirores a 100C, a concentração de cálcio no espaço miofibrilar aumenta em até 40 vezes, devido à inativação das bombas de cálcio existentes nas membranas lipoprotéicas do retículo que, em função do frio, perdem a capacidade de reter esses íons. Como consequência, ocorre uma contração muscular extensa pela aceleração do metabolismo muscular. 


|       Músculos apresentando "encurtamento a frio" mostram drástico endurecimento da carne após o cozimento. Ainda durante o pré-refriamento, a presença da camada de gordura da cobertura da carne reduz a eficiência  da dissipação do calor, aumentando a ação microbiológica, mas protegendo o múculo contra o ressecamento superficial e a redução da perda de água na carcaça.  O congelamento deve ser realizado preferencialmente após a rigidez cadavérica. Quanto realizado antes, o ATP remanescente e a atividade metabólica tendem a ser retomados mais vigorosamente após o descongelamente  (atividade da ATPase), reduzindo a tenrez da carne (contração muscular mais intensa) e promovendo sua exudação (extravasamento de líquido do interior da carne). 


|       O congelamento deve ser rápido. Quando lento, pode promover a formação de grandes cristais de água, desnaturando e precipitando proteínas, e rompendo células, o que, consequentemente, reduz a atividade metabólica sobre a carne descongelada (menor maturação). A armazenagem a frio induz a liberação de aminoácidos (degradação protéica), de glicídios (glicogenólise), e de hipoxantina (derivado de ácido nucléico), contribuindo para suas características culinárias. O armazenamento a frio não deve ser muito prolongado, caso contrário pode ocorrer perda de aroma (desaparecimento de substâncias voláteis). Neste sentido, proteínas da carne são mais estáveis que de pescado.

|       Carne bovina, armazenada por  8 semanas em -40C, pode desencadear um aumento no teor lipídico (hidrólise de fosfolipídios), e na atividade de lipoxidases, aumentando sua rancificação (oxidação de ácidos graxos, com consequente liberação de ácidos graxos voláteis de odor desagradável). 


### Salmoura

|       A salga inclui permanecer a carne na salga com cloreto de sódio a 4%, o que reduz a capacidade de retenção de água na carne (combinação NaCl-proteína aumenta a pressão osmótica). O cloreto de sódio tem ainda função bacteriostática, gustativa e emulsificante da carne, esta última pelo aumento no teor da força iônica, aumentando suas propriedades tecnológicas, e responsável por manter estabilidade e conferir textura aos produtos.


### Conservantes

|       Acréscimo de nitrato de sódio torna a carne mais rósea. Microbiologicamente, nitrato é reduzido a nitrito, e este a óxido nítrico; o óxido nítrico combina-se com com a hemoglobina, auxiliando na fixação da cor. Além disso, nitritos e nitratos exercem efeito bacteriostático (ex: Clostrídia), e ajudam no desenvolvimento do sabor e aroma. O nitrito é carcinogênico, pois pode levar à formação de nitrosaminas no organismo. 

|       Além do nitrito, comercialmente mais empregado que o nitrato (conversão bacteriana de aferição imprecisa), são utilizados também o sorbato, antibióticos, ácido acético e láctico, como conservantes. O nitrito, utilizado em 10-50 ppm, não pode industrialmente ultrapassar 200ppm.


### Defumação

|       No processo de defumação, atuam componentes desidratantes e antimicrobianos da fumagem, além do retardamento da rancificação. Não obstante, a pirólise da madeira libera também benzopireno e antraceno, ambos carcinogênicos. As propriedades organolépticas (aroma e sabor) da defumação dependem da composição de celulose, hemicelulose e lignina (esta última a principal, cuja pirólise forma as substâncias que mais conferem aroma e sabor). A coloração da carne defumada é resultante de reações entre os componentes da madeira e das proteínas e aminoácidos da carne. No trato culinário, o aquecimento da carne desnatura enzimas e proteínas. 


|       Exemplificando, hexoquinase desnatura em 400$^{o}$C, creatina quinase em 600$^{o}$C, mioglobina em 650C. Além disso, o aquecimento aumenta a perda de água, coagula proteínas (650$^{o}$C, coagulação do colágeno favorece tenrura), destrói 1/3 das vitaminas hidrossolúveis e alguns aminoácidos (lisina e metionina, por exemplo), diminuindo o valor nutritivo da carne. O aquecimento promove o escurecimento da carne através da reação de glicídios redutores com NH2 de aminoácidos e proteínas. Além disso, manifestam-se odores característicos, resultado da volatilização de nitrogênio, acetaldeído, acetona, amoníaco e ácidos graxos voláteis. 

|       A defumação também pode ser a frio (<400$^{o}$C), a quente (50-1200$^{o}$C), com fumaça líquida  (produto da destilação da madeira), ou eletrostática (permite a eliminação de partículas e água, sem afetar os vapores).


### Rancificação

|       A rancificação é a oxidação de lipídios carregados e insaturados, em sua maioria, deteriorando a carne em suas propriedades de cor, aroma e valor nutritivo. O ranço acelera em carnes não aquecidas (hemoglobina e porfirinas não oxidadas), flutuações térmicas, umidade, ausência de compostos anti-oxidantes e provimento exagerado de oxigênio. 

|       O Fe2+ e as hemeproteínas oxidam peróxidos lipídicos, gerando radicais livres em cadeia. 

### Coloração

|       A coloração natural da carne se dá através da estrutura de proteínas de grupo heme, como a mioglobina e a hemoglobina, uma vez que a oxidação do ferro e a desnaturação destas proteínas resulta na cor rósea da carne. No pescado, a desnaturação de mioglobina acarreta reações químicas com os grupos -SH de cisteínas da carne, resultando no tom esverdeado do pescado. Tons esverdeados na carne vermelha também podem ser originados da oxidação da mioglobina em presença de peróxido de hidrogênio (H2O2). 

|       Neste caso, o OH se combina ao grupo heme da mioglobina. A hemoglobina se oxida mais rapidamente do que a mioglobina, por possuir quatro grupos heme, ao invés de um.


### Deterioração de pescados

|       A microbiota singular de pescados, existente em guelras, trato gastrointestinal e superfície corporal, juntamente com o rápido perídodo post-morten do mesmo (10h em 200$^{o}$C , 4h a 300$^{o}$C), onde a produção e retenção local de ácido láctico é grande, fazem com que o controle sobre o produto deva ser rigoroso para o consumidor final, devido a alterações enzimáticas, organolépticas e de rancificação nos mesmos. 

|       Além disso, a constituição frouxa do tecido conectivo de pescados (facilita a permeabilidade bacteriana), concentrações de proteínas sarcoplasmáticas e miofibrilares, juntamente com grande teor de fosfolipídios,  ácidos graxos e colesterol, variam muito em espécies, sexo, e idade, tornando os processos anteriores também variáveis. 

|       Exemplificando, o cação possui 0,8% de gordura e 21% de proteína bruta em sua carne, ao passo que o bagre possui 15% de gordura e 15% de proteína. Peixes jovens possuem maior teor de água e menor de gordura do que adultos. Sazonalmente também há grande variação de água e gordura em pescados. Como resultado final, a rápida deterioração do pescado é um produto da rápida ação descontrolada de enzimas endógenas (amolecimento da carne), atuação bacteriana elevada (produto cárneo final é menos ácido), alta rancidez (riqueza de ácidos graxos polinsaturados nos óleos), e ação de sucos digestivos (passam da parede intestinal e atuam sobre os tecidos musculares, facilitando o espalhamento de microorganismos nos tecidos. 

|       A indústria de pescados utiliza alguns procedimentos para prolongar a vida útil dos produtos em depósito, tais como o emprego de conservantes (borato, benzoato, dióxido de etileno, fosfatos, nitrito), aplicação de atmosferas modificadas (hipobárica, vácuo, enriquecimento de CO2, lavagem de carcaças com ozônio), e irradiação ionizante. Alterações na carne de pescados provocadas por insetos (mosca e besouro) parecem resultar em mais danos do que as de bactérias, fungos e ácaros, devido ao grande número de ovos na postura e à voracidade das larvas no ataque da carne. O combate vem sendo realizado com cuidados no abate e imersão em inseticidas. 

