---
title: "Metabolismo & Dietas"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       Uma simples observação do mapa metabólico nos infere sobre sua plasticidade, adaptação e riscos, no que tange aos vários tipos de dietas consumidas com objetivos hospitalares ou estéticos. Este texto trata dos aspectos bioquímicos básicos da integração metabólica que envolve as principais dietas cultuadas pela população, como a dieta vegetariana, dieta de carboidratos, dieta de gorduras e dieta de proteínas.


### Dieta vegetariana. 

|       O grande problema é o de se obter calorias e proteínas suficientes para preencher a NDR. Isso se dá pelo baixo teor protéico de produtos vegetais, pelo baixo valor biológico de proteínas vegetais, e pela indigestibilidade de algumas proteínas vegetais. A dieta vegetaria estrita é potencialmente arriscada em condições em que não se é possível a redução da NDR, como no lactente, na gestação, e na lactação, o que pode resultar em desnutrição protéico-calórica. A dieta vegetariana deve ser complementada com leite e ovos (dieta lacto-ovo), incluir fontes calóricas altas de vegetais (nozes, grãos, frutas secas), e permitir combinações protéicas que elevem o valor biológicos da proteínas ingeridas. 


### Dieta de carboidratos. 

|       Dietas ricas em carboidratos pontuam a existência de polissacarídios e de fibras. Neste caso, as fibras possuem papel central no emagrecimento, uma vez que fornecem a sensação de plenitude gástrica, ao mesmo tempo em que não são absorvidas, reduzindo o peso corporal. Carboidratos complexos fornecem calorias, além de sua hidrólise parcial resultar na liberação de prebióticos, substâncias que auxiliam a microflora animal. Além disso, o consumo de carboidratos leva a um efeito poupador de proteínas corporais, com proteólise reduzida uma vez que se tornam menos necessários os esqueletos de carbono para suprimento na gliconeogênese. O uso excessivo de carboidratos, entretanto, pode resultar em formação e acúmulo de ácidos graxos através da síntese de glicerol e de acetil CoA, a partir da disponibilidade de derivados monossacarídicos. Não obstante, dietas ricas em carboidratos exigem maior consumo de água para sua digestibilidade e absorção. Além dos riscos iminentes da ingesta insuficiente de água, a perda aparente de peso corporal observada pode ser consequência do sequestro de água exigido no metabolismo de fibras e carboidratos complexos. A dieta rica em carboidratos é empregada no trabalho atlético de esforços aeróbicos, como corridas de longa distância, natação e futebol. Já é conhecido que uma dieta rica em carboidratos complexos aumenta a secreção insulínica, facilita a glicogênese hepática, aumenta os estoques de glicogênio e, por consequência, a resistência física do atleta.  


### Dieta de gorduras. 

|       Originalmente desenvolvida para o tratamento de diabéticos (supressão da glicose dietética), dietas ricas em gordura possuem a vantagem de se consumir menos do que em outras dietas, já que o aporte calórico de ácidos graxos é 2 vezes maior que o de proteínas e carboidratos. Porém, uma observação deve ser feita quando se trata de uma dieta rica em gorduras, já que encontra-se muito bem estabelecida a relação entre gorduras saturadas e colesterol, com doenças coronarianas. Ao se tratar desse tipo de dieta, deve-se ter em mente ácidos graxos insaturados, monoinsaturados mais do que polinsaturados (PUFAs), e ácidos graxos essenciais, o que inclui alguns óleos vegetais como canola e oliva, e o consumo de peixes, principalmente de água fria.


### Dieta de proteínas. 

|       A dieta rica em proteínas tem respaldo bioquímico no fato de que apenas 2 aminoácidos, Lys e Leu, são estritamente cetogênicos. Sendo assim, uma dieta protéica combinada, onde haja escassez destes aminoácidos, poderá reduzir a lipogênese. Além disso, aminoácidos são convertidos a glicose, reduzindo a necessidade de consumo daqueles para a manutenção dos níveis glicêmicos. Além disso, alguns aminoácidos como Gln e Ala são essenciais no ciclo de reaproveitamento do lactato sanguíneo (ciclo de Cori), vindo da fermentação eritrociária ou muscular. Glutamina, em especial, possui papel preponderante, já que representa 50% dos aminoácidos circulantes, transporta amônia tóxica, e auxilia no balanço ácido-básico. A dieta protéica, entretanto, encontra barreira no uso por indivíduos com algum tipo de disfunção renal,  já que o controle da produção de uréia e eliminação da amônia envolve o metabolismo ntirogenado. 

|       Insuficiência renal crônica, por exemplo, caracteriza-se pelo acúmulo de produtos finais do catabolismo de proteínas, principalmente uréia. Algum grau de restrição protéica na dieta é geralmente necessário porque esses produtos finais tóxicos são responsáveis por muitos dos sintomas associados à doença.


<!-- ### Algumas observações -->

<!-- |       Estratégias em nutrição levam em conta a possibilidade de oferecer bem-estar alimentar à população, evitando contudo o desenvolvimento da obesidade. Neste sentido, as recomendações traduzem-se em uma dieta baseada principalmente em carboidratos, com proteína suficiente para suprir as necessidades de aminoácidos essenciais, e com lipídios não ultrapassando 30% do consumo calórico total. Substitutos de gorduras têm chegado ao mercado nos últimos anos acompanhados de controvérsias. Olestra, um poliéster de sacarose esterificado com 6 a 8 ácidos graxos, relacionado quimicamente ao triacilglicerol, tem sido associado a distúrbios digestivos e diarréia, já que não é degradado enzimaticamente durante a digestão.  -->

<!-- |       Estudos com leptina, uma proteína de 16 kD sintetizada a partir do gene *ob* de camundongos, tem tido emprego comercial, ainda que duvidosos. Sua administração em modelos animais evidenciou redução de apetite e aumento de atividade, resultando em perda de peso. -->






