---
title: "Exercício em Animais de Competição"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       	O conhecimento da dinâmica metabólica de cada animal pode auxiliar na seleção de nutrientes adequados em períodos que antecedem a competição. Entre esses nutrientes destacam-se a água, eletrólitos, formas variadas de glicose e de lipídios contidos em forragem e alimentos, e proteínas, em relação íntima para o esforço físico quando direcionado ao trabalho muscular aeróbico ou anaeróbico.

## Detalhes

|       Por animal de competição em pecuária, abordaremos exclusivamente o rebanho equino. Resumidamente, a comparação de uma competição hipotética entre um homem, um rato e um cavalo atletas, resultaria em melhor performance física deste último, uma vez que apresenta maior velocidade de corrida, menor fadiga em exercícios de longa duração, maior consumo máximo de oxigênio, maior capacidade de carga e movimentos de beleza e robustez. 

|       Entretanto, este vencedor perderia para o rato na competição relativa ao peso corporal, e ao homem, na habilidade motora e intelectual da execuçào do movimento. 


### Consumo energético e de O$_{2}$

|       A energia disponível para a atividade física animal fica disponível sob a forma de trifosfato de adenosina, ATP, sendo sua biossíntese realizada por três processos bioquímicos. Hidrólise de fosfocreatina, em atividades físicas intensas e de curta duração (em torno de 10 segundos), glicólise anaeróbica, uma oxidação incompleta de nutrientes, com formação de ácido lático, e oxidação mitocondrial, uma oxidação completa de nutrientes, onde os pares de prótons formados no ciclo de Krebs são tamponados na cadeia respiratória, em reação oxigenada que resulta na formação de água. 


|       A oxidação de um mol de glicose leva à formação de 38 moles de ATP, enquanto que a oxidação de um mol de palmitato (ácido graxo livre) resulta na formação de 129 moles de ATP.  Apesar da aparente vantagem de lipídios sobre carboidratos no tangente à produção energética total, o gasto de oxigênio para a metabolização de um grama de lipídio é de 2,019 litros, ao passo que para um grama de glicose, 0,828 litros. Curiosamente, o catabolismo graxo produz-se 3 vezes mais energia, mais consome 3 vezes mais oxigênio. 
Assim, as células musculares dos animais submetidos a exercício físico crescente metabolizam, inicialmente, grandes quantidades de lipídios como a formação de muito ATP (exercício de baixa intensidade).

|       Ao se reduzir a oferta de oxigênio na continuidade do exercício, as células passam a utilizar mais a glicose (exercício moderado) e, posteriormente, processos glicolíticos anaeróbicos (exercício intenso), esses últimos com formação de ácido lático. Este momento caracteriza o limiar anaeróbio, no qual o metabolismo aeróbio é insuficiente para a produção de ATP, e cujo produto ácido pode resultar em acidose metabólica considerável.


### Produção de ácido lático

|       O ácido lático produzido na fibra muscular esquelética rapidamente se difunde para o plasma e é tamponado pelo bicarbonato de sódio, resultando na formação de lactato de sódio e ácido carbônico, este último dissociando-se em gás carbônico e água. A elevada concentração de ácido lático plasmático é denominada lactacidemia a qual, juntamente com a hipercapnia (elevação de dióxido de carbono), desencadeiam uma hiperventilação no animal para eliminar o excesso de dióxido de carbono produzido, evitando, assim, uma acidose metabólica.


|       Quando a lactacidemia torna-se elevada o ácido lático pode inibir o processo contrátil da fibra muscular esquelética, uma vez que os íons H+ do ácido competem no mesmo sítio TN-C de ligação de cálcio na troponina. Complementarmente, a redução local de pH pode comprometer as atividades enzimáticas do catabolismo durante a atividade física. Em cavalos, a relação de lactacidemia por unidade de peso corporal é baixa (0,04), o que o leva a interromper o exercício precocemente em relação ao rato (36,8) e ao homem (0,2). 

|       A causa primordial da ineficiência relativa do cavalo em suportar elevada lactacidemia, deve-se às características do padrão respiratório que, durante atividade física intensa, não consegue corrigir adequadamente o equilíbrio ácido-base. Esta inabilidade de ajustes precisos da ventilação e do equilíbrio ácido-base desencadeia a síndrome de pós-esforço, uma miopatia denominada rabdomiólise, que aparece nas primeiras 48 h após o esforço físico extenuante.


### Adaptações a exercícios intensos

|       Diversas são as alterações subsequentes a atividade física periódica nos animais. Dentre estas, aumento da taxa metabólica, taquicardia, taquipnéia, elevação do débito cardíaco, hiperventilação, e aumento nos níveis de alguns fatores, tais como hormônios de crescimento, tireoideanos, cortisol, adrenocorticotrópico, glicagon e prolactina, dentre outros. Algumas adaptações são exclusivas de cavalos, como o aparecimento de equinócitos produzidos no baço, similares a eritrócitos, que aumentam a viscosidade sanguínea e, em especial, a resistência ao fluxo sanguíneo na artéria pulmonar. Este fenômeno, 5 vezes superior ao que ocorre em humanos, pode promover a ruptura de alvéolos e da microcirculação pulmonar, resultando em hemorragias nasais no animal. 


### Manejo nutricional de cavalos de competição

|       A injestão de volumosos, concentrados, água e eletrólitos têm efeitos imeidatos no organismo do cavalo e, potencialmente, sob sua performance ao dia da competição. A água é o elemento mais crítico para estes animais, principalmente ao dia da competição, sendo controlada por hormônio atrial natriurético, arginina-vasopressina, e aldosterons. A ingestão involuntária de água em rebanho equino pode variar até 4 vezes ao longo do dia (9 a 33 litros reportado). 


|       Em esforço físico para máxima performance (anaeróbico limitado a 3 min), como corridas rasas e com barreira, são utlizados glicose e glicogênio como principais fontes de energia, e ácidos graxos livres durante o período de aquecimento (poupadores de carboidratos). Para performance submáxima de longo prazo (aeróbica por mais de 60 min), como enduro, cavalgada por trilhas, alta escola e competição de três dias, a manutenção da hidratação torna-se a principal preocupação, seguida do fornecimento de eletrólitos. 

|       As fontes de glicose e glicogênio não configuram interesse como no trabalho anaeróbico, contando-se para a atividade com a oxidação da ácidos graxos livres provenientes da fermentação da forragem no intestino grosso, e da mobilização de reservas corporais.
