---
title: "Bioquímica da Gestação"
lang: pt
---

```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```


## Introdução

|       O desenvolvimento embrionário que ocorre durante a gestação promove um conjunto extenso de modificações metabólicas e fisiológicas em ambos os tecidos envolvidos, materno e fetal. A grosso modo, o período gestacional oferece um catabolismo aumentado para a mãe em simultaneidade ao anabolismo dos tecidos embrionários. 

|       As faixas de referência de diversos marcadores de função tecidual (hepática, renal, sanguínea) adquirem significativa flexibilidade durante o período, atingindo níveis sorológicos comparáveis aos apresentados em distúrbios severos, como síndrome nefrótica ou metástase óssea. 

|       O monitoramento fetal durante o período pode ser efetivado por ultrassonografia, fetoscopia e radiografia, bem como pela obtenção de fluidos (amniocentese, cordocentese), e biópsia do fígado e da pele.

## Detalhes


|       A gestante ganha peso. A biomassa adquirida, em torno de 12,5 ± 4 kg, provém principalmente do líquido extracelular (LEC, volume sanguíneo aumenta em 45 %) advindo da retanção de água (em torno de 5 litros), dos produtos da concepção (feto, placenta e líquido amniótico), e de reservas de gorduras (em torno de 25 % do peso ganho). 

|       A gestante apresenta hiperventilação no primeiro trimestre de gravidez, com teor reduzido de CO2, o que é compensado por um aumento na excreção de de HCO3-, evitando assim um quadro de alcalose. À despeito da respiração normal, também consome 20 % mais de oxigênio molecular.  A taxa de filtração glomerular da mulher grávida também aumenta, em torno de 15 %, aumentando por conseguinte a excreção de glicose (baixo limiar renal), aminoácidos, urato, e albumina (microalbuminúria), situações que na não-gestante poderiam estar associadas a patologias variadas.

### Características sorológicas


|       Diversos metabólitos presentes no soro materno também sofrem significativa alteração. Em sua maioria, pode-se afirmar que ocorre uma redução nos principais marcadores funcionais, exemplificando-se AST e ALT, albumina (maior LEC), bilirrubina, glicose em jejum, uréia, e elementos tais como o ferro. 

|       Por outro lado, a gestante experimenta consideráveis aumentos de fosfatase alcalina, proteínas transportadoras de esteróis (transtiroxina e proteína transportadora de hormônios sexuais, fibrinogênio (auemnto em mais de 50 %) e proteínas da cascata de coagulação sanguínea, hormônios específicos (paratormônio - PTH, estrógenos, T3 e T4 totais, progesterona, corticosteróides – aumento em várias vezes, prolactina – aumento em dez vezes, e hormônio placentário - hPL), vitamina D3 e cobre. 

|       Como um todo, esses aumentos séricos conduzem a uma maior resistência ao sistema angiotensina-aldosterona, maior teor de proteínas ligantes de hormônios tireoideanos, esteroidais e fibrinogênio, e a um catabolismo lipídico mais pronunciado, em relação ao da glicose.

### Características metabólicas

|       A gestante desenvolve uma resistência a insulina que, se não monitorada, pode resultar em diabetes gestacional (3 % dos casos). Quando não tratado, esse quadro pode levar a paciente à administração de insulina por toda a vida (30 % dos casos). A resistência insulínica é acompanhada por síntese reduzida de receptores de glicose e permeases específicas. 

|       Isto induz ao metabolismo materno um redirecionamento para o catabolismo de lipídios, aumentando, por conseguinte, os teores plasmáticos de triglicérides, colesterol, e fosfolipídios. LDL-colesterol também aumenta, promovendo um aumento na síntese de estrógenos e progestágenos, aumentando ainda mais a resistência insulínica materna.

|       O catabolismo elevado de ácidos graxos, estimulado pelo hPL e hormônio placentário, pode envolver a mãe num quadro de acetoacidose, devido ao acúmulo de corpos cetônicos no organismo, ao final do período gestacional. Nessa fase, e ao início da lactação, quilomicra e VLDL aumentados são utilizados para a síntese de gordura láctea, ao passo que hormônio placentário para a ativação de proteína lipase que estimulará a produção de ductos secretores mamários. Concomitantente, biossíntese aumentada de lactose pela gliconeogênese mamária e prolactina para a organogênese das glândulas.

### Marcadores da gravidez e problemas correlatos

#### hCG

|       A identificação do estado gestacional pode ser realizada, no ambulatório ou com uso de kits  com a glicoproteína hCG, ou gonadotrofina coriônica, que aparece após 24 h da implantação do blastocisto ou 11 dias após a concepção.  A hCG atinge picos séricos até a 9a. semana de gestação, decrescendo até o 3o. trimestre.  Essa proteína permite uma ativação da progesterona que favorece a formação do corpo lúteo. Clinicamente, variações imprevistas em seus teores são utilizadas no diagnóstico de gravidez ectópica, viabilidade fetal (aborto), coriocarcinoma e mola hidatiforme.

#### Alfa-fetoproteína

|       Glicoproteína produzida pela bolsa vitelínica e pelo fígado fetal, e que aumenta progressivamente durante a gravidez até a 32a. semana. No entanto, valores muito pronunciados de AFP escoados para o líquido amniótico säo indicadores de deficiëncias na formaçäo do tubo neural (90 % dos casos), como na espinha bífida e na anencefalia. associaçöes de AFP e de hCG säo comumente obtidas para aferir anomalias cromossomais (Síndrome de Down, por exemplo).

#### Bilirrubina

|       O pigmento presente no líquido amniótico pode ser empregado na triagem de incompatibilidade Rhesus, resumidamente, a produçäo de anticorpos maternos tipo IgG que atravessam a barreira placentária causando hemólise em hemácias fetais. A hemólise libera hemoglobina cujo grupo prostético, heme, converte-se em bilirrubina.
	
|       Complementarmente, o método de Coombs direto avalia a possibilidade da enfermidade na determinaçäo de anticorpos por volta da 16a. semana, e o risco da doença hemolítica do recém-nascido. A reversäo conhecida do quadro pode ser efetivada através de administraçäo intravenosa de anticorpos.

#### Fosfolipídios

|       A síndrome da angústia respiratória do neonato pode ser diagnosticada pela deficiëncia de surfactante pulmonar, lecitina, atingindo 1 % dos recém-nascidos, ou 10 % dos prematuros. Nesse caso, avalia-se o risco quando a relaçäo lecitina / esfingomielina estiver abaixo de 2, um indicativo da imaturidade tecidual. O tratamento é realizado por aplicaçäo do líquido deficitário.

#### Gases e metabólitos

|       O tecido fetal metaboliza o lactato, glicerol, ácidos carboxílicos, corpos cetönicos, e glicose. Desse, o excesso de lactato pode ocasionar hipóxia fetal.

#### Lactogênio placentário

|       O hPL, modulador da funçäo placentária e por esse tecido produzido, possui valores que flutuam até o parto com pouca releväncia clínica em diagnóstico.

#### Hormönios sexuais

|       Estrógenos e gestágenos figuram entre os mais relevantes durante o período em questäo. Os estrógenos placentários provém do precursor deidroepiandrosterona, DHEA, resultando em estradiol (folicular), estrona (mucosa uterina), e estriol (mucosa vaginal), originalmente sintetizados no ovário. O estrógeno amplifica a secreçäo de prolactina em mais de dez vezes. 

|       A progesterona, produzida pelo ovário e placenta, diferem em seus destinos metabólicos. Enquanto que a primeira inibe os processos de maturaçäo folicular e ovulaçäo, a progesterona placentária promove a lactaçäo e o desenvolvimento da mucosa uterina. Entretanto, até o 5o. mês de gestaçäo, a síntese de estrógenos e progesterona é promovida essencialmente pelo corpo lúteo.

