---
title: "Metabolismo & Nutrição"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       As necessidades dietéticas recomendadas (NDR) estimam a quantidade de um nutriente requerida para preencher as necessidades de 95% da população. A NDR pode variar com a idade (lactentes exigem 2,5 vezes mais proteína que adultos), sexo (a NDR masculina é 20% maior que a feminina) e outros fatores (mulheres grávidas e nutrizes possuem NDR até 30% maior). 

|       As necessidades energéticas humanas médias estão em torno de 2900 kcal/dia para homens (adulto de 70kg) e 2100 kcal/dia para mulheres (adulto de 50kg). A energia alimentar disponível gira em torno de 4 kcal/g para carboidratos, 4 kcal/g para proteínas, 9 kcal/g para gorduras e 7 kcal/g para o álcool. A energia total requerida por um indivíduo é a soma de 3 processos, a saber, a taxa metabólica basal (energia gasta no repouso ou estado absortivo, 1800 kcal para homens e 1300 kcal para mulheres), o efeito térmico do alimento (30% de calor corporal aumentado na digestão e absorção), e a atividade física. 

## Detalhes

|       Nutricionalmente classifica-se os grupos alimentares em macro e micronutrientes. Os macronutrientes abrangem gorduras, carboidratos e proteínas. As gorduras, 90% na forma de triacilglicerol, têm papel no fornecimento de energia, palatabilidade, e absorção de vitaminas lipossolúveis. As gorduras podem ser de fonte vegetal (ácidos graxos insaturados, como óleo de milho – polinsaturado, óleo de canola e oliva – monoinsaturado; ácidos graxos saturados, como óleo de côco e dendê), ou de fonte animal (ácidos graxos saturados, à excessão do peixe). 

|       Ácidos graxos essenciais, tais como o linoléico e linolênico, são exigidos na dieta. Na falta do ácido linoléico, é necessária a injesta de seu metabólito, o ácido araquidônico. Deficiências de ácidos graxos essenciais são raras, levando a dermatite descamativa, perda de cabelo e má cicatrização.


|       Os carboidratos da dieta podem se apresentar na forma de monossacarídios (glicose e frutose são os principais), dissacarídios (maltose das bebidas maltadas, sacarose do açúcar de mesa, lactose do leite), ou polissacarídios (amido do trigo e batata, fibras). As fibras da dieta (cerais integrais, frutas, vegetais e legumes) são polissacarídios não digeríveis (celulose, lignina e pectina), não fornecendo energia, mas propiciando mobilidade gástrica (captação de água do intestino, aumentando seu volume em até 15 vezes), menor absorção de tóxicos, menor constipação, hemorróida e câncer de cólon. Desvantagens do consumo de fibras incluem a sua capacidade de combinação com zinco, e redução de absorção de vitaminas lipossolúveis. Os carboidratos não constituem um elemento essencial, já que podem ser produzidos a partir de aminoácidos, mas sua ausência dietética leva a produção de corpos cetônicos e proteólise corporal (esqueletos de carbono para a gliconeogênese). 

|       Não há evidências de que açúcares simples sejam nocivos, não sendo diabetogênicos tampouco engordantes em si. A síntese de ácidos graxos a partir de glicose só ocorre quando este encontra-se em excesso. Entretanto, está bem estabelecido a correlação do consumo de sacarose com a cárie dentária. Proteínas possuem valor biológico proporcional à sua oferta de 8 aminoácidos essenciais (o score máximo é representado pela albumina do ovo, com valor de 100; pão integral tem valor de 30). Na infância, mais 2 aminoácidos, Arg e His, são requeridos para o crescimento rápido de tecidos (o mesmo para recuperação traumática). Neste sentido, seres humanos não possuem necessidade dietética de proteínas em si. 

|       Proteínas podem ser de fonte animal (carne, aves, leite, peixe), com maior valor biológico, e de fontes vegetais (que quando combinadas adequadamente podem produzir o valor biológico de proteínas animais; ex: feijão  - pobre em Met, rico em Lys e arroz  - pobre em Lys, rico em Met). Quando o consumo de nitrogênio iguala-se saudavelmente à sua perda (urina, fezes, suor), o organismo encontra-se em equilíbrio nitrogenado. Balanço nitrogenado positivo pode ser requerido em situações como crescimento, gestação ou recuperação, ao passo que balanço nitrogenado negativo ocorre em situações como estresse, trauma ou má qualidade protéica. Não há vantagens fisiológicas no consumo excessivo de proteínas, uma vez que o acetil CoA metabolisado excessivamente leva à síntese de ácidos graxos. No entanto, o consumo de carboidratos diminui a proteólise para as necessidades de glicose, sendo aqueles considerados poupadores de proteínas.


|       Os micronutrientes são constituidos pelos minerais, que podem atuar como elementos estruturais, como cofatores, no equilíbrio ácido-básico, na condução nervosa e sensibilidade muscular. O cálcio corporal encontra-se principalmente na forma de cristais de fosfato e cálcio (ossos e dentes), e secundariamente como cálcio iônico. Este último é utilizado pelo organismo para contração muscular, impulso nervoso, transporte iônico, e para transmissão de sinais pelas membranas. O cálcio é controlado no organismo através do hormônio da paratireóide (ativado em queda) e da calcitonina (ativada em aumento). O hormônio da paratireóide, PTH, é ativado pela queda nos teores intracelulares de cálcio. O PTH então aumenta a absorção de cálcio do filtrado glomerular renal, diminui a absorção de fosfato, e aumenta a síntese da forma ativa da vitamina D, a qual libera cálcio dos ossos e aumenta o transporte intestinal de cálcio ao sangue. Quando os níveis de cálcio encontram-se elevados, a calcitonina da tireóide diminui sua reabsorção óssea e aumenta a perda de cálcio e fosfato pela urina. 

|       O cálcio está relacionado com a osteoporose, doença que leva à perda progressiva da massa óssea, com prevalência em 70% das fraturas de norte-americanos idosos. Sódio, potássio e cloreto agem sinergicamente na regulação de pH e manutenção da osmolaridade intra e extracelular. Apesar de não existir relação causal direta entre o consumo de sal e a hipertensão arterial, sabe-se que um terço da população hipertensa norte-americana responde a uma redução de sal dietético. O consumo de potássio está inversamente relacionado ao derrame cerebral e hipertensão arterial. O ferro encontra-se 99% combinado a hemeproteínas como hemoglobina e citocromos, e proteínas de armazenamento, como ferritina e hemossiderina. Deficiência de ferro leva a anemia ferropriva, reduzindo a produção de hemoglobina. Suplementos férricos, à excessão da fase menstrual, podem ser tóxicos, levando a um índice maior de infarto do miocárdio. O ferro em excesso também origina radical hidroxila a partir de peróxido de hidrogênio, e favorece a oxidação de LDL.


|       A *NDR* dos vários componentes da dieta envolve um consumo de gordura máximo de 30% das calorias totais ingeridas (10% de monoinsaturados, 10% de polinsaturados, 10% de saturados), até 60% de carboidratos complexos,  10% de proteínas, 30g de fibra, menos de 300mg de colesterol, até 8g de sal, e no máximo dois drinques alcoólicos. Atualmente, doenças causadas por deficiências nutricionais vêm sendo substituidas por aquelas de excesso no consumo. Os problemas centrais da doença crônica de base nutricional são aqueles atribuidos a gorduras. Doença arterial coronária (infarto do miocárdio, ataque cardíaco) está bem relacionada ao consumo de ácidos graxos saturados e colesterol. 

|       Níveis altos de LDL sugerem maior risco coronariano, já que a lipoproteína transporta 80% do colesterol corporal. Em contraste, níveis elevados de HDL está relacionados com efeito protetor à doença coronariana. A gordura saturada é o fator dietético que mais influencia o colesterol plasmático, apesar de nem todos os ácidos graxos saturados propiciarem um aumento do colesterol (estearato e ácidos graxos de cadeia curta). As principais fontes de ácidos graxos saturados que elevam o colesterol (laureato, miristato, palmitato) estão nos laticínios, carnes e alguns óleos vegetais (coco, palma). 

|       O ácido linoléico (n-6, de soja, milho, girassol e açafrão) reduz o colesterol plasmático, enquanto que o ácido linolênico (n-3, de salmão, arenque, sardinha, soja e canola) reduz o triacilglicerol plasmático, a formação de trombos e agregação plaquetária (inibe conversão do ácido araquidônico ao trombogênico TX2, sendo formados TX3). Àcidos graxos trans (produzidos pela hidrogenação da margarina), que correspondem a 5% da dieta gordurosa elevam os níveis de colesterol plasmático. Consumo de anti-oxidantes como vitaminas C e E, e fibras, pode reduzir os riscos de tumores.  A vitamina E reduz em até 40% o risco da letalidade do infarto, a vitamina C (frutas cítricas e vegetais) protege contra tumores do estômago, ambas diminuem a oxidação de LDL (aterosclerose), e as fibras reduzem o risco de câncer de cólon e diverticulite.







