---
title: "Bioquímica de Ovos"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       	Ovos de frango possuem uma composição bioquímica comum a outros derivados de origem animal, qual seja, um conjunto de glicídios, de aminoácidos  livres e peptídios, proteínas e enzimas variadas, fosfolipídios e ácidos graxos, além de vitaminas e minerais, desses últimos fazendo mister a participação do cálcio. Existem algumas diferenças na composição dessas biomoléculas para o albúmen da clara e o conteúdo da gema. Enquanto que a primeira é melhor relacionada a princípios de defesa, mecanismos metabólicos e proteção ao embrião, a gema encontra-se mis voltada ao aporte nutricional para o desenvolvimento do mesmo.

## Detalhes

|       A síntese e produção de ovos decorre, a grosso modo, do transporte e produção de substâncias específicas através de membranas. As etapas de produção constituem a formação de albúmen à 3a. hora, a formação de membrans da casca até a 5a. hora, adição de água pela 10a. hora, calcificação após decorridas 24 horas, e produção da gema, essa em 7 dias. A composição média final do ovo de galinha gira em torno de água  (40 g), proteína (7 g), gordura (6 g), carboidratos (0,3 g), cálcio (2 g), e outros elementos (4 g). Gema e clara de ovo são distintas em sua composição de proteínas e lipídios.

|       As principais proteínas da gema são a fosfovitina, lipovitelinas (complexação com cálcio e ferro), e livetinas (solúveis em água). Os lipídios da gema são constituidos por triglicerídios, lecitina, cefalina, fosfolipídios e esfingomielinas. A síntese da gema envolve a produção de proteínas no fígado, com posterior transporte ao ovário. Os lipídios da gema possuem um conteúdo hepático dobrado quando comparado a frangos não poedeiros.


|       Existem aproximadamente 40 proteínas distintas no albúmen da clara de ovo, dentre as quais podem ser destacadas ovalbumina, ovovitelina, ovotransferrina, ovomucóide, ovomucina, avidina e globulinas. Enzimas, por sua vez, são formadas principalmente por lisozima, glicosidases, catalases, esterases e peptidases. A síntese na clara de ovo ocorre no oviduto, com posterior transporte para o ovário. A formação do albúmen decorre de uma sequência específica composta por ovulação, formação do tecido protéico, adição de íons, água e glícides e, por último, formação da casca.


|       A casca é constituida por carbonato de cálcio (98 %) e proteína  (2 %) As proteínas da casca envolvem a ovoceratina, proteína similar ao colágeno, e glicoproteínas. Junto à essas existe também um significativo conteúdo de glicosaminoglicanos (sulfato de condroitina). A calcificação da casca ocorre por uma migração de proteínas quelantes de cálcio ao oviduto, com consequente reabsorção de cálcio sanguíneo em mitocôndrias das células da casca. Essas células permitem a síntese de carbonato de sódio, utilizável como um tampão, e de cálcio, para calcificação.


### Formação da casca de ovos

|       A membrana interna da casca constitui sua base orgânica, sendo formada por proteínas e mucopolissacárides. Sobre esta base, são formados núcleos de calcificação, constituindo a camada mamilar. Sobre esta camada vai ocorrendo a deposição de carbonato de cálcio, formando a camada esponjos, mais espessa, e responsável pela resistência da casca. A última camada do ovo é a cutícula, composta por matéria orgânica, e cobrindo a superfície do ovo. A cutícula veda os poros da casca, evitando a perda de umidade e reduzindo a contaminação microbiana.


|       A casca de ovo possui como elemento principal de resistência mecânica à pressões externas o cálcio, na forma de carbonatada de CaCO3. Para tanto, requer que sua forma orgânica seja produzida a partir de bicarbonato advindo do gás carbônico eliminado na respiração celular e de água, reação catalisada pela anidrase carbônica da mucosa uterina, além de um aporte de cálcio iônico do plasma sanguíneo.


### Qualidade da casca de ovos

|       De particular interesse, ovos trincados representam uma importante fonte de perda econômica para o produtor de ovos. Países desenvolvidos como Reino Unido, Alemanha e EUA, estimam em torno de 7 % os ovos de qualidade inferior devido a avarias na casca. Em termos econômicos, este último país calcula em 1,32 dólares a perda por ave atribuida a ovos com problemas na casca. No Brasil, o plantel nacional de poedeiras comerciais em postura foi estimado no início do milênio em 56 milhões de aves, e representou a produção de 16 bilhões de ovos (produção anual de 286 ovos por ave em 1997). Neste sentido, pode-se verificar a perda monetária substancial decorrente do problema em questão (R$ 74 milhões de reais em 1996). 


|       Os fatores que afetam a qualidade da casca de ovo parecem incluir o teor de cálcio da mesma (2,1 a 2,4 g/ovo de tamanho médio, otimizados a 3,75 g/ave/dia recomendados), de fósforo (22 mg/ovo, obtidos a 0,7 g/ave/dia), de eletrólitos (bicarbonato e H+), vitamina D (sintetizada na forma inativa na pele da ave), microminerais (zinco e manganês, componentes respectivos da anidrase carbônica e de mucopolissacárides da matriz orgânica da casca), e aluminosilicatos (melhoria da qualidade por aumento na capacidade de troca iônica).  

|       Cálcio e fósforo não devem possuir teores alterados, nem para cima, nem para baixo, uma vez que o metabolismo de ambos é interdependente, além de resultar em alterações na palatabilidade. Altos níveis de cloro induzem acidose, reduzindo o bicarbonato plasmático, enquanto sódio parece melhorar a qualidade da casca (bicarbonato de sódio). Fatores extrínsecos, por sua vez, podem incluir a idade da ave e temperatura ambiente, ambos inversamente proporcionais à qualidade, genética (herdabilidade da espessura da casca em torno de 40 %), e uso de medicamentos (sulfonamidas inibem anidrase carbônica e reduzem a absorção de cálcio).
