---
title: "Bioquímica de Rações"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       	Rações constitui um tema frequente da nutrição animal, uma vez que o seu manejo determina, primariamente, a melhoria da produtividade animal. Na Natureza os diversos nutrientres necessários ao consumo animal nem sempre se encontram presentes no campo, em razão de um grande número de variáveis, tais como solo, culturas autóctones e sazonalidade, o que sugere esforços do produtor para a manufatura de um alimento o mais completo possível para determinado rebanho. Neste sentido, o balanceamento e cálculo de nutrientes em rações, bem como o seu processamento mecânico e térmico contribuem para o sucesso da produtividade no campo.

|       A ração pode ser definida como a quantidade que um animal recebe em um período de 24 horas, contrariamente à dieta, quantidade total de alimentos ingeridos em 24 horas, incluindo a água. A ração deve ser padronizada em função do padrão genético animal, do nível de produção e fase do ciclo produtivo, da disponibilidade de alimentos e de sua escolha, e das exigências nutricionais de cada raça. Assim, para maximizar o potencial produtivo animal, deve se ter em mente as necessidades distintas de diferentes padrões genéticos, e observar a fase produtiva e de crescimento do animal, de forma a não superalimentar o espécime. Restos industriais e despojos de cultivares podem também se empregados na elaboração da ração, desde que sob conservação ideal, uma vez que tendem a degradação espontânea e biológico ao longo do tempo. Aspectos sazonais também influem na seleção de nutrientes, devido à disponibilidade de matérias-primas e da flexibilidade de custos. 

## Detalhes

|       No formalismo matemático empregado para o cálculo de rações, deve-se considerar alguns aspectos arbitrários, considerando-se a confiabilidade, disponibilidade e adequação de dados. Os cálculos são então realizados por técnicas de ensaio e erro, ajustes lineares e curvilineares de produtividade, sistemas de equações, e pacotes estatísticos. Nesse sentido, a elaboração do arraçoamento leva em consideração alguns parâmetros de fibras, proteínas e lípides, tais como os mencionados anteriormente (bioenergética).


### Volumosos e concentrados.

|       O sistema de arraçoamento brasileiro utiliza normalmente alta proporção de volumosos no preparo de rações, visando o fornecimento total da dieta do animal no confinamento. De modo geral as rações possuem entre 50 a 80 % de volumosos na matéria seca. Os volumosos mais comuns são a silagem de capins tropicais, silagem ou capineira de capim-elefante, silagem de milho e sorgo, a cana picada e o bagaço de cana hidrolisado. Entre os volumosos menos utilizados encontram-se o milheto, fenos de gramíneas, palhadas de culturas, silagem de girassol, e casca de caroço de algodão. O uso de elevada quantidade de volumoso nas rações de confinamento no Brasil é decorrente do seu baixo custo de produção, além da necessidades de áreas relativamente pequenas.


|       Concentrados são alimentos que fornecem proteína ou energia, o segundo  pelo alto teor fermentativo de seus ingredientes. Assim, são considerados concentrados energéticos de uso corrente no país o milho e sorgo moído, o farelo de trigo e arroz, o melaço e a polpa cítrica. Entre os concentrados protéicos mais utilizados destacam-se os farelos de soja e algodão, a levedura seca de cana-de-açúcar, o farelo de amendoim, o caroço de algodão e a cama de frango.

### Sal arraçoado

|       O sal arraçoado é um produto desenvolvido para aumentar a ingestão de uréia pelos animais durante o período seco do ano, e que deve ser utilizado somente em situações de grande disponibilidade de forragens. Esse sal possui de 30 a 50 % de farelos que funcionam mais como palatabilizantes do que como fontes de energia ou proteína.

|       A mistura ideal deve proporcionar uma ingestão de um grama desse sal para cada quilograma de peso vivo do animal. A utilização de sal arraçoado pode resultar um diferencial de ganho de até 300 g/animal/dia, em pastagens cuja qualidade é próxima das exigências de manutenção.


### Controle de qualidade de matérias-primas

|       Apesar do assunto vasto e multidisciplinar, o controle de qualidade de matérias-primas é o mais direto a ser estabelecido em uma empresa, visto que depende exclusivamente de ensaios microbiológicos (Salmonella sp), bioquímicos e físico-químicos específicos. De modo geral, contudo, faz-se mister a complementação de controle dos processos industriais (qualidade da área física da empresa, do acesso humano, das pesagens, da produção da ração, dos equipamentos, da distribuição e da mão-de-obra). 


|       Na arraçoamento da matéria-prima considera-se fontes primárias para análise como milho, farelo de soja, farinha de carne e osso, e sal. No controle do milho, grãos amarelos destinados a alimentação animal, considera-se a umidade, em torno de 15 %, impurezas, aceitáveis a um limite máximo de 1 %, podres, ardidos e brotados (limites de 0,5 %), partidos e quebrados (restrição se houver contaminações e impurezas).
	
	
|       No controle de qualidade do farelo de soja, produto obtido do grão de soja, após a extração do óleo com solventes seguido de tostagem, deve se observar coloração e odores característicos (sob a forma de pellets ou farelados), impurezas (não aceitáveis), e níveis bromatológicos específicos (atividade urease – 0,05-0,3 %, solubilidade – 75 a 83 %, valor protéico mínimo – 45,5 %, fibra bruta máxima – 7 %). 

|       A farinha de carne e osso, por sua vez, é definida como um produto de graxaria de frigoríficos, resultante de ossos e tecidos cárneos bovinos e suínos, prensado para a retirada parcial de gorduras e finamente moído. O seu controle de qualidade leva em conta a apresentação (farelado e ensacado), a granulometria (dependente do diâmetro de peneira), teste de Eber (negativo), ácidez máxima em hidróxido de sódio de 6 %, e aspectos bromatológicos (extrato etéreo – 8 a 12 %, fósforo mínimo a 6 %, e ausência de sangue). Finalmente, o cloreto de sódio é verificado a partir da isenção de impurezas, e de umidade máxima a 4% e, uso de melaço, através do grau Brix.	


### Extrusão

|       A extrusão de alimentos é um processo que visa a melhoria na palatabilidade, digestibilidade e absorção de rações e produtos derivados. O processo de extrusão é particularmente importante na viabilidade nutricional de animais de estimação. Através da extrusão é possível obter produtos secos e expandidos, produtos semi-úmidos, macios, “snacks” e “treats” (agrados e guloseimas). No processo de extrusão ocorre um cozimento do alimento pela combinação de umidade (25 %), pressão (10 atm), e atrito mecânico, os quais acabam por provocar altas temperaturas (1500C), resultando na gelatinização de amido, rearranjo de proteínas, expansão e reestruturação de componentes nutricionais, e a expansão exotérmica das partículas. 


|       O principal efeito da extrusão no amido é a quebra da molécula, transformando-o em açúcares mais absorvíveis (glicose). A extrusão atua como inibidor de crescimento microbiano, além de promover um reagrupamnto de ligações poliméricas e a formação de complexos lipoprotéicos. 

