---
title: "Bioquímica dos Solos e Ciclo de Nutrientes"
lang: pt
---


```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```



## Introdução

|       	Dos elementos químicos que compõem o solo destacam-se o carbono, o nitrogênio, o fósforo e o enxofre. Todos esses sofrem uma biotransformação cíclica mediada pela atividade microbiana do solo, e que resulta em formas inorgânicas e orgânicas do mesmo. A assimilação, redução, imobilização e mineralização constituem processos comuns a estes elementos, visando sua incorporação e posterior degradação de carboidratos, proteínas, lipídios e ácidos nucléicos para a nutrição microbiana e vegetal.


## Detalhes


### Ciclo do Carbono

|       A fixação de carbono por plantas verdes no solo é fonte produtora de blocos biossintéticos, como carboidratos, lignina, e proteínas. O caminho reverso da decomposição destes em CO2 e água após a senescência e morte do exemplar é mediado pela atividade de microrganismos em contato com o solo. Em resumo, o ciclo opera por fixação, armazenamento e liberação de nutrientes. Os constituintes orgânicos do solo são formados pela via epígea e endógena. A primeira encerra restos vegetais e animais depositados na superfície, ao passo que a via endógena, a exudação da raiz viva e produtos da planta em decomposição. 


|       Dos diversos carboidratos que presentes no solo, a celulose responde por 30 a 60 % do substrato orgânico incorporado. Arabinoglicanos e xiloglicanos também fazem parte como estruturas da parede celular vegetal. A lignina, unidades ligadas por fenilpropano, são degradadas inicalmente apenas por alguns fungos basidiomicetos e bactérias ligninolíticas. Além destes, a produção de matéria orgânica glicídica no solo conta ainda com pectinas e heteropolímeros altamente ramificados.


|       O solo também possui alguns complexos enzimáticos que permitem humificação e mineralização do solo, tais como celulase, urease, fosfatase, deamidase, glicosidase, e algumas proteases. Uma atividade enzimática constante dos solos é aquela que permite a formação do húmus, uma formação e acumulação de partes orgânicas no solo. 


|       A humificação é realizada por oxidação de substratos hidrolisados monoméricos, produzindo macromoléculas de tonalidade escura, bem como por transformações microbianas de fenóis e quinonas (decomposição da lignina). As funções da humificação envolvem o favorecimento de agregação de partículas do solo, uma capacidade de troca iônica pro argilominerais e matéria orgânica contida no mesmo, além de nutrição mineral para as plantas através da liberação lenta de nitrogênio, fósforo e enxofre.


### Ciclo do Nitrogênio 

|       As vias do metabolismo nitrogenado estão centradas numa sucessão de reações bioquímicas do elemento na superfície do solo mediadas principalmente pro microrganismos, como fungos e bactérias. As fontes de nitrogênio são constituidas por restos vegetais e animais, fertilizantes, nitratos, e sais de amônio, além do nitrogênio fixado microbiologicamente. No solo existe um processo de mineralização do nitrogênio, uma transformação do nitrogênio orgânico em nitrato. Este processo encontra-se subdividido em amonificação, conduzido por organismos quimiorganotróficos, e nitrificação, efetivado por organismos quimiolitotróficos. 


|       Dois outros processo ocorrem metabolicamente com o nitrogênio dos solos: a imobilização e a desnitrificação. O primeiro se dá pela utilização do nitrogênio mineral pelo metabolismo microbiano, e ocorre simultaneamente à mineralização. O processo de desnitrificação, por sua vez, decorre da respiração anaeróbica, o que resulta em perdas gasosas de nitrogênio.

### Ciclo do Fósforo

|       O fósforo é um elemento químico de baixíssimo teor na atmosfera, tendo o seu reservatório natural na litosfera, já que não são conhecidas formas gasosas estáveis do elemento. Neste sentido, o fósforo entre pela biosfera por absorção de plantas e microrganismos, retornando ao solo por decomposição da matéria orgânica. 


|       O ciclo do fósforo no solo é formado por etapas de absorção vegetal e de transferência à cadeia heterotrófica. Estes processos decorrem do uso de fertilizantes, simultaneamente à transformações microbianas do fósforo solúvel no solo por imobilização e mineralização, com perdas significativas através de erosão e de lixiviação do solo. A imobilização do fósforo se dá por sua conversão do estado solúvem em orgânico, o oposto da mineralização. 

|       O fósforo inorgânico é formado por sais cristalinos, como hidroxiapatita e carbonoapatita. O fósforo orgânico, por sua vez, é produzido pela oxidação de substratos vegetais e animais, tais como o fosfato de inositol, ácidos nucléicos e fosfolipídios.


### Ciclo do Enxofre

|       O enxofre é reduzido e assimilado na forma de sulfato inorgânico pela atividade microbiana do solo. Segue-se à assimilação a degradação microbiana através de dessulfurização de cisteína, metionina, acetil CoA, ferredoxina, e outras biomoléculas sulfatadas. 

|       A redução e liberação microbiana de enxofre é efetivada pela oxidação da matéria orgânica e transferência de elétrons para o sulfato. As fontes de enxofre no solo são constituidas por restos de animais e vegetais, fertilizantes, e por intemperização de rochas.

