---
title: "Interactive Graphs and Maps at School"
---


| This material aims to provide a set of *interactive and animated graphs and maps* for some topics found in *high school* subjects. These *teaching objects* use interactive *R* packages, mainly `plotly` and `gganimate`.

--------------------------------------------------------------

## Reproducible Interactive Teaching Objects (OIER) developed for elementary education

| The *Graphs & Maps* section of [Bioquanti](https://bioquanti.netlify.app/) has a repository of teaching objects of the same name accompanied by their commented code snippets, allowing for easy reproduction, customization, and creation of new materials for sharing. The repository covers the areas of *Mathematics, Natural Sciences, Humanities, and Languages*. It is divided into classes, each with some illustrative *Reproducible Interactive Teaching Objects (OIER)*: Mathematics, Physics, Chemistry, Biology, Humanities, History, Geography, and Languages. Each OIER is referenced by its title along with some related codes from the *BNCC.* In order to simplify the production of each OIER for graphs and maps related to basic education, as well as to facilitate the use of `R` in the *RStudio* environment, the use of the `plotly` library was favored. 

| Occasionally, the `ggplot2` library was used for more elaborate graphs, and subsequent conversion to `plotly` interactivity using the package's `ggplotly` function. Sometimes the `gganimate` package was also used, which allows the creation of an animation by sequential representation of `ggplot2` graphs, as well as some packages specific to a given situation.
\

| Each OIER is structured in three parts:

```{r, eval=FALSE}
1. The OIER itself, with title and BNCC codes;

2. The source code used to generate the object;

3. Suggestions for modifications to the source code to obtain a final object that is different from the original.
```

## Teaching objects and codes


[1. Mathematics](matematica_en.qmd)
\

[2. Physics](fisica_en.qmd)
\

[3. Biology](biologia_en.qmd)
\

[4. Humanities](humanas_en.qmd)
\

[5. History](historia_en.qmd)
\

[6. Geography](geografia_en.qmd)
\

[7. Languages](linguagens_en.qmd)
