---
title: "Some features of Jmol as a molecular viewer:"
---

1. Educational and intuitive program;
2. Complete program with free distribution and source code, not restricted to demonstration or educational versions;
3. Does not require installation, only initialization of an executable file in *Java*.
4. Since it does not require installation, simply copy the program directory for use on removable media;
5. Allows saving the image as an interactive PNG, whose file can be opened in an image viewer, or integrated, directly in Jmol.
6. If the images are renderable, simply click and drag them to the *Jmol* window;
7. Allows running independently of the *Java* language, via the *JSmol* applet, entirely in HTML5, which allows its use by any internet browser;
8. Allows insertion of three-dimensional models into internet pages via *JavaScript*; 9. It is widely used in the production of images and dynamic models on various *websites* and books;
10. It has a large number of tutorials available *online.*
11. It adopts simple command lines;
12. It makes it easier to identify typing errors, highlighting the command line in red; 1. It allows *scripts* saved as videos by a sequential set of commands;
13. It allows the use of more than one section at the same time;
14. It allows the use of a *kit* of development tools for other *Java* applications.
15. It allows for a *menu* that can be customized by the user;
16. It has a very active *user group* on the internet;
17. It runs images in HTML5, which allows independence of device (mobile or not) and operating system;
18. It includes crystallographic symmetry analysis. 19. Loads and allows the production of several molecular surface formats (van der Waals, molecular surface, solvent accessible area - SAS, electrostatic potential);
20. Allows loading of files in over 60 formats, including Protein Data Bank (PDB), Crystallographic Information File (CIF), MDL Molfile (mol), and Chemical Markup Language (CML), as well as Pymol sessions (PSE);
21. Allows loading of the molecule from the Internet, by introducing PDB, SMILES or PubChem code, in addition to SMART language;
22. Exports to GIF, JPG, PNG, PDF, WRL, POV-Ray, and OBJ;
23. Has a generic JavaScript library for Swing.
24. Allows reading of spectroscopic formats of JCAMP-DX, CML, AnIML by JSpecView.
25. Allows simulation of 1H and 13C NMR spectrograms. 26. Produces interactive spectra in PDF format for IR, Raman, NMR, GC/MS, and UV/VIS;
27. Supports energy calculations and minimization (MMFF94/UFF).
28. Allows for structure alignment;
29. Although it does not perform or have an extension for modeling, simulation, or molecular dynamics modules, it allows for a sketch of some of these actions (e.g., optimization of protein secondary structure, tracking of likely interaction sites).
30. It is more limited for structure alignment activities for comparison or directed mutations, in relation to some competitors;
31. It has very few *plugins*, contrary to some competitors;
32. Renders high-quality vector images for publication, although indirectly (POV-ray);
33. It is a program for molecular visualization with command lines and programming accessible via a browser, which sets it apart from its competitors.