---
title: "Carbohydrates"
---

<!-- Google tag (gtag.js) -->

```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```

```{=html}
<script>
 window.dataLayer = window.dataLayer || [];
 function gtag(){dataLayer.push(arguments);}
 gtag('js', new Date());

 gtag('config', 'G-S1L73VGCG5');
</script>
```



## Monosaccharides

|
| Carbohydrates are defined as **polyhydroxyaldehydes**\index{polyhydroxyaldehyde} or **polyhydroxyacetones**\index{polyhydroxyketone}, from the simplest carbon skeleton of a trisaccharide, as represented by the *Fisher projection* for [glyceraldehyde](https://chemapps.stolaf.edu/jmol/jmol.php?model=glyceraldehyde&script=Console){target="_blank"} and for [dihydroxyketone](https://chemapps.stolaf.edu/jmol/jmol.php?model=dihydroxyacetone&script=Console){target="_blank"}. Thus, carbohydrates are now referred to as **aldoses**\index{aldose} or as **ketoses**\index{ketose}.

| Carbohydrates, like amino acids, have a *chiral center*\index{chiral center} and, consequently, an **optical isomerism**\index{optical isomerism}, detectable in a polarimeter. Identify the *chiral carbon* for [glyceraldehyde](https://chemapps.stolaf.edu/jmol/jmol.php?model=glyceraldehyde&script=Console){target="_blank"}. Also identify whether the model refers to *D-glyceraldehyde* or *L-glyceraldehyde*.

| To do this, rotate the molecule so that the carbonyl (C=O) is facing down, and with its oxygen atom on the right. If the hydroxyl group (-OH) is on the right of the *Jmol* screen, it is D-glyceraldehyde. Otherwise, it will be L-glyceraldehyde. It can be seen that the model accessed by the *link* is of a D-glyceraldehyde.

| From these molecules, it is possible to compose several carbohydrates by varying the number of their carbons (*diose, triose, tetrose, pentose, hexose, heptose*) and/or the function that defines them (*aldoses or ketoses*). Thus, a *glucopyranose* molecule can be represented by a [glucose](https://chemapps.stolaf.edu/jmol/jmol.php?model=glucose&script=Console){target="_blank"}

| The linear structure represented above is of very low proportion in solution. The most common structure involves a *cyclization* originating from an initial twist between *C-4* and *C-5*, which brings an alcohol closer to the carbohydrate functional group. In this way, a reaction occurs between the alcohol function and an aldehyde/ketone, producing a *hemiacetal* (aldehyde + R-OH) or a *hemiketal* (ketone + R-OH). With the cyclization, the carbohydrate gains another chiral center.

| It is worth taking a moment here to consider the acquisition of new models for visualization by *Jmol*. Up to now, and with rare exceptions, we have used *PDB* attribute files related to the deposit of crystallographic biomolecules in the homonymous site. Other biomolecules are easily accessible by *Jmol* itself, by *File, Get Mol*, which is mirrored to the *web* by the structures loaded from the [Chemapps-Stolaf](https://chemapps.stolaf.edu/jmol/jmol.php?pdbid=XXX&script=Console){target="_blank"} site.

| However, for other molecules, such as those contained in this chapter, the structures are scattered throughout the internet, requiring their *download* and subsequent loading into *Jmol*.

| Remembering a feature of *Jmol*, to better understand the concepts reported in this material, in addition to viewing the image related to each subject in a common image program, it is also possible to click and drag the *PNG* (*Portable Network Graphics*) image file downloaded from this site to the main *Jmol* window. This will allow a more consolidated study, since it is possible to observe the molecules in three-dimensional space as was done in the previous chapters, being able to rotate them, direct their observation to a specific region, change colors and representations, calculate distances and angles, among others.

| To illustrate what was said, load the model of [glucose under ring closure](./figuras/glc_closing.png){target="_blank"} onto your PC, and observe the details of the reaction between the alcohol function and aldehyde that culminates in the production of the *hemiacetal*.

| Is it difficult to visualize? Then try loading the [glucose animation under closure](./figuras/glc_open_close.png){target="_blank"} model into *Jmol*

| With cyclization, the monosaccharide also acquires a **conformational isomerism**\index{conformational isomerism}. Thus, the conformation of a *cyclohexane*\index{cyclohexane} for the *pyran*\index{pyran} ring (e.g. glucose, a pyranose) or *furan*\index{furan} (e.g. fructose, a furanose) can vary. The main conformers are the [boat](./figuras/boat.png){target="_blank"} and the [chair](./figuras/chair.png){target="_blank"}, the latter being energetically more favorable.

| Reinforcing, both structures can be observed three-dimensionally by lowering them on the PC and dragging one of the images with the *mouse* to the open *Jmol* screen. And of course, you can also open the image in the program by *File, Open* !

| It is also possible to visualize the **configurational isomerism** of carbohydrates using *Jmol*. To do so, load the [alpha configuration of glucose](./figuras/glucose-a.png){target="_blank"} into *Jmol*. Now position the oxygen in the ring to the *North*, so that the *-CH*$_{2}$OH function is facing left. Tilt the molecule forward little by little and observe how the alcohol of the anomeric carbon in C1 (just to the right of the oxygen in the ring) is located outside the plane of the ring. This is the $\alpha$ configuration of glucose.

| Repeat the procedure for the [beta configuration of fructose](./figuras/beta-fru.png){target="_blank"}, a ketose, to see that the arrangement of the *-OH* group mentioned is not exactly above the plane, as in the two-dimensional representations of textbooks, although it is quite different from the alpha isomers.

## Carbohydrate derivatives

| In addition to \index{constitutional isomerism}*constitutional isomerism* (aldo/keto), \index{optical isomerism}*optical isomerism* (L/D), \index{conformational isomerism}*conformational isomerism* (boat/chair), and \index{configurational isomerism}*configurational isomerism* ($\alpha$/$\beta$), monosaccharides can undergo several reactions, such as *sulfatation* ([chondroitin](./figuras/chondroitin.png){target="_blank"}\index{chondroitin}), *amination* ([glucosamine](https://chemapps.stolaf.edu/jmol/jmol.php?model=glucosamine&script=Console){target="_blank"}\index{glucosamine}), *oxidation*, *reduction*, *phosphorylation*, *methylation*, *introduction of an alcohol* (polyol, "sorbitol.png") or *deoxidation* (deoxysugar). These changes enrich the structural and functional diversity of carbohydrates, and are related to variations in the interaction with the solvent, and with other biomolecules, such as those presented in cellular interaction and signaling, among others.

## Oligosaccharides

| They are defined from an [*acetal (glycosidic) bond*](./figuras/maltose-lig.png){target="_blank"} between the anomeric carbons of two monosaccharides. This bond also involves the release of a water molecule. As observed by the model above, the acetal bond\index{acetal bond} is formed between carbons C1 and C4.

| The glycosidic bond can also be characterized as $\alpha$ (ex: [maltose](./figuras/maltose.png){target="_blank"}\index{maltose}) or $\beta$ (ex: [cellobiose](./figuras/cellobiose.png){target="_blank"}\index{cellobiose}) depending on the *axial or sagittal vector* of a functional group, in this case *-OH*, from the C1 carbon of the 1st monomer. To highlight this difference, proceed in a similar way to what was done with the glucose molecules above in the text.

| First load the [maltose](./figuras/maltose.png){target="_blank"}. Position the molecule in such a way that the oxygen of the ring of the 1st. residue, the one that has the C1 label on its carbon $\alpha$, is on the right. Now tilt the structure and highlight how the glycosidic bond moves away from the plane of the 1st residue. This is the *bond* $\alpha$, considered in the books as below the two-dimensional plane. Repeat this procedure with [cellobiose](./figuras/cellobiose.png){target="_blank"}, and see the difference from a $\beta$-glycosidic bond. Note how the *bond* $\beta$ occurs in a dimer of [cellobiose](https://chemapps.stolaf.edu/jmol/jmol.php?model=cellobiose&script=Console){target="_blank"}\index{cellobiose}

| In the official nomenclature, oligosaccharides have the numbering of the carbons involved in the glycosidic bond, as well as the direction of the reaction. Thus, we have [sucrose](https://chemapps.stolaf.edu/jmol/jmol.php?model=sucrose&script=Console){target="_blank"}\index{sucrose}, table sugar, or $\alpha$-D-glucopyranosyl (1,2)-$\beta$-D-fructofuranose, as a disaccharide formed by the acetal bond between a glucose residue and a fructose residue.

| Since the *glycosidic bond*\index{glycosidic bond} compromises the two *anomeric carbons*\index{anomeric carbon} involved in the formation of sucrose, it loses the reducing capacity of the carbonyl group. The same does not occur with [lactose](https://chemapps.stolaf.edu/jmol/jmol.php?model=XXX&script=Console){target="_blank"}\index{lactose}, whose glycosidic bond still allows a reducing potential\index{reducing potential} of a free anomer (Cu$^{+}$ to Cu$^{0}$, for example).

| Clinically, the deficiency of the enzyme $\beta$-galactosidase prevents the hydrolysis of the glycosidic bond of lactose, accumulating it in the tissues and inducing one of the forms of lactose malabsorption/intolerance.

| In this way, monosaccharides can join together to form disaccharides ([maltose](https://chemapps.stolaf.edu/jmol/jmol.php?model=maltose&script=Console){target="_blank"}\index{maltose}), trisaccharides ([maltotriose](https://chemapps.stolaf.edu/jmol/jmol.php?model=maltotriose&script=Console){target="_blank"}\index{maltotriose}), tetrasaccharides, etc.

| Some oligomers of approximately 15-50 units can also exhibit beneficial health properties, being considered *functional oligosaccharides*. An example of a functional oligosaccharide is [inulin](./figuras/inulin.png){target="_blank"}, a fructooligosaccharide composed of 30 fructose residues and one glucose residue, and related to digestive, antimicrobial and immunomodulatory benefits.

## Polysaccharides

| Although there is no consensus on their size, a polysaccharide is considered to be a polymer ranging from 300 to more than 50,000 monomeric residues. These polymers, or **glycans**\index{glycan}, can have the same monomer in their composition, thus being called *homoglycans*\index{homoglycan}, or different types of monomers, producing *heteroglycans*\index{heteroglycan}.

| The most common example of a homoglycan is *starch*\index{starch}. It is composed of a branched structure and a linear structure. The branched structure is called [amylopectin](./figuras/amylopectin.png){target="_blank"} (in the model, shown with 25 glucose residues). See a more concise structure of [amylopectin](https://chemapps.stolaf.edu/jmol/jmol.php?model=amylopectin&script=Console){target="_blank"}\index{amylopectin}.

| Branching occurs in the 1-6 direction between every 10-12 glucose residues. Animal [glycogen](./figuras/glycogen.png){target="_blank"}\index{glycogen} is similar to amylopectin, except for the greater degree of branching resulting from the spacing of 8-12 glucose residues. Here is a more concise model for rendering the [glycogen](https://chemapps.stolaf.edu/jmol/jmol.php?model=glycogen&script=Console){target="_blank"}\index{glycogen} Rotate the structure (concise or broader model) and notice that there is a central spiral in its molecule. This helical conformation represents [amylose](./figuras/amylose.png){target="_blank"}. Amylose has a linear structure and presents a helical conformation. Note that both glycogen and starch have this helical structure.

| Another common *homopolysaccharide* is [cellulose](./figuras/cellulose.png){target="_blank"}\index{cellulose}, a linear polymer of glucose residues. Both amylose and cellulose have conformations resulting from the *configuration* of their glycosidic bond, $\alpha$ for amylose and $\beta$ for cellulose.

### Other polysaccharides

| Several polysaccharides, homo or hetero, act functionally in cells, such as [hyaluronic acid](./figuras/acido-hialuronico.png){target="_blank"}\index{hyaluronic acid}, a heteroglycan of the vitreous humor and synovial fluid, formed by $\beta$-acetyl-N-glucosamine and glucuronic acid, or [pectin](./figuras/pectina.png){target="_blank"}\index{pectin}), a *water-soluble homopolysaccharide - soluble fiber*, present in the plant wall, and formed by galacturonic acid (polygalacturonic), rhamnose, arabinose and galactose.

| Other polysaccharides contribute to the constitutive structure of organisms, such as [chitin](./figuras/chitin.png){target="_blank"}\index{chitin}, a structural homoglycan in the exoskeleton of insects and crustaceans, formed by $\beta$-acetyl-N-glucosamine residues. Observe a more concise rendered model for [chitin](https://chemapps.stolaf.edu/jmol/jmol.php?model=chitin&script=Console){target="_blank"}\index{chitin}. Other polysaccharides also have biological activity, such as [heparin](https://chemapps.stolaf.edu/jmol/jmol.php?model=heparin&script=Console){target="_blank"}\index{heparin}, an anticoagulant that acts by chelating calcium ions.