---
title: "Lipids"
---

<!-- Google tag (gtag.js) -->

```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
 window.dataLayer = window.dataLayer || [];
 function gtag(){dataLayer.push(arguments);}
 gtag('js', new Date());

 gtag('config', 'G-S1L73VGCG5');
</script>
```


| For this chapter, some of the structures are not available in the database that renders the three-dimensional structures, from the [Cactus](https://cactus.nci.nih.gov/chemical/structure){target="_blank"} website, a source of *JSmol* models through the [Stolaff College](https://chemapps.stolaf.edu/jmol/jmol.php?model=water&script=Console){target="_blank"} portal. However, these structures will be made available as *PNG* images that can be rendered by *Jmol/JSmol*.

## Fatty acids and derivatives

| Lipids can be presented in two basic types: as **hydrocarbons**\index{hydrocarbon} formed by conjugation of ethylenes to carboxylic derivatives of hydrocarbons (derived from acetates), or as **steroids**\index{steroid}, structures of four fused hydrophobic rings and derived from isoprenes. [Palmitic acid](https://chemapps.stolaf.edu/jmol/jmol.php?model=palmitate&script=Console){target="_blank"} exemplifies the first type. Every fatty acid is formed by a hydrocarbon "tail" or alkyl chain, and a carboxylic acid "head". The carbon of the carboxylic group is numbered as *C1* or carbon $\alpha$, and the last carbon of the chain, as carbon $\omega$. Because they have a pKa value of around 4.8 to 7.7 (proportional to the size of the carbon chain), fatty acids tend to be partially ionized in physiological solution.

### Unsaturation and nomenclature of fatty acids

| Fatty acids can differ in size (number of carbons) and degree of unsaturation. [Palmitic acid](https://chemapps.stolaf.edu/jmol/jmol.php?model=palmitate&script=Console){target="_blank"} represents a fatty acid with saturated bonds, which classifies it as a \index{saturated fatty acid}**saturated fatty acid**. The insertion of a double bond limits the flexibility of the alkyl chain in this region, and promotes a conformational change that reduces its ability to adhere between molecules. This is an example of [oleic acid](https://chemapps.stolaf.edu/jmol/jmol.php?model=oleate&script=Console){target="_blank"}, an **unsaturated fatty acid**\index{unsaturated fatty acid} with 18 carbons (C-18).

| The area occupied by an unsaturated fatty acid is also larger, 32 Angstrom$^{2}$ for oleic acid\index{oleic acid}, while stearic acid, also a C-18, although saturated, has 21 Angstrom$^{2}$. Each double bond inserted into the structure of a fatty acid alters its local conformation, as exemplified for [linolenic acid](https://chemapps.stolaf.edu/jmol/jmol.php?model=linoleate&script=Console){target="_blank"}\index{linolenic acid}, with three double bonds in its structure.

| Unsaturations also give rise to two *configurational isomers*, *cis* and *trans*\index{cis and trans configuration}, depending on the positioning of the hydrogen atoms, whether opposite in the double bond (*trans*) or close to and on the same side of it (*cis*). Thus, *cis* fatty acids exhibit the hydrogen bond HC=CH in the same direction ([linolenic acid](https://chemapps.stolaf.edu/jmol/jmol.php?model=linoleate&script=Console){target="_blank"}, C18, linolenic acid), while *trans fatty acids* do so in opposite directions. Hence the name **trans fat**\index{trans fat} present in industrialized and ultra-processed products, and related to clinical dysfunctions, such as atherosclerosis and cardiac complications.

| Because it has the first double bond at the 3rd carbon counted from the last carbon of the chain (carbon $\omega$), linolenic acid\index{acid $\alpha$-linolenic} is also called $\omega$-3. This nomenclature allows us to differentiate \index{$\alpha$-linolenic acid}$\alpha$-linolenic acid, an $\omega$-3, from \index{$\gamma$-linolenic acid}$\gamma$-linolenic acid, an $\omega$-6. And by this nomenclature, [oleic acid](https://chemapps.stolaf.edu/jmol/jmol.php?model=oleate&script=Console){target="_blank"} is considered a fatty acid of the $\omega$-9 series.

| There are two acids considered **essential fatty acids**\index{essential fatty acid}, that is, they require ingestion since they are not produced in mammals, a $\omega$-3, linolenic acid, and a $\omega$-6, linoleic acid.\index{omega series}.

| A more technical nomenclature, which avoids structural synonyms, is the one that defines the position of each double bond in the structure. Thus, linolenic acid is named 18:3$^{\Delta~ 9,12,15}$, while linoleic acid displays the code 18:2$^{\Delta~ 9,12}$.

### Chemical reactions of fatty acids

| Fatty acids can undergo three main transformations: **rancidification**\index{rancidification}, **hydrogenation**\index{hydrogenation} and **saponification**\index{saponification}. **rancidification** results from the action of molecular oxygen, high temperature and/or microorganisms on unsaturations, promoting cleavage of the fatty acid and release of low molecular weight fatty derivatives, sometimes volatile, and with an unpleasant odor. Hydrogenation\* involves an industrial process on unsaturated bonds, making them saturated.

| *Saponification*, in turn, occurs when a strong alkali such as NaOH or KOH interacts with a more complex structure of fatty acids, the triglycerides, triglycerides or, more appropriately, \index{triacylglycerol}[triacylglycerols](https://chemapps.stolaf.edu/jmol/jmol.php?model=triglyceride&script=Console){target="_blank"}. These are formed by an ester linkage to each of the three fatty acids to the glycerol alcohol, as exemplified for [trimyristin](./figures/trimyristin.png){target="_blank"}. In short, saponification produces polar amphipathic structures at the end of the carboxylate's interaction with sodium or potassium ions, which allows its interaction with water, while the nonpolar tails allow interaction with lipid structures, promoting a reduction in the surface tension of the water around the target molecule and, more generally, the cleaning of fats.

| Thus, in saponification, the alkaline hydrolysis of the triglyceride releases [glycerol](https://chemapps.stolaf.edu/jmol/jmol.php?model=glycerol&script=Console){target="_blank"} and forms a mixture of free fatty acid salts with their ionized carboxylates in interaction with the alkali cation (Na$^{+}$ or K$^{+}$).

### Other derivatives

| Other structures derived from fatty acids include **phospholipids**\index{phospholipids}, **sphingolipids**\index{sphingolipids}, and **glycolipids**\index{glycolipids}. Of these, *phospholipids* are the most common and are present in the structure of biomembranes\index{biomembranes}, such as *lecithin*. Lecithin is actually a yellowish lipid compound, formed by mixtures of [phosphatidylcholine](https://chemapps.stolaf.edu/jmol/jmol.php?model=phosphatidylcholine&script=Console){target="_blank"}, [phosphatidylserine](https://chemapps.stolaf.edu/jmol/jmol.php?model=phosphatidylserine&script=Console){target="_blank"}, [phosphatidylethanolamine](https://chemapps.stolaf.edu/jmol/jmol.php?model=phosphatidylethanolamine&script=Console){target="_blank"}, [acid. phosphatidic acid](https://chemapps.stolaf.edu/jmol/jmol.php?model=phosphatidate&script=Console){target="_blank"} and *phosphatidylinositol*, a derivative of [inositol](https://chemapps.stolaf.edu/jmol/jmol.php?model=inositol&script=Console){target="_blank"}. But [lecithin](./figures/lecithin.png){target="_blank"} can also be considered alone as a molecule of 1-hexadecanoyl-2-(9Z,12Z-octadecadienoyl)-sn-glycero-3-phosphocholine, a phosphatidylcholine\index{phosphatidylcholine}. [Choline](https://chemapps.stolaf.edu/jmol/jmol.php?model=choline&script=Console){target="_blank"}, 2-hydroxyethyl-trimethylammonium, appears as the amino structure linked to the phosphate group.

| **Sphingolipids**, phospholipids commonly found in cell membranes such as the myelin sheath of axons, have a fatty acid-anchoring structure distinct from glycerol, [sphingosine](https://chemapps.stolaf.edu/jmol/jmol.php?model=sphingosine&script=Console){target="_blank"} (D-erythro-sphingosine). An example is *sphingomyelin*, usually formed by [phosphocholine](https://chemapps.stolaf.edu/jmol/jmol.php?model= phosphocholine&script=Console){target="_blank"} and [ceramide](https://chemapps.stolaf.edu/jmol/jmol.php?model= ceramide&script=Console){target="_blank"} or [phosphatidylethanolamine](https://chemapps.stolaf.edu/jmol/jmol.php?model=phosphatidylethanolamine&script=Console){target="_blank"}.
| [Ceramide](https://chemapps.stolaf.edu/jmol/jmol.php?model= ceramide&script=Console){target="_blank"} is also found in the skin of fruits such as apples, in earwax, and in the production of honey. Ceramides inhibit water evaporation in addition to acting physiologically in cellular regulation.
| Finally, **glycolipids** constitute lipids with a covalent bond to a monosaccharide, such as *cerebroside*, maintain the structural stability of the membrane and facilitate cellular recognition.

## Association of fatty acids

| Lipids, such as fatty acids, phospholipids or sphingolipids, can undergo self-association in aqueous solvents (blood, for example), leading to the formation of structures such as *liposomes*\index{liposome}, [micelles](./figures/micelle.png){target="_blank"}\index{micelle}, and [biological membranes](./figures/membrane.png){target="_blank"}\index{biomembrane}. Note that in all these associations water maintains its interaction with the polar face of the structure, as exemplified in Figures~\ref{micelle2} and ~\ref{membr}. In *reverse micelles*\index{reverse micelles}, on the other hand, the opposite occurs when in contact with solvent. The [biological membrane](./figures/membrane.png){target="_blank"}, as a lipid bilayer containing phospholipids, also has cholesterol between the aliphatic chains of phospho and sphingolipids, which allows reducing the effect of paracrystallinity with temperature, as well as an extensive set of integral and peripheral proteins, information not available in the structural model.

## Vitamin derivatives and inflammatory homeostasis

### Fat-soluble vitamins

| From aliphatic chains of 20 carbons, several compounds are produced, generating a group called **eicosanoids**\index{eicosanoid} *eicoso*, from the Greek, twenty). From this group, some vitamins are taken as examples, such as [retinol](https://chemapps.stolaf.edu/jmol/jmol.php?model=retinol&script=Console){target="_blank"} or *vitamin A*\index{vitamin A}, and [tocopherol](https://chemapps.stolaf.edu/jmol/jmol.php?model=tocopherol&script=Console){target="_blank"} or *vitamin E*\index{vitamin E}.

### Inflammation mediators

| Likewise, inflammation-balancing compounds are also synthesized from lipid precursors, especially [arachidonic acid](https://chemapps.stolaf.edu/jmol/jmol.php?model=arachidonate&script=Console){target="_blank"}\index{acid. arachidonic}, such as [prostaglandins](https://chemapps.stolaf.edu/jmol/jmol.php?model=prostaglandin&script=Console){target="_blank"}\index{prostaglandin}, [leukotrienes](./figures/leukotrieneB4.png){target="_blank"}\index{leukotriene}, and [thromboxanes](./figures/thromboxane.png){target="_blank"}\index{thromboxane}.

## Steroids

| The second major set of lipids derives from the overlapping linkage of [isoprenes](https://chemapps.stolaf.edu/jmol/jmol.php?model=isoprene&script=Console){target="_blank"}\index{isoprene}, *5C* structures that form a steroid molecule called [cholesterol](https://chemapps.stolaf.edu/jmol/jmol.php?model=cholesterol&script=Console){target="_blank"}\index{cholesterol}. Chemically, cholesterol is an alcohol formed from the fusion of four rings formed by *isoprenoids*, producing a *perhydrocyclophenanthrene*\index{perhydrocyclophenanthrene} ring. When in high levels, cholesterol can form [cholesterol crystals](./figures/cholesterol-crystal.png){target="_blank"}\index{cholesterol crystal} due to the *hydrophobic effect* between its molecules, excluding the aqueous solvent.

### Cholesterol derivatives
| From cholesterol, several steroid structures are biosynthesized, including *sex hormones* such as [testosterone](https://chemapps.stolaf.edu/jmol/jmol.php?model=testosterone&script=Console){target="_blank"}\index{testosterone} (or 17-hydroxy-androst-4-en-3-one, a C21), [progesterone](https://chemapps.stolaf.edu/jmol/jmol.php?model=progesterone&script=Console){target="_blank"}\index{progesterone}, and [estradiol](https://chemapps.stolaf.edu/jmol/jmol.php?model=estradiol&script=Console){target="_blank"}\index{estradiol}. *Mineralcorticoids* are also produced, such as [aldosterone](https://chemapps.stolaf.edu/jmol/jmol.php?model=aldosterone&script=Console){target="_blank"}\index{aldosterone} (also known as 11,21-dihydroxy-3,20-dioxo-pregn-4-en-18-al, a C21, for blood sodium control), [cortisol](https://chemapps.stolaf.edu/jmol/jmol.php?model=cortisol&script=Console){target="_blank"}\index{cortisol} (chemically, 11,17,21-trihydroxypregn-4-ene-3,20-dione, active in cellular catabolism), *fat-soluble vitamins* such as [vitamin D](https://chemapps.stolaf.edu/jmol/jmol.php?model=calciferol&script=Console){target="_blank"}\index{vitamin D} (calciferol or 7-dehydrocholecalciferol, calcium regulation) and [vitamin K](./figures/vitaminK.png){target="_blank"}\index{vitamin K} (or phylloquinone, warfarin, present in blood clotting), and *bile acids* (lipid emulsifiers), such as [cholic acid](https://chemapps.stolaf.edu/jmol/jmol.php?model=cholate&script=Console){target="_blank"}\index{ac. cholic}, [deoxycholic acid](https://chemapps.stolaf.edu/jmol/jmol.php?model=deoxycholate&script=Console){target="_blank"}\index{deoxycholic acid}, and [taurocholic acid](https://chemapps.stolaf.edu/jmol/jmol.php?model=taurocholate&script=Console){target="_blank"}\index{taurocholic acid}, the latter derived from [taurine](https://chemapps.stolaf.edu/jmol/jmol.php?model=taurine&script=Console){target="_blank"}\index{taurine}.